/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.gt.gs.gs11;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2011-06-23 15:23:29
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class InvoiceAndBlanInfoTempVO extends SuperVO {
	private String pk_corp;
	private UFDateTime ts;
	private String pk_balanceinfo_b;
	private Integer dr;
	private String pk_saleinvoice_b;
	private String pk_saleinvoice;
	private String pk_invblatemp;
	private String srownum;
	
	
	public String getPk_saleinvoice() {
		return pk_saleinvoice;
	}
	public void setPk_saleinvoice(String pk_saleinvoice) {
		this.pk_saleinvoice = pk_saleinvoice;
	}
	public String getSrownum() {
		return srownum;
	}
	public void setSrownum(String srownum) {
		this.srownum = srownum;
	}
	public String getPk_invblatemp() {
		return pk_invblatemp;
	}
	public void setPk_invblatemp(String pk_invblatemp) {
		this.pk_invblatemp = pk_invblatemp;
	}
	public String getPk_saleinvoice_b() {
		return pk_saleinvoice_b;
	}
	public void setPk_saleinvoice_b(String pk_saleinvoice_b) {
		this.pk_saleinvoice_b = pk_saleinvoice_b;
	}
	

	public static final String PK_CORP = "pk_corp";
	public static final String PK_BALANCEINFO_B = "pk_balanceinfo_b";
	public static final String TS = "ts";
	public static final String DR = "dr";
	public static final String PK_SALEINVOICE_B = "pk_saleinvoice_b";
	public static final String PK_INVBLATEMP = "pk_invblatemp";
		
	
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2011-06-23 15:23:29
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2011-06-23 15:23:29
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2011-06-23 15:23:29
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2011-06-23 15:23:29
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	    
	/**
	 * 属性pk_balanceinfo_b的Getter方法.
	 * 创建日期:2011-06-23 15:23:29
	 * @return String
	 */
	public String getPk_balanceinfo_b () {
		return pk_balanceinfo_b;
	}   
	/**
	 * 属性pk_balanceinfo_b的Setter方法.
	 * 创建日期:2011-06-23 15:23:29
	 * @param newPk_balanceinfo_b String
	 */
	public void setPk_balanceinfo_b (String newPk_balanceinfo_b ) {
	 	this.pk_balanceinfo_b = newPk_balanceinfo_b;
	} 	  
  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2011-06-23 15:23:29
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2011-06-23 15:23:29
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-06-23 15:23:29
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-06-23 15:23:29
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_invblatemp";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2011-06-23 15:23:29
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "gt_invblatemp";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-06-23 15:23:29
	  */
     public InvoiceAndBlanInfoTempVO() {
		super();	
	}    
} 
