/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.jyglgt.pub;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-01-10 17:49:42
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class EventBVO extends SuperVO {
	private String pk_corp;
	private UFDateTime ts;
	private String vdef9;
	private String pk_event_b;
	private String pk_event;
	private String sjr;
	private String vdef1;
	private String vdef8;
	private String vdef10;
	private String vdef2;
	private String vdef5;
	private String vmemo;
	private String vdef3;
	private String vdef6;
	private String sjryx;
	private Integer dr;
	private String vdef4;
	private String vdef7;

	public static final String PK_CORP = "pk_corp";
	public static final String VDEF9 = "vdef9";
	public static final String CSH_EVENT_B = "csh_event_b";
	public static final String CSH_EVENT = "csh_event";
	public static final String SJR = "sjr";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF8 = "vdef8";
	public static final String VDEF10 = "vdef10";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF5 = "vdef5";
	public static final String VMEMO = "vmemo";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF6 = "vdef6";
	public static final String SJRYX = "sjryx";
	public static final String VDEF4 = "vdef4";
	public static final String VDEF7 = "vdef7";
			
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @return String
	 */
	public String getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @param newVdef9 String
	 */
	public void setVdef9 (String newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	
	
	public String getPk_event_b() {
		return pk_event_b;
	}
	public void setPk_event_b(String pk_event_b) {
		this.pk_event_b = pk_event_b;
	}
	public String getPk_event() {
		return pk_event;
	}
	public void setPk_event(String pk_event) {
		this.pk_event = pk_event;
	}
	/**
	 * 属性sjr的Getter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @return String
	 */
	public String getSjr () {
		return sjr;
	}   
	/**
	 * 属性sjr的Setter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @param newSjr String
	 */
	public void setSjr (String newSjr ) {
	 	this.sjr = newSjr;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @return String
	 */
	public String getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @param newVdef1 String
	 */
	public void setVdef1 (String newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @return String
	 */
	public String getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @param newVdef8 String
	 */
	public void setVdef8 (String newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @return String
	 */
	public String getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @param newVdef10 String
	 */
	public void setVdef10 (String newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @return String
	 */
	public String getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @param newVdef2 String
	 */
	public void setVdef2 (String newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @return String
	 */
	public String getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @param newVdef5 String
	 */
	public void setVdef5 (String newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性vmemo的Getter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @return String
	 */
	public String getVmemo () {
		return vmemo;
	}   
	/**
	 * 属性vmemo的Setter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @param newVmemo String
	 */
	public void setVmemo (String newVmemo ) {
	 	this.vmemo = newVmemo;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @return String
	 */
	public String getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @param newVdef3 String
	 */
	public void setVdef3 (String newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @return String
	 */
	public String getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @param newVdef6 String
	 */
	public void setVdef6 (String newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性sjryx的Getter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @return String
	 */
	public String getSjryx () {
		return sjryx;
	}   
	/**
	 * 属性sjryx的Setter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @param newSjryx String
	 */
	public void setSjryx (String newSjryx ) {
	 	this.sjryx = newSjryx;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @return String
	 */
	public String getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @param newVdef4 String
	 */
	public void setVdef4 (String newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @return String
	 */
	public String getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2013-01-10 17:49:42
	 * @param newVdef7 String
	 */
	public void setVdef7 (String newVdef7 ) {
	 	this.vdef7 = newVdef7;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-01-10 17:49:42
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_event";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-01-10 17:49:42
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_event_b";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-01-10 17:49:42
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "csh_event_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-01-10 17:49:42
	  */
     public EventBVO() {
		super();	
	}    
} 
