/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.gt.gs.gs11;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2014-10-25 16:35:54
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class GeneralBVO extends SuperVO {
	private UFDouble nquotentprice;
	private String pk_corp;
	private UFDouble nreplenishedastnum;
	private String vuserdef25;
	private String cselastunitid;
	private UFDouble fbillrowflag;
	private String cvendorid;
	private String drequiretime;
	private String cquotecurrency;
	private String vbatchcode;
	private String vuserdef6;
	private String vuserdef32;
	private UFDate dfirstbilldate;
	private String pk_packsort;
	private UFDouble ntaxprice;
	private UFDouble nquoteunitrate;
	private String pk_cubasdoc;
	private String vuserdef5;
	private String creceiveareaid;
	private String cinvbasid;
	private String vuserdef37;
	private String cquoteunitid;
	private UFBoolean btoinzgflag;
	private String vuserdef9;
	private String csrc2billbid;
	private String ccostobject;
	private String pk_invoicecorp;
	private String vuserdef36;
	private UFBoolean fassertcardflag;
	private String cprojectid;
	private UFDouble ncountnum;
	private String vuserdef13;
	private String vuserdef29;
	private UFDouble ntranoutastnum;
	private UFDate dstandbydate;
	private String vproductbatch;
	private UFBoolean flargess;
	private String cworkcenterid;
	private String corder_bb1id;
	private UFDouble nquotemny;
	private String vuserdef2;
	private UFDouble nquoteunitnum;
	private String pk_defdoc19;
	private String pk_defdoc10;
	private String vuserdef3;
	private String vuserdef11;
	private String vsrc2billcode;
	private String pk_defdoc18;
	private String csourcebillhid;
	private String vuserdef41;
	private String vuserdef4;
	private String creceivepointid;
	private String crowno;
	private String vtransfercode;
	private String vvehiclecode;
	private String pk_reqcorp;
	private String vuserdef12;
	private String vuserdef8;
	private UFBoolean btooutzgflag;
	private String cfreezeid;
	private String pk_bodycalbody;
	private String pk_defdoc7;
	private String vuserdef10;
	private UFDouble nretastnum;
	private String cbodywarehouseid;
	private String vsourcebillcode;
	private String csumid;
	private String pk_defdoc12;
	private String csourcewasttype;
	private String vsourcewastcode;
	private String vsignwastcode;
	private String pk_defdoc6;
	private String csrc2billhid;
	private UFDouble ninassistnum;
	private String vsourcerowno;
	private UFDouble nsaleprice;
	private String pk_defdoc2;
	private String csignwasttype;
	private UFDouble ncorrespondnum;
	private String vuserdef39;
	private String pk_defdoc3;
	private String csrc2billtype;
	private String cbodybilltypecode;
	private String vsrc2billrowno;
	private String vuserdef27;
	private UFDouble naccumtonum;
	private UFDouble nplannedmny;
	private UFBoolean bsourcelargess;
	private String vreceiveaddress;
	private UFDouble nretgrossnum;
	private String csourcetype;
	private UFDouble nmny;
	private UFDouble nshouldoutnum;
	private String vfree10;
	private UFDate dvalidate;
	private UFBoolean bzgflag;
	private String pk_defdoc11;
	private String vuserdef28;
	private String vcorrespondrowno;
	private UFDouble ntaxmny;
	private UFDouble nprice;
	private String vuserdef7;
	private String pk_defdoc4;
	private UFDouble nshouldoutassistnum;
	private String vuserdef38;
	private String vuserdef26;
	private UFDouble ninnum;
	private String creceieveid;
	private UFDouble dr;
	private UFDouble ntranoutnum;
	private String cwp;
	private UFDateTime ts;
	private UFDouble nbarcodenum;
	private String pk_creqwareid;
	private String vfree2;
	private UFBoolean bzgyfflag;
	private String vuserdef14;
	private UFDouble nfeesettletimes;
	private String vfree7;
	private UFDouble ningrossnum;
	private String pk_defdoc8;
	private String pk_defdoc5;
	private String vfirstbillcode;
	private String vfree6;
	private String vnotebody;
	private UFDouble ncorrespondgrsnum;
	private String ccorrespondhid;
	private String vuserdef15;
	private String csignwasthid;
	private String vfree8;
	private String vuserdef16;
	private UFDate drequiredate;
	private String pk_defdoc13;
	private String vbilltypeu8rm;
	private String vfree9;
	private UFBoolean bonroadflag;
	private String ccorrespondbid;
	private String vsourcewastrowno;
	private UFDouble nquotentmny;
	private String vfree4;
	private String vuserdef17;
	private UFDouble noutassistnum;
	private UFDouble ntarenum;
	private UFDouble nsalemny;
	private UFDouble nkdnum;
	private UFBoolean btoouttoiaflag;
	private String pk_defdoc17;
	private UFDouble npricesettlebill;
	private String vuserdef40;
	private UFDouble noutgrossnum;
	private UFDouble nquoteprice;
	private String vuserdef19;
	private UFBoolean bbarcodeclose;
	private String ccorrespondtype;
	private String vfree3;
	private String vuserdef18;
	private String cgeneralhid;
	private String vfree1;
	private String cfirsttype;
	private String vuserdef42;
	private UFBoolean isok;
	private UFDouble nshouldinnum;
	private String cworksiteid;
	private String pk_returnreason;
	private String pk_defdoc1;
	private String csourcewasthid;
	private String cinventoryid;
	private String vuserdef30;
	private String cgeneralbid;
	private String ccorrespondcode;
	private String vuserdef1;
	private UFDate dzgdate;
	private UFBoolean breturnprofit;
	private String csignwastbid;
	private String vuserdef24;
	private String vuserdef21;
	private UFDouble fchecked;
	private UFDouble nretnum;
	private UFDouble idesatype;
	private String pk_reqstoorg;
	private UFDouble ncorrespondastnum;
	private String vuserdef31;
	private String vuserdef23;
	private String vuserdef20;
	private UFBoolean btou8rm;
	private String cprojectphaseid;
	private UFBoolean bsupplyflag;
	private String csourcewastbid;
	private UFDouble noutnum;
	private UFBoolean bsafeprice;
	private String pk_defdoc15;
	private String vuserdef33;
	private UFDate dbizdate;
	private String castunitid;
	private String cparentid;
	private UFBoolean ftoouttransflag;
	private UFDouble nplannedprice;
	private String vuserdef35;
	private String vfirstrowno;
	private String pk_measware;
	private String vfree5;
	private String pk_defdoc16;
	private String vsignwastrowno;
	private UFDouble nreplenishednum;
	private UFDate ddeliverdate;
	private String vuserdef34;
	private String cfirstbillbid;
	private String vuserdef22;
	private String vbodynote2;
	private String ccheckstateid;
	private String pk_defdoc9;
	private String pk_defdoc14;
	private UFDouble nneedinassistnum;
	private UFDouble naccumwastnum;
	private String pk_defdoc20;
	private String cfirstbillhid;
	private String csourcebillbid;
	private UFDouble hsl;

	public static final String NQUOTENTPRICE = "nquotentprice";
	public static final String PK_CORP = "pk_corp";
	public static final String NREPLENISHEDASTNUM = "nreplenishedastnum";
	public static final String VUSERDEF25 = "vuserdef25";
	public static final String CSELASTUNITID = "cselastunitid";
	public static final String FBILLROWFLAG = "fbillrowflag";
	public static final String CVENDORID = "cvendorid";
	public static final String DREQUIRETIME = "drequiretime";
	public static final String CQUOTECURRENCY = "cquotecurrency";
	public static final String VBATCHCODE = "vbatchcode";
	public static final String VUSERDEF6 = "vuserdef6";
	public static final String VUSERDEF32 = "vuserdef32";
	public static final String DFIRSTBILLDATE = "dfirstbilldate";
	public static final String PK_PACKSORT = "pk_packsort";
	public static final String NTAXPRICE = "ntaxprice";
	public static final String NQUOTEUNITRATE = "nquoteunitrate";
	public static final String PK_CUBASDOC = "pk_cubasdoc";
	public static final String VUSERDEF5 = "vuserdef5";
	public static final String CRECEIVEAREAID = "creceiveareaid";
	public static final String CINVBASID = "cinvbasid";
	public static final String VUSERDEF37 = "vuserdef37";
	public static final String CQUOTEUNITID = "cquoteunitid";
	public static final String BTOINZGFLAG = "btoinzgflag";
	public static final String VUSERDEF9 = "vuserdef9";
	public static final String CSRC2BILLBID = "csrc2billbid";
	public static final String CCOSTOBJECT = "ccostobject";
	public static final String PK_INVOICECORP = "pk_invoicecorp";
	public static final String VUSERDEF36 = "vuserdef36";
	public static final String FASSERTCARDFLAG = "fassertcardflag";
	public static final String CPROJECTID = "cprojectid";
	public static final String NCOUNTNUM = "ncountnum";
	public static final String VUSERDEF13 = "vuserdef13";
	public static final String VUSERDEF29 = "vuserdef29";
	public static final String NTRANOUTASTNUM = "ntranoutastnum";
	public static final String DSTANDBYDATE = "dstandbydate";
	public static final String VPRODUCTBATCH = "vproductbatch";
	public static final String FLARGESS = "flargess";
	public static final String CWORKCENTERID = "cworkcenterid";
	public static final String CORDER_BB1ID = "corder_bb1id";
	public static final String NQUOTEMNY = "nquotemny";
	public static final String VUSERDEF2 = "vuserdef2";
	public static final String NQUOTEUNITNUM = "nquoteunitnum";
	public static final String PK_DEFDOC19 = "pk_defdoc19";
	public static final String PK_DEFDOC10 = "pk_defdoc10";
	public static final String VUSERDEF3 = "vuserdef3";
	public static final String VUSERDEF11 = "vuserdef11";
	public static final String VSRC2BILLCODE = "vsrc2billcode";
	public static final String PK_DEFDOC18 = "pk_defdoc18";
	public static final String CSOURCEBILLHID = "csourcebillhid";
	public static final String VUSERDEF41 = "vuserdef41";
	public static final String VUSERDEF4 = "vuserdef4";
	public static final String CRECEIVEPOINTID = "creceivepointid";
	public static final String CROWNO = "crowno";
	public static final String VTRANSFERCODE = "vtransfercode";
	public static final String VVEHICLECODE = "vvehiclecode";
	public static final String PK_REQCORP = "pk_reqcorp";
	public static final String VUSERDEF12 = "vuserdef12";
	public static final String VUSERDEF8 = "vuserdef8";
	public static final String BTOOUTZGFLAG = "btooutzgflag";
	public static final String CFREEZEID = "cfreezeid";
	public static final String PK_BODYCALBODY = "pk_bodycalbody";
	public static final String PK_DEFDOC7 = "pk_defdoc7";
	public static final String VUSERDEF10 = "vuserdef10";
	public static final String NRETASTNUM = "nretastnum";
	public static final String CBODYWAREHOUSEID = "cbodywarehouseid";
	public static final String VSOURCEBILLCODE = "vsourcebillcode";
	public static final String CSUMID = "csumid";
	public static final String PK_DEFDOC12 = "pk_defdoc12";
	public static final String CSOURCEWASTTYPE = "csourcewasttype";
	public static final String VSOURCEWASTCODE = "vsourcewastcode";
	public static final String VSIGNWASTCODE = "vsignwastcode";
	public static final String PK_DEFDOC6 = "pk_defdoc6";
	public static final String CSRC2BILLHID = "csrc2billhid";
	public static final String NINASSISTNUM = "ninassistnum";
	public static final String VSOURCEROWNO = "vsourcerowno";
	public static final String NSALEPRICE = "nsaleprice";
	public static final String PK_DEFDOC2 = "pk_defdoc2";
	public static final String CSIGNWASTTYPE = "csignwasttype";
	public static final String NCORRESPONDNUM = "ncorrespondnum";
	public static final String VUSERDEF39 = "vuserdef39";
	public static final String PK_DEFDOC3 = "pk_defdoc3";
	public static final String CSRC2BILLTYPE = "csrc2billtype";
	public static final String CBODYBILLTYPECODE = "cbodybilltypecode";
	public static final String VSRC2BILLROWNO = "vsrc2billrowno";
	public static final String VUSERDEF27 = "vuserdef27";
	public static final String NACCUMTONUM = "naccumtonum";
	public static final String NPLANNEDMNY = "nplannedmny";
	public static final String BSOURCELARGESS = "bsourcelargess";
	public static final String VRECEIVEADDRESS = "vreceiveaddress";
	public static final String NRETGROSSNUM = "nretgrossnum";
	public static final String CSOURCETYPE = "csourcetype";
	public static final String NMNY = "nmny";
	public static final String NSHOULDOUTNUM = "nshouldoutnum";
	public static final String VFREE10 = "vfree10";
	public static final String DVALIDATE = "dvalidate";
	public static final String BZGFLAG = "bzgflag";
	public static final String PK_DEFDOC11 = "pk_defdoc11";
	public static final String VUSERDEF28 = "vuserdef28";
	public static final String VCORRESPONDROWNO = "vcorrespondrowno";
	public static final String NTAXMNY = "ntaxmny";
	public static final String NPRICE = "nprice";
	public static final String VUSERDEF7 = "vuserdef7";
	public static final String PK_DEFDOC4 = "pk_defdoc4";
	public static final String NSHOULDOUTASSISTNUM = "nshouldoutassistnum";
	public static final String VUSERDEF38 = "vuserdef38";
	public static final String VUSERDEF26 = "vuserdef26";
	public static final String NINNUM = "ninnum";
	public static final String CRECEIEVEID = "creceieveid";
	public static final String NTRANOUTNUM = "ntranoutnum";
	public static final String CWP = "cwp";
	public static final String NBARCODENUM = "nbarcodenum";
	public static final String PK_CREQWAREID = "pk_creqwareid";
	public static final String VFREE2 = "vfree2";
	public static final String BZGYFFLAG = "bzgyfflag";
	public static final String VUSERDEF14 = "vuserdef14";
	public static final String NFEESETTLETIMES = "nfeesettletimes";
	public static final String VFREE7 = "vfree7";
	public static final String NINGROSSNUM = "ningrossnum";
	public static final String PK_DEFDOC8 = "pk_defdoc8";
	public static final String PK_DEFDOC5 = "pk_defdoc5";
	public static final String VFIRSTBILLCODE = "vfirstbillcode";
	public static final String VFREE6 = "vfree6";
	public static final String VNOTEBODY = "vnotebody";
	public static final String NCORRESPONDGRSNUM = "ncorrespondgrsnum";
	public static final String CCORRESPONDHID = "ccorrespondhid";
	public static final String VUSERDEF15 = "vuserdef15";
	public static final String CSIGNWASTHID = "csignwasthid";
	public static final String VFREE8 = "vfree8";
	public static final String VUSERDEF16 = "vuserdef16";
	public static final String DREQUIREDATE = "drequiredate";
	public static final String PK_DEFDOC13 = "pk_defdoc13";
	public static final String VBILLTYPEU8RM = "vbilltypeu8rm";
	public static final String VFREE9 = "vfree9";
	public static final String BONROADFLAG = "bonroadflag";
	public static final String CCORRESPONDBID = "ccorrespondbid";
	public static final String VSOURCEWASTROWNO = "vsourcewastrowno";
	public static final String NQUOTENTMNY = "nquotentmny";
	public static final String VFREE4 = "vfree4";
	public static final String VUSERDEF17 = "vuserdef17";
	public static final String NOUTASSISTNUM = "noutassistnum";
	public static final String NTARENUM = "ntarenum";
	public static final String NSALEMNY = "nsalemny";
	public static final String NKDNUM = "nkdnum";
	public static final String BTOOUTTOIAFLAG = "btoouttoiaflag";
	public static final String PK_DEFDOC17 = "pk_defdoc17";
	public static final String NPRICESETTLEBILL = "npricesettlebill";
	public static final String VUSERDEF40 = "vuserdef40";
	public static final String NOUTGROSSNUM = "noutgrossnum";
	public static final String NQUOTEPRICE = "nquoteprice";
	public static final String VUSERDEF19 = "vuserdef19";
	public static final String BBARCODECLOSE = "bbarcodeclose";
	public static final String CCORRESPONDTYPE = "ccorrespondtype";
	public static final String VFREE3 = "vfree3";
	public static final String VUSERDEF18 = "vuserdef18";
	public static final String CGENERALHID = "cgeneralhid";
	public static final String VFREE1 = "vfree1";
	public static final String CFIRSTTYPE = "cfirsttype";
	public static final String VUSERDEF42 = "vuserdef42";
	public static final String ISOK = "isok";
	public static final String NSHOULDINNUM = "nshouldinnum";
	public static final String CWORKSITEID = "cworksiteid";
	public static final String PK_RETURNREASON = "pk_returnreason";
	public static final String PK_DEFDOC1 = "pk_defdoc1";
	public static final String CSOURCEWASTHID = "csourcewasthid";
	public static final String CINVENTORYID = "cinventoryid";
	public static final String VUSERDEF30 = "vuserdef30";
	public static final String CGENERALBID = "cgeneralbid";
	public static final String CCORRESPONDCODE = "ccorrespondcode";
	public static final String VUSERDEF1 = "vuserdef1";
	public static final String DZGDATE = "dzgdate";
	public static final String BRETURNPROFIT = "breturnprofit";
	public static final String CSIGNWASTBID = "csignwastbid";
	public static final String VUSERDEF24 = "vuserdef24";
	public static final String VUSERDEF21 = "vuserdef21";
	public static final String FCHECKED = "fchecked";
	public static final String NRETNUM = "nretnum";
	public static final String IDESATYPE = "idesatype";
	public static final String PK_REQSTOORG = "pk_reqstoorg";
	public static final String NCORRESPONDASTNUM = "ncorrespondastnum";
	public static final String VUSERDEF31 = "vuserdef31";
	public static final String VUSERDEF23 = "vuserdef23";
	public static final String VUSERDEF20 = "vuserdef20";
	public static final String BTOU8RM = "btou8rm";
	public static final String CPROJECTPHASEID = "cprojectphaseid";
	public static final String BSUPPLYFLAG = "bsupplyflag";
	public static final String CSOURCEWASTBID = "csourcewastbid";
	public static final String NOUTNUM = "noutnum";
	public static final String BSAFEPRICE = "bsafeprice";
	public static final String PK_DEFDOC15 = "pk_defdoc15";
	public static final String VUSERDEF33 = "vuserdef33";
	public static final String DBIZDATE = "dbizdate";
	public static final String CASTUNITID = "castunitid";
	public static final String CPARENTID = "cparentid";
	public static final String FTOOUTTRANSFLAG = "ftoouttransflag";
	public static final String NPLANNEDPRICE = "nplannedprice";
	public static final String VUSERDEF35 = "vuserdef35";
	public static final String VFIRSTROWNO = "vfirstrowno";
	public static final String PK_MEASWARE = "pk_measware";
	public static final String VFREE5 = "vfree5";
	public static final String PK_DEFDOC16 = "pk_defdoc16";
	public static final String VSIGNWASTROWNO = "vsignwastrowno";
	public static final String NREPLENISHEDNUM = "nreplenishednum";
	public static final String DDELIVERDATE = "ddeliverdate";
	public static final String VUSERDEF34 = "vuserdef34";
	public static final String CFIRSTBILLBID = "cfirstbillbid";
	public static final String VUSERDEF22 = "vuserdef22";
	public static final String VBODYNOTE2 = "vbodynote2";
	public static final String CCHECKSTATEID = "ccheckstateid";
	public static final String PK_DEFDOC9 = "pk_defdoc9";
	public static final String PK_DEFDOC14 = "pk_defdoc14";
	public static final String NNEEDINASSISTNUM = "nneedinassistnum";
	public static final String NACCUMWASTNUM = "naccumwastnum";
	public static final String PK_DEFDOC20 = "pk_defdoc20";
	public static final String CFIRSTBILLHID = "cfirstbillhid";
	public static final String CSOURCEBILLBID = "csourcebillbid";
	public static final String HSL = "hsl";
			
	/**
	 * 属性nquotentprice的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNquotentprice () {
		return nquotentprice;
	}   
	/**
	 * 属性nquotentprice的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNquotentprice UFDouble
	 */
	public void setNquotentprice (UFDouble newNquotentprice ) {
	 	this.nquotentprice = newNquotentprice;
	} 	  
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性nreplenishedastnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNreplenishedastnum () {
		return nreplenishedastnum;
	}   
	/**
	 * 属性nreplenishedastnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNreplenishedastnum UFDouble
	 */
	public void setNreplenishedastnum (UFDouble newNreplenishedastnum ) {
	 	this.nreplenishedastnum = newNreplenishedastnum;
	} 	  
	/**
	 * 属性vuserdef25的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef25 () {
		return vuserdef25;
	}   
	/**
	 * 属性vuserdef25的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef25 String
	 */
	public void setVuserdef25 (String newVuserdef25 ) {
	 	this.vuserdef25 = newVuserdef25;
	} 	  
	/**
	 * 属性cselastunitid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCselastunitid () {
		return cselastunitid;
	}   
	/**
	 * 属性cselastunitid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCselastunitid String
	 */
	public void setCselastunitid (String newCselastunitid ) {
	 	this.cselastunitid = newCselastunitid;
	} 	  
	/**
	 * 属性fbillrowflag的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getFbillrowflag () {
		return fbillrowflag;
	}   
	/**
	 * 属性fbillrowflag的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newFbillrowflag UFDouble
	 */
	public void setFbillrowflag (UFDouble newFbillrowflag ) {
	 	this.fbillrowflag = newFbillrowflag;
	} 	  
	/**
	 * 属性cvendorid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCvendorid () {
		return cvendorid;
	}   
	/**
	 * 属性cvendorid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCvendorid String
	 */
	public void setCvendorid (String newCvendorid ) {
	 	this.cvendorid = newCvendorid;
	} 	  
	/**
	 * 属性drequiretime的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getDrequiretime () {
		return drequiretime;
	}   
	/**
	 * 属性drequiretime的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newDrequiretime String
	 */
	public void setDrequiretime (String newDrequiretime ) {
	 	this.drequiretime = newDrequiretime;
	} 	  
	/**
	 * 属性cquotecurrency的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCquotecurrency () {
		return cquotecurrency;
	}   
	/**
	 * 属性cquotecurrency的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCquotecurrency String
	 */
	public void setCquotecurrency (String newCquotecurrency ) {
	 	this.cquotecurrency = newCquotecurrency;
	} 	  
	/**
	 * 属性vbatchcode的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVbatchcode () {
		return vbatchcode;
	}   
	/**
	 * 属性vbatchcode的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVbatchcode String
	 */
	public void setVbatchcode (String newVbatchcode ) {
	 	this.vbatchcode = newVbatchcode;
	} 	  
	/**
	 * 属性vuserdef6的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef6 () {
		return vuserdef6;
	}   
	/**
	 * 属性vuserdef6的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef6 String
	 */
	public void setVuserdef6 (String newVuserdef6 ) {
	 	this.vuserdef6 = newVuserdef6;
	} 	  
	/**
	 * 属性vuserdef32的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef32 () {
		return vuserdef32;
	}   
	/**
	 * 属性vuserdef32的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef32 String
	 */
	public void setVuserdef32 (String newVuserdef32 ) {
	 	this.vuserdef32 = newVuserdef32;
	} 	  
	/**
	 * 属性dfirstbilldate的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDate
	 */
	public UFDate getDfirstbilldate () {
		return dfirstbilldate;
	}   
	/**
	 * 属性dfirstbilldate的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newDfirstbilldate UFDate
	 */
	public void setDfirstbilldate (UFDate newDfirstbilldate ) {
	 	this.dfirstbilldate = newDfirstbilldate;
	} 	  
	/**
	 * 属性pk_packsort的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_packsort () {
		return pk_packsort;
	}   
	/**
	 * 属性pk_packsort的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_packsort String
	 */
	public void setPk_packsort (String newPk_packsort ) {
	 	this.pk_packsort = newPk_packsort;
	} 	  
	/**
	 * 属性ntaxprice的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNtaxprice () {
		return ntaxprice;
	}   
	/**
	 * 属性ntaxprice的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNtaxprice UFDouble
	 */
	public void setNtaxprice (UFDouble newNtaxprice ) {
	 	this.ntaxprice = newNtaxprice;
	} 	  
	/**
	 * 属性nquoteunitrate的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNquoteunitrate () {
		return nquoteunitrate;
	}   
	/**
	 * 属性nquoteunitrate的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNquoteunitrate UFDouble
	 */
	public void setNquoteunitrate (UFDouble newNquoteunitrate ) {
	 	this.nquoteunitrate = newNquoteunitrate;
	} 	  
	/**
	 * 属性pk_cubasdoc的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_cubasdoc () {
		return pk_cubasdoc;
	}   
	/**
	 * 属性pk_cubasdoc的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_cubasdoc String
	 */
	public void setPk_cubasdoc (String newPk_cubasdoc ) {
	 	this.pk_cubasdoc = newPk_cubasdoc;
	} 	  
	/**
	 * 属性vuserdef5的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef5 () {
		return vuserdef5;
	}   
	/**
	 * 属性vuserdef5的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef5 String
	 */
	public void setVuserdef5 (String newVuserdef5 ) {
	 	this.vuserdef5 = newVuserdef5;
	} 	  
	/**
	 * 属性creceiveareaid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCreceiveareaid () {
		return creceiveareaid;
	}   
	/**
	 * 属性creceiveareaid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCreceiveareaid String
	 */
	public void setCreceiveareaid (String newCreceiveareaid ) {
	 	this.creceiveareaid = newCreceiveareaid;
	} 	  
	/**
	 * 属性cinvbasid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCinvbasid () {
		return cinvbasid;
	}   
	/**
	 * 属性cinvbasid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCinvbasid String
	 */
	public void setCinvbasid (String newCinvbasid ) {
	 	this.cinvbasid = newCinvbasid;
	} 	  
	/**
	 * 属性vuserdef37的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef37 () {
		return vuserdef37;
	}   
	/**
	 * 属性vuserdef37的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef37 String
	 */
	public void setVuserdef37 (String newVuserdef37 ) {
	 	this.vuserdef37 = newVuserdef37;
	} 	  
	/**
	 * 属性cquoteunitid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCquoteunitid () {
		return cquoteunitid;
	}   
	/**
	 * 属性cquoteunitid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCquoteunitid String
	 */
	public void setCquoteunitid (String newCquoteunitid ) {
	 	this.cquoteunitid = newCquoteunitid;
	} 	  
	/**
	 * 属性btoinzgflag的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFBoolean
	 */
	public UFBoolean getBtoinzgflag () {
		return btoinzgflag;
	}   
	/**
	 * 属性btoinzgflag的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newBtoinzgflag UFBoolean
	 */
	public void setBtoinzgflag (UFBoolean newBtoinzgflag ) {
	 	this.btoinzgflag = newBtoinzgflag;
	} 	  
	/**
	 * 属性vuserdef9的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef9 () {
		return vuserdef9;
	}   
	/**
	 * 属性vuserdef9的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef9 String
	 */
	public void setVuserdef9 (String newVuserdef9 ) {
	 	this.vuserdef9 = newVuserdef9;
	} 	  
	/**
	 * 属性csrc2billbid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCsrc2billbid () {
		return csrc2billbid;
	}   
	/**
	 * 属性csrc2billbid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCsrc2billbid String
	 */
	public void setCsrc2billbid (String newCsrc2billbid ) {
	 	this.csrc2billbid = newCsrc2billbid;
	} 	  
	/**
	 * 属性ccostobject的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCcostobject () {
		return ccostobject;
	}   
	/**
	 * 属性ccostobject的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCcostobject String
	 */
	public void setCcostobject (String newCcostobject ) {
	 	this.ccostobject = newCcostobject;
	} 	  
	/**
	 * 属性pk_invoicecorp的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_invoicecorp () {
		return pk_invoicecorp;
	}   
	/**
	 * 属性pk_invoicecorp的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_invoicecorp String
	 */
	public void setPk_invoicecorp (String newPk_invoicecorp ) {
	 	this.pk_invoicecorp = newPk_invoicecorp;
	} 	  
	/**
	 * 属性vuserdef36的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef36 () {
		return vuserdef36;
	}   
	/**
	 * 属性vuserdef36的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef36 String
	 */
	public void setVuserdef36 (String newVuserdef36 ) {
	 	this.vuserdef36 = newVuserdef36;
	} 	  
	/**
	 * 属性fassertcardflag的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFBoolean
	 */
	public UFBoolean getFassertcardflag () {
		return fassertcardflag;
	}   
	/**
	 * 属性fassertcardflag的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newFassertcardflag UFBoolean
	 */
	public void setFassertcardflag (UFBoolean newFassertcardflag ) {
	 	this.fassertcardflag = newFassertcardflag;
	} 	  
	/**
	 * 属性cprojectid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCprojectid () {
		return cprojectid;
	}   
	/**
	 * 属性cprojectid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCprojectid String
	 */
	public void setCprojectid (String newCprojectid ) {
	 	this.cprojectid = newCprojectid;
	} 	  
	/**
	 * 属性ncountnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNcountnum () {
		return ncountnum;
	}   
	/**
	 * 属性ncountnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNcountnum UFDouble
	 */
	public void setNcountnum (UFDouble newNcountnum ) {
	 	this.ncountnum = newNcountnum;
	} 	  
	/**
	 * 属性vuserdef13的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef13 () {
		return vuserdef13;
	}   
	/**
	 * 属性vuserdef13的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef13 String
	 */
	public void setVuserdef13 (String newVuserdef13 ) {
	 	this.vuserdef13 = newVuserdef13;
	} 	  
	/**
	 * 属性vuserdef29的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef29 () {
		return vuserdef29;
	}   
	/**
	 * 属性vuserdef29的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef29 String
	 */
	public void setVuserdef29 (String newVuserdef29 ) {
	 	this.vuserdef29 = newVuserdef29;
	} 	  
	/**
	 * 属性ntranoutastnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNtranoutastnum () {
		return ntranoutastnum;
	}   
	/**
	 * 属性ntranoutastnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNtranoutastnum UFDouble
	 */
	public void setNtranoutastnum (UFDouble newNtranoutastnum ) {
	 	this.ntranoutastnum = newNtranoutastnum;
	} 	  
	/**
	 * 属性dstandbydate的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDate
	 */
	public UFDate getDstandbydate () {
		return dstandbydate;
	}   
	/**
	 * 属性dstandbydate的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newDstandbydate UFDate
	 */
	public void setDstandbydate (UFDate newDstandbydate ) {
	 	this.dstandbydate = newDstandbydate;
	} 	  
	/**
	 * 属性vproductbatch的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVproductbatch () {
		return vproductbatch;
	}   
	/**
	 * 属性vproductbatch的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVproductbatch String
	 */
	public void setVproductbatch (String newVproductbatch ) {
	 	this.vproductbatch = newVproductbatch;
	} 	  
	/**
	 * 属性flargess的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFBoolean
	 */
	public UFBoolean getFlargess () {
		return flargess;
	}   
	/**
	 * 属性flargess的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newFlargess UFBoolean
	 */
	public void setFlargess (UFBoolean newFlargess ) {
	 	this.flargess = newFlargess;
	} 	  
	/**
	 * 属性cworkcenterid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCworkcenterid () {
		return cworkcenterid;
	}   
	/**
	 * 属性cworkcenterid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCworkcenterid String
	 */
	public void setCworkcenterid (String newCworkcenterid ) {
	 	this.cworkcenterid = newCworkcenterid;
	} 	  
	/**
	 * 属性corder_bb1id的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCorder_bb1id () {
		return corder_bb1id;
	}   
	/**
	 * 属性corder_bb1id的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCorder_bb1id String
	 */
	public void setCorder_bb1id (String newCorder_bb1id ) {
	 	this.corder_bb1id = newCorder_bb1id;
	} 	  
	/**
	 * 属性nquotemny的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNquotemny () {
		return nquotemny;
	}   
	/**
	 * 属性nquotemny的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNquotemny UFDouble
	 */
	public void setNquotemny (UFDouble newNquotemny ) {
	 	this.nquotemny = newNquotemny;
	} 	  
	/**
	 * 属性vuserdef2的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef2 () {
		return vuserdef2;
	}   
	/**
	 * 属性vuserdef2的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef2 String
	 */
	public void setVuserdef2 (String newVuserdef2 ) {
	 	this.vuserdef2 = newVuserdef2;
	} 	  
	/**
	 * 属性nquoteunitnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNquoteunitnum () {
		return nquoteunitnum;
	}   
	/**
	 * 属性nquoteunitnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNquoteunitnum UFDouble
	 */
	public void setNquoteunitnum (UFDouble newNquoteunitnum ) {
	 	this.nquoteunitnum = newNquoteunitnum;
	} 	  
	/**
	 * 属性pk_defdoc19的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc19 () {
		return pk_defdoc19;
	}   
	/**
	 * 属性pk_defdoc19的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc19 String
	 */
	public void setPk_defdoc19 (String newPk_defdoc19 ) {
	 	this.pk_defdoc19 = newPk_defdoc19;
	} 	  
	/**
	 * 属性pk_defdoc10的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc10 () {
		return pk_defdoc10;
	}   
	/**
	 * 属性pk_defdoc10的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc10 String
	 */
	public void setPk_defdoc10 (String newPk_defdoc10 ) {
	 	this.pk_defdoc10 = newPk_defdoc10;
	} 	  
	/**
	 * 属性vuserdef3的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef3 () {
		return vuserdef3;
	}   
	/**
	 * 属性vuserdef3的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef3 String
	 */
	public void setVuserdef3 (String newVuserdef3 ) {
	 	this.vuserdef3 = newVuserdef3;
	} 	  
	/**
	 * 属性vuserdef11的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef11 () {
		return vuserdef11;
	}   
	/**
	 * 属性vuserdef11的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef11 String
	 */
	public void setVuserdef11 (String newVuserdef11 ) {
	 	this.vuserdef11 = newVuserdef11;
	} 	  
	/**
	 * 属性vsrc2billcode的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVsrc2billcode () {
		return vsrc2billcode;
	}   
	/**
	 * 属性vsrc2billcode的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVsrc2billcode String
	 */
	public void setVsrc2billcode (String newVsrc2billcode ) {
	 	this.vsrc2billcode = newVsrc2billcode;
	} 	  
	/**
	 * 属性pk_defdoc18的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc18 () {
		return pk_defdoc18;
	}   
	/**
	 * 属性pk_defdoc18的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc18 String
	 */
	public void setPk_defdoc18 (String newPk_defdoc18 ) {
	 	this.pk_defdoc18 = newPk_defdoc18;
	} 	  
	/**
	 * 属性csourcebillhid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCsourcebillhid () {
		return csourcebillhid;
	}   
	/**
	 * 属性csourcebillhid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCsourcebillhid String
	 */
	public void setCsourcebillhid (String newCsourcebillhid ) {
	 	this.csourcebillhid = newCsourcebillhid;
	} 	  
	/**
	 * 属性vuserdef41的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef41 () {
		return vuserdef41;
	}   
	/**
	 * 属性vuserdef41的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef41 String
	 */
	public void setVuserdef41 (String newVuserdef41 ) {
	 	this.vuserdef41 = newVuserdef41;
	} 	  
	/**
	 * 属性vuserdef4的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef4 () {
		return vuserdef4;
	}   
	/**
	 * 属性vuserdef4的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef4 String
	 */
	public void setVuserdef4 (String newVuserdef4 ) {
	 	this.vuserdef4 = newVuserdef4;
	} 	  
	/**
	 * 属性creceivepointid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCreceivepointid () {
		return creceivepointid;
	}   
	/**
	 * 属性creceivepointid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCreceivepointid String
	 */
	public void setCreceivepointid (String newCreceivepointid ) {
	 	this.creceivepointid = newCreceivepointid;
	} 	  
	/**
	 * 属性crowno的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCrowno () {
		return crowno;
	}   
	/**
	 * 属性crowno的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCrowno String
	 */
	public void setCrowno (String newCrowno ) {
	 	this.crowno = newCrowno;
	} 	  
	/**
	 * 属性vtransfercode的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVtransfercode () {
		return vtransfercode;
	}   
	/**
	 * 属性vtransfercode的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVtransfercode String
	 */
	public void setVtransfercode (String newVtransfercode ) {
	 	this.vtransfercode = newVtransfercode;
	} 	  
	/**
	 * 属性vvehiclecode的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVvehiclecode () {
		return vvehiclecode;
	}   
	/**
	 * 属性vvehiclecode的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVvehiclecode String
	 */
	public void setVvehiclecode (String newVvehiclecode ) {
	 	this.vvehiclecode = newVvehiclecode;
	} 	  
	/**
	 * 属性pk_reqcorp的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_reqcorp () {
		return pk_reqcorp;
	}   
	/**
	 * 属性pk_reqcorp的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_reqcorp String
	 */
	public void setPk_reqcorp (String newPk_reqcorp ) {
	 	this.pk_reqcorp = newPk_reqcorp;
	} 	  
	/**
	 * 属性vuserdef12的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef12 () {
		return vuserdef12;
	}   
	/**
	 * 属性vuserdef12的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef12 String
	 */
	public void setVuserdef12 (String newVuserdef12 ) {
	 	this.vuserdef12 = newVuserdef12;
	} 	  
	/**
	 * 属性vuserdef8的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef8 () {
		return vuserdef8;
	}   
	/**
	 * 属性vuserdef8的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef8 String
	 */
	public void setVuserdef8 (String newVuserdef8 ) {
	 	this.vuserdef8 = newVuserdef8;
	} 	  
	/**
	 * 属性btooutzgflag的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFBoolean
	 */
	public UFBoolean getBtooutzgflag () {
		return btooutzgflag;
	}   
	/**
	 * 属性btooutzgflag的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newBtooutzgflag UFBoolean
	 */
	public void setBtooutzgflag (UFBoolean newBtooutzgflag ) {
	 	this.btooutzgflag = newBtooutzgflag;
	} 	  
	/**
	 * 属性cfreezeid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCfreezeid () {
		return cfreezeid;
	}   
	/**
	 * 属性cfreezeid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCfreezeid String
	 */
	public void setCfreezeid (String newCfreezeid ) {
	 	this.cfreezeid = newCfreezeid;
	} 	  
	/**
	 * 属性pk_bodycalbody的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_bodycalbody () {
		return pk_bodycalbody;
	}   
	/**
	 * 属性pk_bodycalbody的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_bodycalbody String
	 */
	public void setPk_bodycalbody (String newPk_bodycalbody ) {
	 	this.pk_bodycalbody = newPk_bodycalbody;
	} 	  
	/**
	 * 属性pk_defdoc7的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc7 () {
		return pk_defdoc7;
	}   
	/**
	 * 属性pk_defdoc7的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc7 String
	 */
	public void setPk_defdoc7 (String newPk_defdoc7 ) {
	 	this.pk_defdoc7 = newPk_defdoc7;
	} 	  
	/**
	 * 属性vuserdef10的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef10 () {
		return vuserdef10;
	}   
	/**
	 * 属性vuserdef10的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef10 String
	 */
	public void setVuserdef10 (String newVuserdef10 ) {
	 	this.vuserdef10 = newVuserdef10;
	} 	  
	/**
	 * 属性nretastnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNretastnum () {
		return nretastnum;
	}   
	/**
	 * 属性nretastnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNretastnum UFDouble
	 */
	public void setNretastnum (UFDouble newNretastnum ) {
	 	this.nretastnum = newNretastnum;
	} 	  
	/**
	 * 属性cbodywarehouseid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCbodywarehouseid () {
		return cbodywarehouseid;
	}   
	/**
	 * 属性cbodywarehouseid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCbodywarehouseid String
	 */
	public void setCbodywarehouseid (String newCbodywarehouseid ) {
	 	this.cbodywarehouseid = newCbodywarehouseid;
	} 	  
	/**
	 * 属性vsourcebillcode的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVsourcebillcode () {
		return vsourcebillcode;
	}   
	/**
	 * 属性vsourcebillcode的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVsourcebillcode String
	 */
	public void setVsourcebillcode (String newVsourcebillcode ) {
	 	this.vsourcebillcode = newVsourcebillcode;
	} 	  
	/**
	 * 属性csumid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCsumid () {
		return csumid;
	}   
	/**
	 * 属性csumid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCsumid String
	 */
	public void setCsumid (String newCsumid ) {
	 	this.csumid = newCsumid;
	} 	  
	/**
	 * 属性pk_defdoc12的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc12 () {
		return pk_defdoc12;
	}   
	/**
	 * 属性pk_defdoc12的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc12 String
	 */
	public void setPk_defdoc12 (String newPk_defdoc12 ) {
	 	this.pk_defdoc12 = newPk_defdoc12;
	} 	  
	/**
	 * 属性csourcewasttype的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCsourcewasttype () {
		return csourcewasttype;
	}   
	/**
	 * 属性csourcewasttype的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCsourcewasttype String
	 */
	public void setCsourcewasttype (String newCsourcewasttype ) {
	 	this.csourcewasttype = newCsourcewasttype;
	} 	  
	/**
	 * 属性vsourcewastcode的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVsourcewastcode () {
		return vsourcewastcode;
	}   
	/**
	 * 属性vsourcewastcode的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVsourcewastcode String
	 */
	public void setVsourcewastcode (String newVsourcewastcode ) {
	 	this.vsourcewastcode = newVsourcewastcode;
	} 	  
	/**
	 * 属性vsignwastcode的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVsignwastcode () {
		return vsignwastcode;
	}   
	/**
	 * 属性vsignwastcode的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVsignwastcode String
	 */
	public void setVsignwastcode (String newVsignwastcode ) {
	 	this.vsignwastcode = newVsignwastcode;
	} 	  
	/**
	 * 属性pk_defdoc6的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc6 () {
		return pk_defdoc6;
	}   
	/**
	 * 属性pk_defdoc6的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc6 String
	 */
	public void setPk_defdoc6 (String newPk_defdoc6 ) {
	 	this.pk_defdoc6 = newPk_defdoc6;
	} 	  
	/**
	 * 属性csrc2billhid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCsrc2billhid () {
		return csrc2billhid;
	}   
	/**
	 * 属性csrc2billhid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCsrc2billhid String
	 */
	public void setCsrc2billhid (String newCsrc2billhid ) {
	 	this.csrc2billhid = newCsrc2billhid;
	} 	  
	/**
	 * 属性ninassistnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNinassistnum () {
		return ninassistnum;
	}   
	/**
	 * 属性ninassistnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNinassistnum UFDouble
	 */
	public void setNinassistnum (UFDouble newNinassistnum ) {
	 	this.ninassistnum = newNinassistnum;
	} 	  
	/**
	 * 属性vsourcerowno的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVsourcerowno () {
		return vsourcerowno;
	}   
	/**
	 * 属性vsourcerowno的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVsourcerowno String
	 */
	public void setVsourcerowno (String newVsourcerowno ) {
	 	this.vsourcerowno = newVsourcerowno;
	} 	  
	/**
	 * 属性nsaleprice的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNsaleprice () {
		return nsaleprice;
	}   
	/**
	 * 属性nsaleprice的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNsaleprice UFDouble
	 */
	public void setNsaleprice (UFDouble newNsaleprice ) {
	 	this.nsaleprice = newNsaleprice;
	} 	  
	/**
	 * 属性pk_defdoc2的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc2 () {
		return pk_defdoc2;
	}   
	/**
	 * 属性pk_defdoc2的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc2 String
	 */
	public void setPk_defdoc2 (String newPk_defdoc2 ) {
	 	this.pk_defdoc2 = newPk_defdoc2;
	} 	  
	/**
	 * 属性csignwasttype的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCsignwasttype () {
		return csignwasttype;
	}   
	/**
	 * 属性csignwasttype的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCsignwasttype String
	 */
	public void setCsignwasttype (String newCsignwasttype ) {
	 	this.csignwasttype = newCsignwasttype;
	} 	  
	/**
	 * 属性ncorrespondnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNcorrespondnum () {
		return ncorrespondnum;
	}   
	/**
	 * 属性ncorrespondnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNcorrespondnum UFDouble
	 */
	public void setNcorrespondnum (UFDouble newNcorrespondnum ) {
	 	this.ncorrespondnum = newNcorrespondnum;
	} 	  
	/**
	 * 属性vuserdef39的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef39 () {
		return vuserdef39;
	}   
	/**
	 * 属性vuserdef39的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef39 String
	 */
	public void setVuserdef39 (String newVuserdef39 ) {
	 	this.vuserdef39 = newVuserdef39;
	} 	  
	/**
	 * 属性pk_defdoc3的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc3 () {
		return pk_defdoc3;
	}   
	/**
	 * 属性pk_defdoc3的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc3 String
	 */
	public void setPk_defdoc3 (String newPk_defdoc3 ) {
	 	this.pk_defdoc3 = newPk_defdoc3;
	} 	  
	/**
	 * 属性csrc2billtype的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCsrc2billtype () {
		return csrc2billtype;
	}   
	/**
	 * 属性csrc2billtype的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCsrc2billtype String
	 */
	public void setCsrc2billtype (String newCsrc2billtype ) {
	 	this.csrc2billtype = newCsrc2billtype;
	} 	  
	/**
	 * 属性cbodybilltypecode的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCbodybilltypecode () {
		return cbodybilltypecode;
	}   
	/**
	 * 属性cbodybilltypecode的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCbodybilltypecode String
	 */
	public void setCbodybilltypecode (String newCbodybilltypecode ) {
	 	this.cbodybilltypecode = newCbodybilltypecode;
	} 	  
	/**
	 * 属性vsrc2billrowno的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVsrc2billrowno () {
		return vsrc2billrowno;
	}   
	/**
	 * 属性vsrc2billrowno的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVsrc2billrowno String
	 */
	public void setVsrc2billrowno (String newVsrc2billrowno ) {
	 	this.vsrc2billrowno = newVsrc2billrowno;
	} 	  
	/**
	 * 属性vuserdef27的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef27 () {
		return vuserdef27;
	}   
	/**
	 * 属性vuserdef27的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef27 String
	 */
	public void setVuserdef27 (String newVuserdef27 ) {
	 	this.vuserdef27 = newVuserdef27;
	} 	  
	/**
	 * 属性naccumtonum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNaccumtonum () {
		return naccumtonum;
	}   
	/**
	 * 属性naccumtonum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNaccumtonum UFDouble
	 */
	public void setNaccumtonum (UFDouble newNaccumtonum ) {
	 	this.naccumtonum = newNaccumtonum;
	} 	  
	/**
	 * 属性nplannedmny的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNplannedmny () {
		return nplannedmny;
	}   
	/**
	 * 属性nplannedmny的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNplannedmny UFDouble
	 */
	public void setNplannedmny (UFDouble newNplannedmny ) {
	 	this.nplannedmny = newNplannedmny;
	} 	  
	/**
	 * 属性bsourcelargess的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFBoolean
	 */
	public UFBoolean getBsourcelargess () {
		return bsourcelargess;
	}   
	/**
	 * 属性bsourcelargess的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newBsourcelargess UFBoolean
	 */
	public void setBsourcelargess (UFBoolean newBsourcelargess ) {
	 	this.bsourcelargess = newBsourcelargess;
	} 	  
	/**
	 * 属性vreceiveaddress的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVreceiveaddress () {
		return vreceiveaddress;
	}   
	/**
	 * 属性vreceiveaddress的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVreceiveaddress String
	 */
	public void setVreceiveaddress (String newVreceiveaddress ) {
	 	this.vreceiveaddress = newVreceiveaddress;
	} 	  
	/**
	 * 属性nretgrossnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNretgrossnum () {
		return nretgrossnum;
	}   
	/**
	 * 属性nretgrossnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNretgrossnum UFDouble
	 */
	public void setNretgrossnum (UFDouble newNretgrossnum ) {
	 	this.nretgrossnum = newNretgrossnum;
	} 	  
	/**
	 * 属性csourcetype的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCsourcetype () {
		return csourcetype;
	}   
	/**
	 * 属性csourcetype的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCsourcetype String
	 */
	public void setCsourcetype (String newCsourcetype ) {
	 	this.csourcetype = newCsourcetype;
	} 	  
	/**
	 * 属性nmny的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNmny () {
		return nmny;
	}   
	/**
	 * 属性nmny的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNmny UFDouble
	 */
	public void setNmny (UFDouble newNmny ) {
	 	this.nmny = newNmny;
	} 	  
	/**
	 * 属性nshouldoutnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNshouldoutnum () {
		return nshouldoutnum;
	}   
	/**
	 * 属性nshouldoutnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNshouldoutnum UFDouble
	 */
	public void setNshouldoutnum (UFDouble newNshouldoutnum ) {
	 	this.nshouldoutnum = newNshouldoutnum;
	} 	  
	/**
	 * 属性vfree10的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVfree10 () {
		return vfree10;
	}   
	/**
	 * 属性vfree10的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVfree10 String
	 */
	public void setVfree10 (String newVfree10 ) {
	 	this.vfree10 = newVfree10;
	} 	  
	/**
	 * 属性dvalidate的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDate
	 */
	public UFDate getDvalidate () {
		return dvalidate;
	}   
	/**
	 * 属性dvalidate的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newDvalidate UFDate
	 */
	public void setDvalidate (UFDate newDvalidate ) {
	 	this.dvalidate = newDvalidate;
	} 	  
	/**
	 * 属性bzgflag的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFBoolean
	 */
	public UFBoolean getBzgflag () {
		return bzgflag;
	}   
	/**
	 * 属性bzgflag的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newBzgflag UFBoolean
	 */
	public void setBzgflag (UFBoolean newBzgflag ) {
	 	this.bzgflag = newBzgflag;
	} 	  
	/**
	 * 属性pk_defdoc11的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc11 () {
		return pk_defdoc11;
	}   
	/**
	 * 属性pk_defdoc11的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc11 String
	 */
	public void setPk_defdoc11 (String newPk_defdoc11 ) {
	 	this.pk_defdoc11 = newPk_defdoc11;
	} 	  
	/**
	 * 属性vuserdef28的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef28 () {
		return vuserdef28;
	}   
	/**
	 * 属性vuserdef28的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef28 String
	 */
	public void setVuserdef28 (String newVuserdef28 ) {
	 	this.vuserdef28 = newVuserdef28;
	} 	  
	/**
	 * 属性vcorrespondrowno的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVcorrespondrowno () {
		return vcorrespondrowno;
	}   
	/**
	 * 属性vcorrespondrowno的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVcorrespondrowno String
	 */
	public void setVcorrespondrowno (String newVcorrespondrowno ) {
	 	this.vcorrespondrowno = newVcorrespondrowno;
	} 	  
	/**
	 * 属性ntaxmny的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNtaxmny () {
		return ntaxmny;
	}   
	/**
	 * 属性ntaxmny的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNtaxmny UFDouble
	 */
	public void setNtaxmny (UFDouble newNtaxmny ) {
	 	this.ntaxmny = newNtaxmny;
	} 	  
	/**
	 * 属性nprice的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNprice () {
		return nprice;
	}   
	/**
	 * 属性nprice的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNprice UFDouble
	 */
	public void setNprice (UFDouble newNprice ) {
	 	this.nprice = newNprice;
	} 	  
	/**
	 * 属性vuserdef7的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef7 () {
		return vuserdef7;
	}   
	/**
	 * 属性vuserdef7的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef7 String
	 */
	public void setVuserdef7 (String newVuserdef7 ) {
	 	this.vuserdef7 = newVuserdef7;
	} 	  
	/**
	 * 属性pk_defdoc4的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc4 () {
		return pk_defdoc4;
	}   
	/**
	 * 属性pk_defdoc4的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc4 String
	 */
	public void setPk_defdoc4 (String newPk_defdoc4 ) {
	 	this.pk_defdoc4 = newPk_defdoc4;
	} 	  
	/**
	 * 属性nshouldoutassistnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNshouldoutassistnum () {
		return nshouldoutassistnum;
	}   
	/**
	 * 属性nshouldoutassistnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNshouldoutassistnum UFDouble
	 */
	public void setNshouldoutassistnum (UFDouble newNshouldoutassistnum ) {
	 	this.nshouldoutassistnum = newNshouldoutassistnum;
	} 	  
	/**
	 * 属性vuserdef38的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef38 () {
		return vuserdef38;
	}   
	/**
	 * 属性vuserdef38的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef38 String
	 */
	public void setVuserdef38 (String newVuserdef38 ) {
	 	this.vuserdef38 = newVuserdef38;
	} 	  
	/**
	 * 属性vuserdef26的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef26 () {
		return vuserdef26;
	}   
	/**
	 * 属性vuserdef26的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef26 String
	 */
	public void setVuserdef26 (String newVuserdef26 ) {
	 	this.vuserdef26 = newVuserdef26;
	} 	  
	/**
	 * 属性ninnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNinnum () {
		return ninnum;
	}   
	/**
	 * 属性ninnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNinnum UFDouble
	 */
	public void setNinnum (UFDouble newNinnum ) {
	 	this.ninnum = newNinnum;
	} 	  
	/**
	 * 属性creceieveid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCreceieveid () {
		return creceieveid;
	}   
	/**
	 * 属性creceieveid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCreceieveid String
	 */
	public void setCreceieveid (String newCreceieveid ) {
	 	this.creceieveid = newCreceieveid;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newDr UFDouble
	 */
	public void setDr (UFDouble newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ntranoutnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNtranoutnum () {
		return ntranoutnum;
	}   
	/**
	 * 属性ntranoutnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNtranoutnum UFDouble
	 */
	public void setNtranoutnum (UFDouble newNtranoutnum ) {
	 	this.ntranoutnum = newNtranoutnum;
	} 	  
	/**
	 * 属性cwp的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCwp () {
		return cwp;
	}   
	/**
	 * 属性cwp的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCwp String
	 */
	public void setCwp (String newCwp ) {
	 	this.cwp = newCwp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性nbarcodenum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNbarcodenum () {
		return nbarcodenum;
	}   
	/**
	 * 属性nbarcodenum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNbarcodenum UFDouble
	 */
	public void setNbarcodenum (UFDouble newNbarcodenum ) {
	 	this.nbarcodenum = newNbarcodenum;
	} 	  
	/**
	 * 属性pk_creqwareid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_creqwareid () {
		return pk_creqwareid;
	}   
	/**
	 * 属性pk_creqwareid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_creqwareid String
	 */
	public void setPk_creqwareid (String newPk_creqwareid ) {
	 	this.pk_creqwareid = newPk_creqwareid;
	} 	  
	/**
	 * 属性vfree2的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVfree2 () {
		return vfree2;
	}   
	/**
	 * 属性vfree2的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVfree2 String
	 */
	public void setVfree2 (String newVfree2 ) {
	 	this.vfree2 = newVfree2;
	} 	  
	/**
	 * 属性bzgyfflag的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFBoolean
	 */
	public UFBoolean getBzgyfflag () {
		return bzgyfflag;
	}   
	/**
	 * 属性bzgyfflag的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newBzgyfflag UFBoolean
	 */
	public void setBzgyfflag (UFBoolean newBzgyfflag ) {
	 	this.bzgyfflag = newBzgyfflag;
	} 	  
	/**
	 * 属性vuserdef14的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef14 () {
		return vuserdef14;
	}   
	/**
	 * 属性vuserdef14的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef14 String
	 */
	public void setVuserdef14 (String newVuserdef14 ) {
	 	this.vuserdef14 = newVuserdef14;
	} 	  
	/**
	 * 属性nfeesettletimes的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNfeesettletimes () {
		return nfeesettletimes;
	}   
	/**
	 * 属性nfeesettletimes的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNfeesettletimes UFDouble
	 */
	public void setNfeesettletimes (UFDouble newNfeesettletimes ) {
	 	this.nfeesettletimes = newNfeesettletimes;
	} 	  
	/**
	 * 属性vfree7的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVfree7 () {
		return vfree7;
	}   
	/**
	 * 属性vfree7的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVfree7 String
	 */
	public void setVfree7 (String newVfree7 ) {
	 	this.vfree7 = newVfree7;
	} 	  
	/**
	 * 属性ningrossnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNingrossnum () {
		return ningrossnum;
	}   
	/**
	 * 属性ningrossnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNingrossnum UFDouble
	 */
	public void setNingrossnum (UFDouble newNingrossnum ) {
	 	this.ningrossnum = newNingrossnum;
	} 	  
	/**
	 * 属性pk_defdoc8的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc8 () {
		return pk_defdoc8;
	}   
	/**
	 * 属性pk_defdoc8的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc8 String
	 */
	public void setPk_defdoc8 (String newPk_defdoc8 ) {
	 	this.pk_defdoc8 = newPk_defdoc8;
	} 	  
	/**
	 * 属性pk_defdoc5的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc5 () {
		return pk_defdoc5;
	}   
	/**
	 * 属性pk_defdoc5的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc5 String
	 */
	public void setPk_defdoc5 (String newPk_defdoc5 ) {
	 	this.pk_defdoc5 = newPk_defdoc5;
	} 	  
	/**
	 * 属性vfirstbillcode的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVfirstbillcode () {
		return vfirstbillcode;
	}   
	/**
	 * 属性vfirstbillcode的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVfirstbillcode String
	 */
	public void setVfirstbillcode (String newVfirstbillcode ) {
	 	this.vfirstbillcode = newVfirstbillcode;
	} 	  
	/**
	 * 属性vfree6的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVfree6 () {
		return vfree6;
	}   
	/**
	 * 属性vfree6的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVfree6 String
	 */
	public void setVfree6 (String newVfree6 ) {
	 	this.vfree6 = newVfree6;
	} 	  
	/**
	 * 属性vnotebody的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVnotebody () {
		return vnotebody;
	}   
	/**
	 * 属性vnotebody的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVnotebody String
	 */
	public void setVnotebody (String newVnotebody ) {
	 	this.vnotebody = newVnotebody;
	} 	  
	/**
	 * 属性ncorrespondgrsnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNcorrespondgrsnum () {
		return ncorrespondgrsnum;
	}   
	/**
	 * 属性ncorrespondgrsnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNcorrespondgrsnum UFDouble
	 */
	public void setNcorrespondgrsnum (UFDouble newNcorrespondgrsnum ) {
	 	this.ncorrespondgrsnum = newNcorrespondgrsnum;
	} 	  
	/**
	 * 属性ccorrespondhid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCcorrespondhid () {
		return ccorrespondhid;
	}   
	/**
	 * 属性ccorrespondhid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCcorrespondhid String
	 */
	public void setCcorrespondhid (String newCcorrespondhid ) {
	 	this.ccorrespondhid = newCcorrespondhid;
	} 	  
	/**
	 * 属性vuserdef15的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef15 () {
		return vuserdef15;
	}   
	/**
	 * 属性vuserdef15的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef15 String
	 */
	public void setVuserdef15 (String newVuserdef15 ) {
	 	this.vuserdef15 = newVuserdef15;
	} 	  
	/**
	 * 属性csignwasthid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCsignwasthid () {
		return csignwasthid;
	}   
	/**
	 * 属性csignwasthid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCsignwasthid String
	 */
	public void setCsignwasthid (String newCsignwasthid ) {
	 	this.csignwasthid = newCsignwasthid;
	} 	  
	/**
	 * 属性vfree8的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVfree8 () {
		return vfree8;
	}   
	/**
	 * 属性vfree8的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVfree8 String
	 */
	public void setVfree8 (String newVfree8 ) {
	 	this.vfree8 = newVfree8;
	} 	  
	/**
	 * 属性vuserdef16的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef16 () {
		return vuserdef16;
	}   
	/**
	 * 属性vuserdef16的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef16 String
	 */
	public void setVuserdef16 (String newVuserdef16 ) {
	 	this.vuserdef16 = newVuserdef16;
	} 	  
	/**
	 * 属性drequiredate的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDate
	 */
	public UFDate getDrequiredate () {
		return drequiredate;
	}   
	/**
	 * 属性drequiredate的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newDrequiredate UFDate
	 */
	public void setDrequiredate (UFDate newDrequiredate ) {
	 	this.drequiredate = newDrequiredate;
	} 	  
	/**
	 * 属性pk_defdoc13的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc13 () {
		return pk_defdoc13;
	}   
	/**
	 * 属性pk_defdoc13的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc13 String
	 */
	public void setPk_defdoc13 (String newPk_defdoc13 ) {
	 	this.pk_defdoc13 = newPk_defdoc13;
	} 	  
	/**
	 * 属性vbilltypeu8rm的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVbilltypeu8rm () {
		return vbilltypeu8rm;
	}   
	/**
	 * 属性vbilltypeu8rm的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVbilltypeu8rm String
	 */
	public void setVbilltypeu8rm (String newVbilltypeu8rm ) {
	 	this.vbilltypeu8rm = newVbilltypeu8rm;
	} 	  
	/**
	 * 属性vfree9的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVfree9 () {
		return vfree9;
	}   
	/**
	 * 属性vfree9的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVfree9 String
	 */
	public void setVfree9 (String newVfree9 ) {
	 	this.vfree9 = newVfree9;
	} 	  
	/**
	 * 属性bonroadflag的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFBoolean
	 */
	public UFBoolean getBonroadflag () {
		return bonroadflag;
	}   
	/**
	 * 属性bonroadflag的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newBonroadflag UFBoolean
	 */
	public void setBonroadflag (UFBoolean newBonroadflag ) {
	 	this.bonroadflag = newBonroadflag;
	} 	  
	/**
	 * 属性ccorrespondbid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCcorrespondbid () {
		return ccorrespondbid;
	}   
	/**
	 * 属性ccorrespondbid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCcorrespondbid String
	 */
	public void setCcorrespondbid (String newCcorrespondbid ) {
	 	this.ccorrespondbid = newCcorrespondbid;
	} 	  
	/**
	 * 属性vsourcewastrowno的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVsourcewastrowno () {
		return vsourcewastrowno;
	}   
	/**
	 * 属性vsourcewastrowno的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVsourcewastrowno String
	 */
	public void setVsourcewastrowno (String newVsourcewastrowno ) {
	 	this.vsourcewastrowno = newVsourcewastrowno;
	} 	  
	/**
	 * 属性nquotentmny的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNquotentmny () {
		return nquotentmny;
	}   
	/**
	 * 属性nquotentmny的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNquotentmny UFDouble
	 */
	public void setNquotentmny (UFDouble newNquotentmny ) {
	 	this.nquotentmny = newNquotentmny;
	} 	  
	/**
	 * 属性vfree4的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVfree4 () {
		return vfree4;
	}   
	/**
	 * 属性vfree4的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVfree4 String
	 */
	public void setVfree4 (String newVfree4 ) {
	 	this.vfree4 = newVfree4;
	} 	  
	/**
	 * 属性vuserdef17的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef17 () {
		return vuserdef17;
	}   
	/**
	 * 属性vuserdef17的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef17 String
	 */
	public void setVuserdef17 (String newVuserdef17 ) {
	 	this.vuserdef17 = newVuserdef17;
	} 	  
	/**
	 * 属性noutassistnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNoutassistnum () {
		return noutassistnum;
	}   
	/**
	 * 属性noutassistnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNoutassistnum UFDouble
	 */
	public void setNoutassistnum (UFDouble newNoutassistnum ) {
	 	this.noutassistnum = newNoutassistnum;
	} 	  
	/**
	 * 属性ntarenum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNtarenum () {
		return ntarenum;
	}   
	/**
	 * 属性ntarenum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNtarenum UFDouble
	 */
	public void setNtarenum (UFDouble newNtarenum ) {
	 	this.ntarenum = newNtarenum;
	} 	  
	/**
	 * 属性nsalemny的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNsalemny () {
		return nsalemny;
	}   
	/**
	 * 属性nsalemny的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNsalemny UFDouble
	 */
	public void setNsalemny (UFDouble newNsalemny ) {
	 	this.nsalemny = newNsalemny;
	} 	  
	/**
	 * 属性nkdnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNkdnum () {
		return nkdnum;
	}   
	/**
	 * 属性nkdnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNkdnum UFDouble
	 */
	public void setNkdnum (UFDouble newNkdnum ) {
	 	this.nkdnum = newNkdnum;
	} 	  
	/**
	 * 属性btoouttoiaflag的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFBoolean
	 */
	public UFBoolean getBtoouttoiaflag () {
		return btoouttoiaflag;
	}   
	/**
	 * 属性btoouttoiaflag的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newBtoouttoiaflag UFBoolean
	 */
	public void setBtoouttoiaflag (UFBoolean newBtoouttoiaflag ) {
	 	this.btoouttoiaflag = newBtoouttoiaflag;
	} 	  
	/**
	 * 属性pk_defdoc17的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc17 () {
		return pk_defdoc17;
	}   
	/**
	 * 属性pk_defdoc17的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc17 String
	 */
	public void setPk_defdoc17 (String newPk_defdoc17 ) {
	 	this.pk_defdoc17 = newPk_defdoc17;
	} 	  
	/**
	 * 属性npricesettlebill的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNpricesettlebill () {
		return npricesettlebill;
	}   
	/**
	 * 属性npricesettlebill的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNpricesettlebill UFDouble
	 */
	public void setNpricesettlebill (UFDouble newNpricesettlebill ) {
	 	this.npricesettlebill = newNpricesettlebill;
	} 	  
	/**
	 * 属性vuserdef40的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef40 () {
		return vuserdef40;
	}   
	/**
	 * 属性vuserdef40的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef40 String
	 */
	public void setVuserdef40 (String newVuserdef40 ) {
	 	this.vuserdef40 = newVuserdef40;
	} 	  
	/**
	 * 属性noutgrossnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNoutgrossnum () {
		return noutgrossnum;
	}   
	/**
	 * 属性noutgrossnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNoutgrossnum UFDouble
	 */
	public void setNoutgrossnum (UFDouble newNoutgrossnum ) {
	 	this.noutgrossnum = newNoutgrossnum;
	} 	  
	/**
	 * 属性nquoteprice的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNquoteprice () {
		return nquoteprice;
	}   
	/**
	 * 属性nquoteprice的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNquoteprice UFDouble
	 */
	public void setNquoteprice (UFDouble newNquoteprice ) {
	 	this.nquoteprice = newNquoteprice;
	} 	  
	/**
	 * 属性vuserdef19的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef19 () {
		return vuserdef19;
	}   
	/**
	 * 属性vuserdef19的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef19 String
	 */
	public void setVuserdef19 (String newVuserdef19 ) {
	 	this.vuserdef19 = newVuserdef19;
	} 	  
	/**
	 * 属性bbarcodeclose的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFBoolean
	 */
	public UFBoolean getBbarcodeclose () {
		return bbarcodeclose;
	}   
	/**
	 * 属性bbarcodeclose的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newBbarcodeclose UFBoolean
	 */
	public void setBbarcodeclose (UFBoolean newBbarcodeclose ) {
	 	this.bbarcodeclose = newBbarcodeclose;
	} 	  
	/**
	 * 属性ccorrespondtype的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCcorrespondtype () {
		return ccorrespondtype;
	}   
	/**
	 * 属性ccorrespondtype的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCcorrespondtype String
	 */
	public void setCcorrespondtype (String newCcorrespondtype ) {
	 	this.ccorrespondtype = newCcorrespondtype;
	} 	  
	/**
	 * 属性vfree3的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVfree3 () {
		return vfree3;
	}   
	/**
	 * 属性vfree3的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVfree3 String
	 */
	public void setVfree3 (String newVfree3 ) {
	 	this.vfree3 = newVfree3;
	} 	  
	/**
	 * 属性vuserdef18的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef18 () {
		return vuserdef18;
	}   
	/**
	 * 属性vuserdef18的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef18 String
	 */
	public void setVuserdef18 (String newVuserdef18 ) {
	 	this.vuserdef18 = newVuserdef18;
	} 	  
	/**
	 * 属性cgeneralhid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCgeneralhid () {
		return cgeneralhid;
	}   
	/**
	 * 属性cgeneralhid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCgeneralhid String
	 */
	public void setCgeneralhid (String newCgeneralhid ) {
	 	this.cgeneralhid = newCgeneralhid;
	} 	  
	/**
	 * 属性vfree1的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVfree1 () {
		return vfree1;
	}   
	/**
	 * 属性vfree1的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVfree1 String
	 */
	public void setVfree1 (String newVfree1 ) {
	 	this.vfree1 = newVfree1;
	} 	  
	/**
	 * 属性cfirsttype的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCfirsttype () {
		return cfirsttype;
	}   
	/**
	 * 属性cfirsttype的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCfirsttype String
	 */
	public void setCfirsttype (String newCfirsttype ) {
	 	this.cfirsttype = newCfirsttype;
	} 	  
	/**
	 * 属性vuserdef42的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef42 () {
		return vuserdef42;
	}   
	/**
	 * 属性vuserdef42的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef42 String
	 */
	public void setVuserdef42 (String newVuserdef42 ) {
	 	this.vuserdef42 = newVuserdef42;
	} 	  
	/**
	 * 属性isok的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFBoolean
	 */
	public UFBoolean getIsok () {
		return isok;
	}   
	/**
	 * 属性isok的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newIsok UFBoolean
	 */
	public void setIsok (UFBoolean newIsok ) {
	 	this.isok = newIsok;
	} 	  
	/**
	 * 属性nshouldinnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNshouldinnum () {
		return nshouldinnum;
	}   
	/**
	 * 属性nshouldinnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNshouldinnum UFDouble
	 */
	public void setNshouldinnum (UFDouble newNshouldinnum ) {
	 	this.nshouldinnum = newNshouldinnum;
	} 	  
	/**
	 * 属性cworksiteid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCworksiteid () {
		return cworksiteid;
	}   
	/**
	 * 属性cworksiteid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCworksiteid String
	 */
	public void setCworksiteid (String newCworksiteid ) {
	 	this.cworksiteid = newCworksiteid;
	} 	  
	/**
	 * 属性pk_returnreason的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_returnreason () {
		return pk_returnreason;
	}   
	/**
	 * 属性pk_returnreason的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_returnreason String
	 */
	public void setPk_returnreason (String newPk_returnreason ) {
	 	this.pk_returnreason = newPk_returnreason;
	} 	  
	/**
	 * 属性pk_defdoc1的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc1 () {
		return pk_defdoc1;
	}   
	/**
	 * 属性pk_defdoc1的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc1 String
	 */
	public void setPk_defdoc1 (String newPk_defdoc1 ) {
	 	this.pk_defdoc1 = newPk_defdoc1;
	} 	  
	/**
	 * 属性csourcewasthid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCsourcewasthid () {
		return csourcewasthid;
	}   
	/**
	 * 属性csourcewasthid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCsourcewasthid String
	 */
	public void setCsourcewasthid (String newCsourcewasthid ) {
	 	this.csourcewasthid = newCsourcewasthid;
	} 	  
	/**
	 * 属性cinventoryid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCinventoryid () {
		return cinventoryid;
	}   
	/**
	 * 属性cinventoryid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCinventoryid String
	 */
	public void setCinventoryid (String newCinventoryid ) {
	 	this.cinventoryid = newCinventoryid;
	} 	  
	/**
	 * 属性vuserdef30的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef30 () {
		return vuserdef30;
	}   
	/**
	 * 属性vuserdef30的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef30 String
	 */
	public void setVuserdef30 (String newVuserdef30 ) {
	 	this.vuserdef30 = newVuserdef30;
	} 	  
	/**
	 * 属性cgeneralbid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCgeneralbid () {
		return cgeneralbid;
	}   
	/**
	 * 属性cgeneralbid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCgeneralbid String
	 */
	public void setCgeneralbid (String newCgeneralbid ) {
	 	this.cgeneralbid = newCgeneralbid;
	} 	  
	/**
	 * 属性ccorrespondcode的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCcorrespondcode () {
		return ccorrespondcode;
	}   
	/**
	 * 属性ccorrespondcode的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCcorrespondcode String
	 */
	public void setCcorrespondcode (String newCcorrespondcode ) {
	 	this.ccorrespondcode = newCcorrespondcode;
	} 	  
	/**
	 * 属性vuserdef1的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef1 () {
		return vuserdef1;
	}   
	/**
	 * 属性vuserdef1的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef1 String
	 */
	public void setVuserdef1 (String newVuserdef1 ) {
	 	this.vuserdef1 = newVuserdef1;
	} 	  
	/**
	 * 属性dzgdate的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDate
	 */
	public UFDate getDzgdate () {
		return dzgdate;
	}   
	/**
	 * 属性dzgdate的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newDzgdate UFDate
	 */
	public void setDzgdate (UFDate newDzgdate ) {
	 	this.dzgdate = newDzgdate;
	} 	  
	/**
	 * 属性breturnprofit的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFBoolean
	 */
	public UFBoolean getBreturnprofit () {
		return breturnprofit;
	}   
	/**
	 * 属性breturnprofit的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newBreturnprofit UFBoolean
	 */
	public void setBreturnprofit (UFBoolean newBreturnprofit ) {
	 	this.breturnprofit = newBreturnprofit;
	} 	  
	/**
	 * 属性csignwastbid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCsignwastbid () {
		return csignwastbid;
	}   
	/**
	 * 属性csignwastbid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCsignwastbid String
	 */
	public void setCsignwastbid (String newCsignwastbid ) {
	 	this.csignwastbid = newCsignwastbid;
	} 	  
	/**
	 * 属性vuserdef24的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef24 () {
		return vuserdef24;
	}   
	/**
	 * 属性vuserdef24的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef24 String
	 */
	public void setVuserdef24 (String newVuserdef24 ) {
	 	this.vuserdef24 = newVuserdef24;
	} 	  
	/**
	 * 属性vuserdef21的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef21 () {
		return vuserdef21;
	}   
	/**
	 * 属性vuserdef21的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef21 String
	 */
	public void setVuserdef21 (String newVuserdef21 ) {
	 	this.vuserdef21 = newVuserdef21;
	} 	  
	/**
	 * 属性fchecked的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getFchecked () {
		return fchecked;
	}   
	/**
	 * 属性fchecked的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newFchecked UFDouble
	 */
	public void setFchecked (UFDouble newFchecked ) {
	 	this.fchecked = newFchecked;
	} 	  
	/**
	 * 属性nretnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNretnum () {
		return nretnum;
	}   
	/**
	 * 属性nretnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNretnum UFDouble
	 */
	public void setNretnum (UFDouble newNretnum ) {
	 	this.nretnum = newNretnum;
	} 	  
	/**
	 * 属性idesatype的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getIdesatype () {
		return idesatype;
	}   
	/**
	 * 属性idesatype的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newIdesatype UFDouble
	 */
	public void setIdesatype (UFDouble newIdesatype ) {
	 	this.idesatype = newIdesatype;
	} 	  
	/**
	 * 属性pk_reqstoorg的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_reqstoorg () {
		return pk_reqstoorg;
	}   
	/**
	 * 属性pk_reqstoorg的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_reqstoorg String
	 */
	public void setPk_reqstoorg (String newPk_reqstoorg ) {
	 	this.pk_reqstoorg = newPk_reqstoorg;
	} 	  
	/**
	 * 属性ncorrespondastnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNcorrespondastnum () {
		return ncorrespondastnum;
	}   
	/**
	 * 属性ncorrespondastnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNcorrespondastnum UFDouble
	 */
	public void setNcorrespondastnum (UFDouble newNcorrespondastnum ) {
	 	this.ncorrespondastnum = newNcorrespondastnum;
	} 	  
	/**
	 * 属性vuserdef31的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef31 () {
		return vuserdef31;
	}   
	/**
	 * 属性vuserdef31的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef31 String
	 */
	public void setVuserdef31 (String newVuserdef31 ) {
	 	this.vuserdef31 = newVuserdef31;
	} 	  
	/**
	 * 属性vuserdef23的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef23 () {
		return vuserdef23;
	}   
	/**
	 * 属性vuserdef23的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef23 String
	 */
	public void setVuserdef23 (String newVuserdef23 ) {
	 	this.vuserdef23 = newVuserdef23;
	} 	  
	/**
	 * 属性vuserdef20的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef20 () {
		return vuserdef20;
	}   
	/**
	 * 属性vuserdef20的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef20 String
	 */
	public void setVuserdef20 (String newVuserdef20 ) {
	 	this.vuserdef20 = newVuserdef20;
	} 	  
	/**
	 * 属性btou8rm的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFBoolean
	 */
	public UFBoolean getBtou8rm () {
		return btou8rm;
	}   
	/**
	 * 属性btou8rm的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newBtou8rm UFBoolean
	 */
	public void setBtou8rm (UFBoolean newBtou8rm ) {
	 	this.btou8rm = newBtou8rm;
	} 	  
	/**
	 * 属性cprojectphaseid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCprojectphaseid () {
		return cprojectphaseid;
	}   
	/**
	 * 属性cprojectphaseid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCprojectphaseid String
	 */
	public void setCprojectphaseid (String newCprojectphaseid ) {
	 	this.cprojectphaseid = newCprojectphaseid;
	} 	  
	/**
	 * 属性bsupplyflag的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFBoolean
	 */
	public UFBoolean getBsupplyflag () {
		return bsupplyflag;
	}   
	/**
	 * 属性bsupplyflag的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newBsupplyflag UFBoolean
	 */
	public void setBsupplyflag (UFBoolean newBsupplyflag ) {
	 	this.bsupplyflag = newBsupplyflag;
	} 	  
	/**
	 * 属性csourcewastbid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCsourcewastbid () {
		return csourcewastbid;
	}   
	/**
	 * 属性csourcewastbid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCsourcewastbid String
	 */
	public void setCsourcewastbid (String newCsourcewastbid ) {
	 	this.csourcewastbid = newCsourcewastbid;
	} 	  
	/**
	 * 属性noutnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNoutnum () {
		return noutnum;
	}   
	/**
	 * 属性noutnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNoutnum UFDouble
	 */
	public void setNoutnum (UFDouble newNoutnum ) {
	 	this.noutnum = newNoutnum;
	} 	  
	/**
	 * 属性bsafeprice的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFBoolean
	 */
	public UFBoolean getBsafeprice () {
		return bsafeprice;
	}   
	/**
	 * 属性bsafeprice的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newBsafeprice UFBoolean
	 */
	public void setBsafeprice (UFBoolean newBsafeprice ) {
	 	this.bsafeprice = newBsafeprice;
	} 	  
	/**
	 * 属性pk_defdoc15的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc15 () {
		return pk_defdoc15;
	}   
	/**
	 * 属性pk_defdoc15的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc15 String
	 */
	public void setPk_defdoc15 (String newPk_defdoc15 ) {
	 	this.pk_defdoc15 = newPk_defdoc15;
	} 	  
	/**
	 * 属性vuserdef33的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef33 () {
		return vuserdef33;
	}   
	/**
	 * 属性vuserdef33的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef33 String
	 */
	public void setVuserdef33 (String newVuserdef33 ) {
	 	this.vuserdef33 = newVuserdef33;
	} 	  
	/**
	 * 属性dbizdate的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDate
	 */
	public UFDate getDbizdate () {
		return dbizdate;
	}   
	/**
	 * 属性dbizdate的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newDbizdate UFDate
	 */
	public void setDbizdate (UFDate newDbizdate ) {
	 	this.dbizdate = newDbizdate;
	} 	  
	/**
	 * 属性castunitid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCastunitid () {
		return castunitid;
	}   
	/**
	 * 属性castunitid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCastunitid String
	 */
	public void setCastunitid (String newCastunitid ) {
	 	this.castunitid = newCastunitid;
	} 	  
	/**
	 * 属性cparentid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCparentid () {
		return cparentid;
	}   
	/**
	 * 属性cparentid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCparentid String
	 */
	public void setCparentid (String newCparentid ) {
	 	this.cparentid = newCparentid;
	} 	  
	/**
	 * 属性ftoouttransflag的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFBoolean
	 */
	public UFBoolean getFtoouttransflag () {
		return ftoouttransflag;
	}   
	/**
	 * 属性ftoouttransflag的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newFtoouttransflag UFBoolean
	 */
	public void setFtoouttransflag (UFBoolean newFtoouttransflag ) {
	 	this.ftoouttransflag = newFtoouttransflag;
	} 	  
	/**
	 * 属性nplannedprice的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNplannedprice () {
		return nplannedprice;
	}   
	/**
	 * 属性nplannedprice的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNplannedprice UFDouble
	 */
	public void setNplannedprice (UFDouble newNplannedprice ) {
	 	this.nplannedprice = newNplannedprice;
	} 	  
	/**
	 * 属性vuserdef35的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef35 () {
		return vuserdef35;
	}   
	/**
	 * 属性vuserdef35的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef35 String
	 */
	public void setVuserdef35 (String newVuserdef35 ) {
	 	this.vuserdef35 = newVuserdef35;
	} 	  
	/**
	 * 属性vfirstrowno的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVfirstrowno () {
		return vfirstrowno;
	}   
	/**
	 * 属性vfirstrowno的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVfirstrowno String
	 */
	public void setVfirstrowno (String newVfirstrowno ) {
	 	this.vfirstrowno = newVfirstrowno;
	} 	  
	/**
	 * 属性pk_measware的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_measware () {
		return pk_measware;
	}   
	/**
	 * 属性pk_measware的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_measware String
	 */
	public void setPk_measware (String newPk_measware ) {
	 	this.pk_measware = newPk_measware;
	} 	  
	/**
	 * 属性vfree5的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVfree5 () {
		return vfree5;
	}   
	/**
	 * 属性vfree5的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVfree5 String
	 */
	public void setVfree5 (String newVfree5 ) {
	 	this.vfree5 = newVfree5;
	} 	  
	/**
	 * 属性pk_defdoc16的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc16 () {
		return pk_defdoc16;
	}   
	/**
	 * 属性pk_defdoc16的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc16 String
	 */
	public void setPk_defdoc16 (String newPk_defdoc16 ) {
	 	this.pk_defdoc16 = newPk_defdoc16;
	} 	  
	/**
	 * 属性vsignwastrowno的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVsignwastrowno () {
		return vsignwastrowno;
	}   
	/**
	 * 属性vsignwastrowno的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVsignwastrowno String
	 */
	public void setVsignwastrowno (String newVsignwastrowno ) {
	 	this.vsignwastrowno = newVsignwastrowno;
	} 	  
	/**
	 * 属性nreplenishednum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNreplenishednum () {
		return nreplenishednum;
	}   
	/**
	 * 属性nreplenishednum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNreplenishednum UFDouble
	 */
	public void setNreplenishednum (UFDouble newNreplenishednum ) {
	 	this.nreplenishednum = newNreplenishednum;
	} 	  
	/**
	 * 属性ddeliverdate的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDate
	 */
	public UFDate getDdeliverdate () {
		return ddeliverdate;
	}   
	/**
	 * 属性ddeliverdate的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newDdeliverdate UFDate
	 */
	public void setDdeliverdate (UFDate newDdeliverdate ) {
	 	this.ddeliverdate = newDdeliverdate;
	} 	  
	/**
	 * 属性vuserdef34的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef34 () {
		return vuserdef34;
	}   
	/**
	 * 属性vuserdef34的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef34 String
	 */
	public void setVuserdef34 (String newVuserdef34 ) {
	 	this.vuserdef34 = newVuserdef34;
	} 	  
	/**
	 * 属性cfirstbillbid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCfirstbillbid () {
		return cfirstbillbid;
	}   
	/**
	 * 属性cfirstbillbid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCfirstbillbid String
	 */
	public void setCfirstbillbid (String newCfirstbillbid ) {
	 	this.cfirstbillbid = newCfirstbillbid;
	} 	  
	/**
	 * 属性vuserdef22的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVuserdef22 () {
		return vuserdef22;
	}   
	/**
	 * 属性vuserdef22的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVuserdef22 String
	 */
	public void setVuserdef22 (String newVuserdef22 ) {
	 	this.vuserdef22 = newVuserdef22;
	} 	  
	/**
	 * 属性vbodynote2的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getVbodynote2 () {
		return vbodynote2;
	}   
	/**
	 * 属性vbodynote2的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newVbodynote2 String
	 */
	public void setVbodynote2 (String newVbodynote2 ) {
	 	this.vbodynote2 = newVbodynote2;
	} 	  
	/**
	 * 属性ccheckstateid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCcheckstateid () {
		return ccheckstateid;
	}   
	/**
	 * 属性ccheckstateid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCcheckstateid String
	 */
	public void setCcheckstateid (String newCcheckstateid ) {
	 	this.ccheckstateid = newCcheckstateid;
	} 	  
	/**
	 * 属性pk_defdoc9的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc9 () {
		return pk_defdoc9;
	}   
	/**
	 * 属性pk_defdoc9的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc9 String
	 */
	public void setPk_defdoc9 (String newPk_defdoc9 ) {
	 	this.pk_defdoc9 = newPk_defdoc9;
	} 	  
	/**
	 * 属性pk_defdoc14的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc14 () {
		return pk_defdoc14;
	}   
	/**
	 * 属性pk_defdoc14的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc14 String
	 */
	public void setPk_defdoc14 (String newPk_defdoc14 ) {
	 	this.pk_defdoc14 = newPk_defdoc14;
	} 	  
	/**
	 * 属性nneedinassistnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNneedinassistnum () {
		return nneedinassistnum;
	}   
	/**
	 * 属性nneedinassistnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNneedinassistnum UFDouble
	 */
	public void setNneedinassistnum (UFDouble newNneedinassistnum ) {
	 	this.nneedinassistnum = newNneedinassistnum;
	} 	  
	/**
	 * 属性naccumwastnum的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getNaccumwastnum () {
		return naccumwastnum;
	}   
	/**
	 * 属性naccumwastnum的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newNaccumwastnum UFDouble
	 */
	public void setNaccumwastnum (UFDouble newNaccumwastnum ) {
	 	this.naccumwastnum = newNaccumwastnum;
	} 	  
	/**
	 * 属性pk_defdoc20的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getPk_defdoc20 () {
		return pk_defdoc20;
	}   
	/**
	 * 属性pk_defdoc20的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newPk_defdoc20 String
	 */
	public void setPk_defdoc20 (String newPk_defdoc20 ) {
	 	this.pk_defdoc20 = newPk_defdoc20;
	} 	  
	/**
	 * 属性cfirstbillhid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCfirstbillhid () {
		return cfirstbillhid;
	}   
	/**
	 * 属性cfirstbillhid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCfirstbillhid String
	 */
	public void setCfirstbillhid (String newCfirstbillhid ) {
	 	this.cfirstbillhid = newCfirstbillhid;
	} 	  
	/**
	 * 属性csourcebillbid的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return String
	 */
	public String getCsourcebillbid () {
		return csourcebillbid;
	}   
	/**
	 * 属性csourcebillbid的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newCsourcebillbid String
	 */
	public void setCsourcebillbid (String newCsourcebillbid ) {
	 	this.csourcebillbid = newCsourcebillbid;
	} 	  
	/**
	 * 属性hsl的Getter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @return UFDouble
	 */
	public UFDouble getHsl () {
		return hsl;
	}   
	/**
	 * 属性hsl的Setter方法.
	 * 创建日期:2014-10-25 16:35:54
	 * @param newHsl UFDouble
	 */
	public void setHsl (UFDouble newHsl ) {
	 	this.hsl = newHsl;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2014-10-25 16:35:54
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "CGENERALHID";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2014-10-25 16:35:54
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "cgeneralbid";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2014-10-25 16:35:54
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "IC_GENERAL_B";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2014-10-25 16:35:54
	  */
     public GeneralBVO() {
		super();	
	}    
} 
