/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.jyglgt.j400680;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2011-06-14 09:08:51
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class CreditVO extends SuperVO {
	private String pk_corp;
	private UFDateTime ts;
	private UFDouble deposit;
	private String vapprovednote;
	private String vapprovenote;
	private UFDouble vdef9;
	private String pk_receiveway2;
	private UFDouble vdef10;
	private String vunapproveid;
	private UFDate receivemnydate;
	private String vdef15;
	private String vdef14;
	private UFDouble vdef7;
	private String pk_credit;
	private String vdef16;
	private UFDouble vdef2;
	private UFDouble vdef5;
	private String vdef19;
	private String memo;
	private UFDate vapprovedate;
	private UFDate dapprovedate;
	private String pk_cumandoc;
	private String vdef18;
	private UFDouble vdef4;
	private UFDouble bcskmny;
	private UFDate vunapprovedate;
	private String billtype;
	private String vdef17;
	private String vbillcode;
	private String vdef20;
	private UFDouble vdef1;
	private UFDouble vdef8;
	private UFDouble skmny;
	private String pk_busitype;
	private String vunapprovednote;
	private String vapproveid;
	private String pk_balatype;
	private String pk_psndoc;
	private String pk_deptdoc;
	private UFDouble qcmny;
	private Integer receivetype;
	private String pk_receiveway;
	private String vdef13;
	private UFBoolean whethersk;
	private String currency;
	private String pk_accsubj;
	private UFDouble wmbcreditmny;
	private String vdef11;
	private Integer vbillstatus;
	private UFDate dmakedate;
	private UFDouble vdef3;
	private String vdef12;
	private UFDouble vdef6;
	private UFDouble tkmny;
	private Integer dr;
	private String pk_operator;
	private UFDouble fhmny;
	private UFDouble jsmny;
	private String pk_cubasdoc;
	private String djvbillcode;
	private String csaleid;
	private String vcsaleid;
	private UFDouble cdprice;
	private UFDouble montax;
	private String priceway;
	private String pk_productline;
	private String vpk_productline;
	private String pk_custproduct;
	private String custproductname;
	private UFDate voicesdate;
	private UFDate voiceedate;
	private UFDouble txdays;//贴现天数
	private UFDouble hddays;//活动天数
	private String pk_vbillcode_tk;//退款单号
	private UFBoolean isreceipt;//是否可收款
	private String pk_stordoc;
	private String receiveunit;
	private String receivebankacc;
	private String receivebank;
	private String payunit;
	private String paybankacc;
	private String paybank;

	public static final String TXDAYS = "txdays";
	public static final String VOICESDATE = "voicesdate";
	public static final String VOICEEDATE = "voiceedate";
	public static final String PK_CUSTPRODUCT = "pk_custproduct";
	public static final String CUSTPRODUCTNAME = "custproductname";
	public static final String VCSALEID = "vcsaleid";
	public static final String CSALEID = "csaleid";
	public static final String CDPRICE = "cdprice";
	public static final String MONTAX = "montax";
	public static final String PRICEWAY = "priceway";
	public static final String VPK_PRODUCTLINE = "vpk_productline";
	public static final String PK_PRODUCTLINE = "pk_productline";
	public static final String PK_CORP = "pk_corp";
	public static final String DEPOSIT = "deposit";
	public static final String VAPPROVEDNOTE = "vapprovednote";
	public static final String VDEF9 = "vdef9";
	public static final String PK_RECEIVEWAY2 = "pk_receiveway2";
	public static final String VDEF10 = "vdef10";
	public static final String VUNAPPROVEID = "vunapproveid";
	public static final String RECEIVEMNYDATE = "receivemnydate";
	public static final String VDEF15 = "vdef15";
	public static final String VDEF14 = "vdef14";
	public static final String VDEF7 = "vdef7";
	public static final String PK_CREDIT = "pk_credit";
	public static final String VDEF16 = "vdef16";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF5 = "vdef5";
	public static final String VDEF19 = "vdef19";
	public static final String MEMO = "memo";
	public static final String VAPPROVEDATE = "vapprovedate";
	public static final String PK_CUMANDOC = "pk_cumandoc";
	public static final String VDEF18 = "vdef18";
	public static final String VDEF4 = "vdef4";
	public static final String BCSKMNY = "bcskmny";
	public static final String VUNAPPROVEDATE = "vunapprovedate";
	public static final String BILLTYPE = "billtype";
	public static final String VDEF17 = "vdef17";
	public static final String VBILLCODE = "vbillcode";
	public static final String VDEF20 = "vdef20";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF8 = "vdef8";
	public static final String SKMNY = "skmny";
	public static final String PK_BUSITYPE = "pk_busitype";
	public static final String VUNAPPROVEDNOTE = "vunapprovednote";
	public static final String VAPPROVEID = "vapproveid";
	public static final String PK_BALATYPE = "pk_balatype";
	public static final String PK_PSNDOC = "pk_psndoc";
	public static final String PK_DEPTDOC = "pk_deptdoc";
	public static final String QCMNY = "qcmny";
	public static final String RECEIVETYPE = "receivetype";
	public static final String PK_RECEIVEWAY = "pk_receiveway";
	public static final String VDEF13 = "vdef13";
	public static final String WHETHERSK = "whethersk";
	public static final String CURRENCY = "currency";
	public static final String PK_ACCSUBJ = "pk_accsubj";
	public static final String WMBCREDITMNY = "wmbcreditmny";
	public static final String VDEF11 = "vdef11";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String DMAKEDATE = "dmakedate";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF12 = "vdef12";
	public static final String VDEF6 = "vdef6";
	public static final String TKMNY = "tkmny";
	public static final String PK_OPERATOR = "pk_operator";
	public static final String FHMNY = "fhmny";
	public static final String JSMNY = "jsmny";
	public static final String HDDAYS = "hddays";
	public static final String PK_VBILLCODE_TK="pk_vbillcode_tk";
	public static final String ISRECEIPT = "isreceipt";
	public static final String PK_STORDOC="pk_stordoc";
		
	
	
	public String getVapprovenote() {
		return vapprovenote;
	}
	public void setVapprovenote(String vapprovenote) {
		this.vapprovenote = vapprovenote;
	}
	public String getReceiveunit() {
		return receiveunit;
	}
	public void setReceiveunit(String receiveunit) {
		this.receiveunit = receiveunit;
	}
	public String getReceivebankacc() {
		return receivebankacc;
	}
	public void setReceivebankacc(String receivebankacc) {
		this.receivebankacc = receivebankacc;
	}
	public String getReceivebank() {
		return receivebank;
	}
	public void setReceivebank(String receivebank) {
		this.receivebank = receivebank;
	}

	
	
	public String getPayunit() {
		return payunit;
	}
	public void setPayunit(String payunit) {
		this.payunit = payunit;
	}
	public String getPaybankacc() {
		return paybankacc;
	}
	public void setPaybankacc(String paybankacc) {
		this.paybankacc = paybankacc;
	}
	public String getPaybank() {
		return paybank;
	}
	public void setPaybank(String paybank) {
		this.paybank = paybank;
	}
	public String getPk_stordoc() {
		return pk_stordoc;
	}
	public void setPk_stordoc(String pk_stordoc) {
		this.pk_stordoc = pk_stordoc;
	}
	public UFDouble getHddays() {
		return hddays;
	}
	public void setHddays(UFDouble hddays) {
		this.hddays = hddays;
	}
	public UFDate getVoicesdate() {
		return voicesdate;
	}
	public void setVoicesdate(UFDate voicesdate) {
		this.voicesdate = voicesdate;
	}
	public UFDate getVoiceedate() {
		return voiceedate;
	}
	public void setVoiceedate(UFDate voiceedate) {
		this.voiceedate = voiceedate;
	}
	public UFDouble getTxdays() {
		return txdays;
	}
	public void setTxdays(UFDouble txdays) {
		this.txdays = txdays;
	}
	public String getPk_custproduct() {
		return pk_custproduct;
	}
	public void setPk_custproduct(String pk_custproduct) {
		this.pk_custproduct = pk_custproduct;
	}
	public String getCustproductname() {
		return custproductname;
	}
	public void setCustproductname(String custproductname) {
		this.custproductname = custproductname;
	}
	public String getVcsaleid() {
		return vcsaleid;
	}
	public void setVcsaleid(String vcsaleid) {
		this.vcsaleid = vcsaleid;
	}
	public String getVpk_productline() {
		return vpk_productline;
	}
	public void setVpk_productline(String vpk_productline) {
		this.vpk_productline = vpk_productline;
	}
	public String getCsaleid() {
		return csaleid;
	}
	public void setCsaleid(String csaleid) {
		this.csaleid = csaleid;
	}
	public UFDouble getCdprice() {
		return cdprice;
	}
	public void setCdprice(UFDouble cdprice) {
		this.cdprice = cdprice;
	}
	public UFDouble getMontax() {
		return montax;
	}
	public void setMontax(UFDouble montax) {
		this.montax = montax;
	}
	public String getPriceway() {
		return priceway;
	}
	public void setPriceway(String priceway) {
		this.priceway = priceway;
	}
	public String getPk_productline() {
		return pk_productline;
	}
	public void setPk_productline(String pk_productline) {
		this.pk_productline = pk_productline;
	}
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	public String getDjvbillcode() {
		return djvbillcode;
	}
	public void setDjvbillcode(String djvbillcode) {
		this.djvbillcode = djvbillcode;
	}
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性deposit的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public UFDouble getDeposit () {
		return deposit;
	}   
	/**
	 * 属性deposit的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newDeposit UFDouble
	 */
	public void setDeposit (UFDouble newDeposit ) {
	 	this.deposit = newDeposit;
	} 	  
	/**
	 * 属性vapprovednote的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getVapprovednote () {
		return vapprovednote;
	}   
	/**
	 * 属性vapprovednote的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVapprovednote String
	 */
	public void setVapprovednote (String newVapprovednote ) {
	 	this.vapprovednote = newVapprovednote;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public UFDouble getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef9 UFDouble
	 */
	public void setVdef9 (UFDouble newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性pk_receiveway2的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getPk_receiveway2 () {
		return pk_receiveway2;
	}   
	/**
	 * 属性pk_receiveway2的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newPk_receiveway2 String
	 */
	public void setPk_receiveway2 (String newPk_receiveway2 ) {
	 	this.pk_receiveway2 = newPk_receiveway2;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public UFDouble getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef10 UFDouble
	 */
	public void setVdef10 (UFDouble newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
	/**
	 * 属性vunapproveid的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getVunapproveid () {
		return vunapproveid;
	}   
	/**
	 * 属性vunapproveid的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVunapproveid String
	 */
	public void setVunapproveid (String newVunapproveid ) {
	 	this.vunapproveid = newVunapproveid;
	} 	  
	/**
	 * 属性receivemnydate的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDate
	 */
	public UFDate getReceivemnydate () {
		return receivemnydate;
	}   
	/**
	 * 属性receivemnydate的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newReceivemnydate UFDate
	 */
	public void setReceivemnydate (UFDate newReceivemnydate ) {
	 	this.receivemnydate = newReceivemnydate;
	} 	  
	/**
	 * 属性vdef15的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getVdef15 () {
		return vdef15;
	}   
	/**
	 * 属性vdef15的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef15 String
	 */
	public void setVdef15 (String newVdef15 ) {
	 	this.vdef15 = newVdef15;
	} 	  
	/**
	 * 属性vdef14的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getVdef14 () {
		return vdef14;
	}   
	/**
	 * 属性vdef14的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef14 String
	 */
	public void setVdef14 (String newVdef14 ) {
	 	this.vdef14 = newVdef14;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public UFDouble getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef7 UFDouble
	 */
	public void setVdef7 (UFDouble newVdef7 ) {
	 	this.vdef7 = newVdef7;
	} 	  
	/**
	 * 属性pk_credit的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getPk_credit () {
		return pk_credit;
	}   
	/**
	 * 属性pk_credit的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newPk_credit String
	 */
	public void setPk_credit (String newPk_credit ) {
	 	this.pk_credit = newPk_credit;
	} 	  
	/**
	 * 属性vdef16的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getVdef16 () {
		return vdef16;
	}   
	/**
	 * 属性vdef16的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef16 String
	 */
	public void setVdef16 (String newVdef16 ) {
	 	this.vdef16 = newVdef16;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public UFDouble getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef2 UFDouble
	 */
	public void setVdef2 (UFDouble newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public UFDouble getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef5 UFDouble
	 */
	public void setVdef5 (UFDouble newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性vdef19的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getVdef19 () {
		return vdef19;
	}   
	/**
	 * 属性vdef19的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef19 String
	 */
	public void setVdef19 (String newVdef19 ) {
	 	this.vdef19 = newVdef19;
	} 	  
	/**
	 * 属性memo的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getMemo () {
		return memo;
	}   
	/**
	 * 属性memo的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newMemo String
	 */
	public void setMemo (String newMemo ) {
	 	this.memo = newMemo;
	} 	  
	/**
	 * 属性vapprovedate的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDate
	 */
	public UFDate getVapprovedate () {
		return vapprovedate;
	}   
	/**
	 * 属性vapprovedate的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVapprovedate UFDate
	 */
	public void setVapprovedate (UFDate newVapprovedate ) {
	 	this.vapprovedate = newVapprovedate;
	} 	  
	/**
	 * 属性pk_cumandoc的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getPk_cumandoc () {
		return pk_cumandoc;
	}   
	/**
	 * 属性pk_cumandoc的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newPk_cumandoc String
	 */
	public void setPk_cumandoc (String newPk_cumandoc ) {
	 	this.pk_cumandoc = newPk_cumandoc;
	} 	  
	/**
	 * 属性vdef18的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getVdef18 () {
		return vdef18;
	}   
	/**
	 * 属性vdef18的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef18 String
	 */
	public void setVdef18 (String newVdef18 ) {
	 	this.vdef18 = newVdef18;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public UFDouble getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef4 UFDouble
	 */
	public void setVdef4 (UFDouble newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性bcskmny的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public UFDouble getBcskmny () {
		return bcskmny;
	}   
	/**
	 * 属性bcskmny的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newBcskmny UFDouble
	 */
	public void setBcskmny (UFDouble newBcskmny ) {
	 	this.bcskmny = newBcskmny;
	} 	  
	/**
	 * 属性vunapprovedate的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDate
	 */
	public UFDate getVunapprovedate () {
		return vunapprovedate;
	}   
	/**
	 * 属性vunapprovedate的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVunapprovedate UFDate
	 */
	public void setVunapprovedate (UFDate newVunapprovedate ) {
	 	this.vunapprovedate = newVunapprovedate;
	} 	  
	/**
	 * 属性billtype的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getBilltype () {
		return billtype;
	}   
	/**
	 * 属性billtype的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newBilltype String
	 */
	public void setBilltype (String newBilltype ) {
	 	this.billtype = newBilltype;
	} 	  
	/**
	 * 属性vdef17的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getVdef17 () {
		return vdef17;
	}   
	/**
	 * 属性vdef17的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef17 String
	 */
	public void setVdef17 (String newVdef17 ) {
	 	this.vdef17 = newVdef17;
	} 	  
	/**
	 * 属性vbillcode的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getVbillcode () {
		return vbillcode;
	}   
	/**
	 * 属性vbillcode的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVbillcode String
	 */
	public void setVbillcode (String newVbillcode ) {
	 	this.vbillcode = newVbillcode;
	} 	  
	/**
	 * 属性vdef20的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getVdef20 () {
		return vdef20;
	}   
	/**
	 * 属性vdef20的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef20 String
	 */
	public void setVdef20 (String newVdef20 ) {
	 	this.vdef20 = newVdef20;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public UFDouble getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef1 UFDouble
	 */
	public void setVdef1 (UFDouble newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public UFDouble getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef8 UFDouble
	 */
	public void setVdef8 (UFDouble newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性skmny的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public UFDouble getSkmny () {
		return skmny;
	}   
	/**
	 * 属性skmny的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newSkmny UFDouble
	 */
	public void setSkmny (UFDouble newSkmny ) {
	 	this.skmny = newSkmny;
	} 	  
	/**
	 * 属性pk_busitype的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getPk_busitype () {
		return pk_busitype;
	}   
	/**
	 * 属性pk_busitype的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newPk_busitype String
	 */
	public void setPk_busitype (String newPk_busitype ) {
	 	this.pk_busitype = newPk_busitype;
	} 	  
	/**
	 * 属性vunapprovednote的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getVunapprovednote () {
		return vunapprovednote;
	}   
	/**
	 * 属性vunapprovednote的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVunapprovednote String
	 */
	public void setVunapprovednote (String newVunapprovednote ) {
	 	this.vunapprovednote = newVunapprovednote;
	} 	  
	/**
	 * 属性vapproveid的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getVapproveid () {
		return vapproveid;
	}   
	/**
	 * 属性vapproveid的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVapproveid String
	 */
	public void setVapproveid (String newVapproveid ) {
	 	this.vapproveid = newVapproveid;
	} 	  
	/**
	 * 属性pk_balatype的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getPk_balatype () {
		return pk_balatype;
	}   
	/**
	 * 属性pk_balatype的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newPk_balatype String
	 */
	public void setPk_balatype (String newPk_balatype ) {
	 	this.pk_balatype = newPk_balatype;
	} 	  
	/**
	 * 属性pk_psndoc的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getPk_psndoc () {
		return pk_psndoc;
	}   
	/**
	 * 属性pk_psndoc的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newPk_psndoc String
	 */
	public void setPk_psndoc (String newPk_psndoc ) {
	 	this.pk_psndoc = newPk_psndoc;
	} 	  
	/**
	 * 属性pk_deptdoc的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getPk_deptdoc () {
		return pk_deptdoc;
	}   
	/**
	 * 属性pk_deptdoc的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newPk_deptdoc String
	 */
	public void setPk_deptdoc (String newPk_deptdoc ) {
	 	this.pk_deptdoc = newPk_deptdoc;
	} 	  
	/**
	 * 属性qcmny的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public UFDouble getQcmny () {
		return qcmny;
	}   
	/**
	 * 属性qcmny的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newQcmny UFDouble
	 */
	public void setQcmny (UFDouble newQcmny ) {
	 	this.qcmny = newQcmny;
	} 	  
	/**
	 * 属性receivetype的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public Integer getReceivetype () {
		return receivetype;
	}   
	/**
	 * 属性receivetype的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newReceivetype UFDouble
	 */
	public void setReceivetype (Integer newReceivetype ) {
	 	this.receivetype = newReceivetype;
	} 	  
	/**
	 * 属性pk_receiveway的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getPk_receiveway () {
		return pk_receiveway;
	}   
	/**
	 * 属性pk_receiveway的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newPk_receiveway String
	 */
	public void setPk_receiveway (String newPk_receiveway ) {
	 	this.pk_receiveway = newPk_receiveway;
	} 	  
	/**
	 * 属性vdef13的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getVdef13 () {
		return vdef13;
	}   
	/**
	 * 属性vdef13的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef13 String
	 */
	public void setVdef13 (String newVdef13 ) {
	 	this.vdef13 = newVdef13;
	} 	  
	/**
	 * 属性whethersk的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFBoolean
	 */
	public UFBoolean getWhethersk () {
		return whethersk;
	}   
	/**
	 * 属性whethersk的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newWhethersk UFBoolean
	 */
	public void setWhethersk (UFBoolean newWhethersk ) {
	 	this.whethersk = newWhethersk;
	} 	  
	/**
	 * 属性currency的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getCurrency () {
		return currency;
	}   
	/**
	 * 属性currency的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newCurrency String
	 */
	public void setCurrency (String newCurrency ) {
	 	this.currency = newCurrency;
	} 	  
	/**
	 * 属性pk_accsubj的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getPk_accsubj () {
		return pk_accsubj;
	}   
	/**
	 * 属性pk_accsubj的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newPk_accsubj String
	 */
	public void setPk_accsubj (String newPk_accsubj ) {
	 	this.pk_accsubj = newPk_accsubj;
	} 	  
	/**
	 * 属性wmbcreditmny的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public UFDouble getWmbcreditmny () {
		return wmbcreditmny;
	}   
	/**
	 * 属性wmbcreditmny的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newWmbcreditmny UFDouble
	 */
	public void setWmbcreditmny (UFDouble newWmbcreditmny ) {
	 	this.wmbcreditmny = newWmbcreditmny;
	} 	  
	/**
	 * 属性vdef11的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getVdef11 () {
		return vdef11;
	}   
	/**
	 * 属性vdef11的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef11 String
	 */
	public void setVdef11 (String newVdef11 ) {
	 	this.vdef11 = newVdef11;
	} 	  
	/**
	 * 属性vbillstatus的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public Integer getVbillstatus () {
		return vbillstatus;
	}   
	/**
	 * 属性vbillstatus的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVbillstatus UFDouble
	 */
	public void setVbillstatus (Integer newVbillstatus ) {
	 	this.vbillstatus = newVbillstatus;
	} 	  
	/**
	 * 属性dmakedate的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDate
	 */
	public UFDate getDmakedate () {
		return dmakedate;
	}   
	/**
	 * 属性dmakedate的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newDmakedate UFDate
	 */
	public void setDmakedate (UFDate newDmakedate ) {
	 	this.dmakedate = newDmakedate;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public UFDouble getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef3 UFDouble
	 */
	public void setVdef3 (UFDouble newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef12的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getVdef12 () {
		return vdef12;
	}   
	/**
	 * 属性vdef12的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef12 String
	 */
	public void setVdef12 (String newVdef12 ) {
	 	this.vdef12 = newVdef12;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public UFDouble getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newVdef6 UFDouble
	 */
	public void setVdef6 (UFDouble newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性tkmny的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public UFDouble getTkmny () {
		return tkmny;
	}   
	/**
	 * 属性tkmny的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newTkmny UFDouble
	 */
	public void setTkmny (UFDouble newTkmny ) {
	 	this.tkmny = newTkmny;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性pk_operator的Getter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @return String
	 */
	public String getPk_operator () {
		return pk_operator;
	}   
	/**
	 * 属性pk_operator的Setter方法.
	 * 创建日期:2011-06-14 09:08:51
	 * @param newPk_operator String
	 */
	public void setPk_operator (String newPk_operator ) {
	 	this.pk_operator = newPk_operator;
	} 	  
 
	
	
	public String getPk_vbillcode_tk() {
		return pk_vbillcode_tk;
	}
	public void setPk_vbillcode_tk(String pk_vbillcode_tk) {
		this.pk_vbillcode_tk = pk_vbillcode_tk;
	}
	
	/**
	 * 是否可收款
	 * @return
	 */
	public UFBoolean getIsreceipt() {
		return isreceipt;
	}
	public void setIsreceipt(UFBoolean isreceipt) {
		this.isreceipt = isreceipt;
	}
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-06-14 09:08:51
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-06-14 09:08:51
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_credit";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2011-06-14 09:08:51
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "gt_credit";
	}    
    
    public UFDate getDapprovedate() {
		return dapprovedate;
	}
	public void setDapprovedate(UFDate dapprovedate) {
		this.dapprovedate = dapprovedate;
	}
	/**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-06-14 09:08:51
	  */
     public CreditVO() {
		super();	
	}
	public void setFhmny(UFDouble fhmny) {
		this.fhmny = fhmny;
	}
	public UFDouble getFhmny() {
		return fhmny;
	}
	public void setJsmny(UFDouble jsmny) {
		this.jsmny = jsmny;
	}
	public UFDouble getJsmny() {
		return jsmny;
	}
	public void setPk_cubasdoc(String pk_cubasdoc) {
		this.pk_cubasdoc = pk_cubasdoc;
	}
	public String getPk_cubasdoc() {
		return pk_cubasdoc;
	}    
} 
