/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.jyglgt.arap;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2010-11-06 10:36:10
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class DJZBItemVO extends SuperVO {
	private UFBoolean old_flag;
	private String zyx26;
	private String fkyhdz;
	private String zyx21;
	private String zyx3;
	private String innerorderno;
	private UFDouble bbhl;
	private Integer checkflag;
	private UFDate ycskrq;
	private String zyx27;
	private String zyx20;
	private Integer wldx;
	private String ctzhtlx_pk;
	private String skyhdz;
	private String zyx22;
	private String zyx4;
	private String ywxz;
	private String zyx25;
	private UFDouble jshj;
	private String zyx23;
	private String vouchid;
	private String ckdid;
	private String kxyt;
	private UFBoolean isverifyfinished;
	private String zyx24;
	private String zyx5;
	private String zyx29;
	private UFDouble bbtxfy;
	private String djbh;
	private UFDouble dfshl;
	private String deptid;
	private UFDouble shlye;
	private String tax_num;
	private UFDouble jfybje;
	private UFDouble bbye;
	private UFDouble jfbbsj;
	private UFDouble wbfbbje;
	private UFDouble zkl;
	private UFDouble dfybsj;
	private String pch;
	private UFDouble jfzkfbje;
	private String chbm_cl;
	private UFDouble dfbbsj;
	private UFDouble jfybsj;
	private String htbh;
	private String tbbh;
	private String ddhh;
	private String ksbm_cl;
	private UFDouble sl;
	private String dwbm;
	private UFDate bz_date;
	private UFDouble dfbbje;
	private String pj_jsfs;
	private String xmbm4;
	private String bfyhzh;
	private String ywbm;
	private String pjdirection;
	private String jobid;
	private String bankrollprojet;
	private String dfyhzh;
	private String assetpactno;
	private String item_bill_pk;
	private Integer flbh;
	private String clbh;
	private UFDouble fbhl;
	private String zyx2;
	private UFDouble ysfbye;
	private String ordercusmandoc;
	private UFDouble txlx_ybje;
	private String zrdeptid;
	private Integer xgbh;
	private UFDouble jfjs;
	private String fph;
	private String payman;
	private String chmc;
	private String facardbh;
	private String zjldw;
	private String pk_jobobjpha;
	private String sanhu;
	private UFDouble dfybwsje;
	private String sfbz;
	private UFDouble payflag;
	private UFDouble wbffbje;
	private UFDouble jffbje;
	private String commonflag;
	private String zyx8;
	private String produceorder;
	private UFDouble pzflh;
	private UFDouble dffbje;
	private String zyx28;
	private String zyx9;
	private String skyhmc;
	private String ph;
	private String seqnum;
	private UFDouble dffbsj;
	private String bzbm;
	private String bjjldw;
	private UFBoolean pausetransact;
	private UFDouble spzt;
	private String zyx7;
	private UFDouble dfybje;
	private UFDouble jfbbje;
	private String zyx6;
	private String hbbm;
	private Integer dr;
	private String bz_kjnd;
	private UFDateTime ts;
	private UFDouble ybpjlx;
	private UFDate qxrq;
	private UFDate verifyfinisheddate;
	private String zyx30;
	private String zyx12;
	private String ggxh;
	private String usedept;
	private UFDouble occupationmny;
	private String dstlsubcs;
	private String accountid;
	private String itemstyle;
	private UFDouble ybtxfy;
	private String xm;
	private String htmc;
	private UFDouble jfzkybje;
	private UFBoolean issfkxychanged;
	private String fjldw;
	private String encode;
	private UFDouble fbye;
	private String ywybm;
	private String zyx11;
	private String zyx16;
	private String freeitemid;
	private UFDouble dfjs;
	private String xyzh;
	private String xmys;
	private UFDouble jfybwsje;
	private String fkyhmc;
	private UFBoolean srbz;
	private UFDouble bjdwsl;
	private String task;
	private String fphid;
	private String cksqsh;
	private String jobphaseid;
	private String djlxbm;
	private String othersysflag;
	private UFDouble bjdwhsdj;
	private UFDouble ybye;
	private String fb_oid;
	private String zyx10;
	private String cashitem;
	private UFDate kprq;
	private String szxmid;
	private UFDouble txlx_fbje;
	private String equipmentcode;
	private String notetype;
	private String ddlx;
	private String ddh;
	private String zyx19;
	private String zy;
	private String ddhid;
	private String sfkxyh;
	private String cinventoryid;
	private String contractno;
	private UFDouble ysbbye;
	private UFDate paydate;
	private String groupnum;
	private UFDouble jffbsj;
	private UFDouble wbfybje;
	private String ckdh;
	private UFDouble dj;
	private String bz_kjqj;
	private UFDate billdate;
	private UFDouble txlx_bbje;
	private String zyx17;
	private UFDouble bbpjlx;
	private String productline;
	private String zyx18;
	private UFDouble dfbbwsje;
	private UFDouble ysybye;
	private Integer fx;
	private String zyx15;
	private UFDouble hsdj;
	private String zyx14;
	private UFDouble fbtxfy;
	private UFDouble jfshl;
	private String xbbm3;
	private Integer djxtflag;
	private UFBoolean old_sys_flag;
	private String zyx13;
	private String pjh;
	private String xmbm2;
	private String jsfsbm;
	private String kmbm;
	private String zyx1;
	private Integer kslb;
	private UFDouble fbpjlx;
	private UFDouble bjdwwsdj;
	private String djdl;
	private UFDouble hsl;
	private String ckbm;

	public static final String OLD_FLAG = "old_flag";
	public static final String ZYX26 = "zyx26";
	public static final String FKYHDZ = "fkyhdz";
	public static final String ZYX21 = "zyx21";
	public static final String ZYX3 = "zyx3";
	public static final String INNERORDERNO = "innerorderno";
	public static final String BBHL = "bbhl";
	public static final String CHECKFLAG = "checkflag";
	public static final String YCSKRQ = "ycskrq";
	public static final String ZYX27 = "zyx27";
	public static final String ZYX20 = "zyx20";
	public static final String WLDX = "wldx";
	public static final String CTZHTLX_PK = "ctzhtlx_pk";
	public static final String SKYHDZ = "skyhdz";
	public static final String ZYX22 = "zyx22";
	public static final String ZYX4 = "zyx4";
	public static final String YWXZ = "ywxz";
	public static final String ZYX25 = "zyx25";
	public static final String JSHJ = "jshj";
	public static final String ZYX23 = "zyx23";
	public static final String VOUCHID = "vouchid";
	public static final String CKDID = "ckdid";
	public static final String KXYT = "kxyt";
	public static final String ISVERIFYFINISHED = "isverifyfinished";
	public static final String ZYX24 = "zyx24";
	public static final String ZYX5 = "zyx5";
	public static final String ZYX29 = "zyx29";
	public static final String BBTXFY = "bbtxfy";
	public static final String DJBH = "djbh";
	public static final String DFSHL = "dfshl";
	public static final String DEPTID = "deptid";
	public static final String SHLYE = "shlye";
	public static final String TAX_NUM = "tax_num";
	public static final String JFYBJE = "jfybje";
	public static final String BBYE = "bbye";
	public static final String JFBBSJ = "jfbbsj";
	public static final String WBFBBJE = "wbfbbje";
	public static final String ZKL = "zkl";
	public static final String DFYBSJ = "dfybsj";
	public static final String PCH = "pch";
	public static final String JFZKFBJE = "jfzkfbje";
	public static final String CHBM_CL = "chbm_cl";
	public static final String DFBBSJ = "dfbbsj";
	public static final String JFYBSJ = "jfybsj";
	public static final String HTBH = "htbh";
	public static final String TBBH = "tbbh";
	public static final String DDHH = "ddhh";
	public static final String KSBM_CL = "ksbm_cl";
	public static final String SL = "sl";
	public static final String DWBM = "dwbm";
	public static final String BZ_DATE = "bz_date";
	public static final String DFBBJE = "dfbbje";
	public static final String PJ_JSFS = "pj_jsfs";
	public static final String XMBM4 = "xmbm4";
	public static final String BFYHZH = "bfyhzh";
	public static final String YWBM = "ywbm";
	public static final String PJDIRECTION = "pjdirection";
	public static final String JOBID = "jobid";
	public static final String BANKROLLPROJET = "bankrollprojet";
	public static final String DFYHZH = "dfyhzh";
	public static final String ASSETPACTNO = "assetpactno";
	public static final String ITEM_BILL_PK = "item_bill_pk";
	public static final String FLBH = "flbh";
	public static final String CLBH = "clbh";
	public static final String FBHL = "fbhl";
	public static final String ZYX2 = "zyx2";
	public static final String YSFBYE = "ysfbye";
	public static final String ORDERCUSMANDOC = "ordercusmandoc";
	public static final String TXLX_YBJE = "txlx_ybje";
	public static final String ZRDEPTID = "zrdeptid";
	public static final String XGBH = "xgbh";
	public static final String JFJS = "jfjs";
	public static final String FPH = "fph";
	public static final String PAYMAN = "payman";
	public static final String CHMC = "chmc";
	public static final String FACARDBH = "facardbh";
	public static final String ZJLDW = "zjldw";
	public static final String PK_JOBOBJPHA = "pk_jobobjpha";
	public static final String SANHU = "sanhu";
	public static final String DFYBWSJE = "dfybwsje";
	public static final String SFBZ = "sfbz";
	public static final String PAYFLAG = "payflag";
	public static final String WBFFBJE = "wbffbje";
	public static final String JFFBJE = "jffbje";
	public static final String COMMONFLAG = "commonflag";
	public static final String ZYX8 = "zyx8";
	public static final String PRODUCEORDER = "produceorder";
	public static final String PZFLH = "pzflh";
	public static final String DFFBJE = "dffbje";
	public static final String ZYX28 = "zyx28";
	public static final String ZYX9 = "zyx9";
	public static final String SKYHMC = "skyhmc";
	public static final String PH = "ph";
	public static final String SEQNUM = "seqnum";
	public static final String DFFBSJ = "dffbsj";
	public static final String BZBM = "bzbm";
	public static final String BJJLDW = "bjjldw";
	public static final String PAUSETRANSACT = "pausetransact";
	public static final String SPZT = "spzt";
	public static final String ZYX7 = "zyx7";
	public static final String DFYBJE = "dfybje";
	public static final String JFBBJE = "jfbbje";
	public static final String ZYX6 = "zyx6";
	public static final String HBBM = "hbbm";
	public static final String BZ_KJND = "bz_kjnd";
	public static final String YBPJLX = "ybpjlx";
	public static final String QXRQ = "qxrq";
	public static final String VERIFYFINISHEDDATE = "verifyfinisheddate";
	public static final String ZYX30 = "zyx30";
	public static final String ZYX12 = "zyx12";
	public static final String GGXH = "ggxh";
	public static final String USEDEPT = "usedept";
	public static final String OCCUPATIONMNY = "occupationmny";
	public static final String DSTLSUBCS = "dstlsubcs";
	public static final String ACCOUNTID = "accountid";
	public static final String ITEMSTYLE = "itemstyle";
	public static final String YBTXFY = "ybtxfy";
	public static final String XM = "xm";
	public static final String HTMC = "htmc";
	public static final String JFZKYBJE = "jfzkybje";
	public static final String ISSFKXYCHANGED = "issfkxychanged";
	public static final String FJLDW = "fjldw";
	public static final String ENCODE = "encode";
	public static final String FBYE = "fbye";
	public static final String YWYBM = "ywybm";
	public static final String ZYX11 = "zyx11";
	public static final String ZYX16 = "zyx16";
	public static final String FREEITEMID = "freeitemid";
	public static final String DFJS = "dfjs";
	public static final String XYZH = "xyzh";
	public static final String XMYS = "xmys";
	public static final String JFYBWSJE = "jfybwsje";
	public static final String FKYHMC = "fkyhmc";
	public static final String SRBZ = "srbz";
	public static final String BJDWSL = "bjdwsl";
	public static final String TASK = "task";
	public static final String FPHID = "fphid";
	public static final String CKSQSH = "cksqsh";
	public static final String JOBPHASEID = "jobphaseid";
	public static final String DJLXBM = "djlxbm";
	public static final String OTHERSYSFLAG = "othersysflag";
	public static final String BJDWHSDJ = "bjdwhsdj";
	public static final String YBYE = "ybye";
	public static final String FB_OID = "fb_oid";
	public static final String ZYX10 = "zyx10";
	public static final String CASHITEM = "cashitem";
	public static final String KPRQ = "kprq";
	public static final String SZXMID = "szxmid";
	public static final String TXLX_FBJE = "txlx_fbje";
	public static final String EQUIPMENTCODE = "equipmentcode";
	public static final String NOTETYPE = "notetype";
	public static final String DDLX = "ddlx";
	public static final String DDH = "ddh";
	public static final String ZYX19 = "zyx19";
	public static final String ZY = "zy";
	public static final String DDHID = "ddhid";
	public static final String SFKXYH = "sfkxyh";
	public static final String CINVENTORYID = "cinventoryid";
	public static final String CONTRACTNO = "contractno";
	public static final String YSBBYE = "ysbbye";
	public static final String PAYDATE = "paydate";
	public static final String GROUPNUM = "groupnum";
	public static final String JFFBSJ = "jffbsj";
	public static final String WBFYBJE = "wbfybje";
	public static final String CKDH = "ckdh";
	public static final String DJ = "dj";
	public static final String BZ_KJQJ = "bz_kjqj";
	public static final String BILLDATE = "billdate";
	public static final String TXLX_BBJE = "txlx_bbje";
	public static final String ZYX17 = "zyx17";
	public static final String BBPJLX = "bbpjlx";
	public static final String PRODUCTLINE = "productline";
	public static final String ZYX18 = "zyx18";
	public static final String DFBBWSJE = "dfbbwsje";
	public static final String YSYBYE = "ysybye";
	public static final String FX = "fx";
	public static final String ZYX15 = "zyx15";
	public static final String HSDJ = "hsdj";
	public static final String ZYX14 = "zyx14";
	public static final String FBTXFY = "fbtxfy";
	public static final String JFSHL = "jfshl";
	public static final String XBBM3 = "xbbm3";
	public static final String DJXTFLAG = "djxtflag";
	public static final String OLD_SYS_FLAG = "old_sys_flag";
	public static final String ZYX13 = "zyx13";
	public static final String PJH = "pjh";
	public static final String XMBM2 = "xmbm2";
	public static final String JSFSBM = "jsfsbm";
	public static final String KMBM = "kmbm";
	public static final String ZYX1 = "zyx1";
	public static final String KSLB = "kslb";
	public static final String FBPJLX = "fbpjlx";
	public static final String BJDWWSDJ = "bjdwwsdj";
	public static final String DJDL = "djdl";
	public static final String HSL = "hsl";
	public static final String CKBM = "ckbm";
			
	/**
	 * 属性old_flag的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFBoolean
	 */
	public UFBoolean getOld_flag () {
		return old_flag;
	}   
	/**
	 * 属性old_flag的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newOld_flag UFBoolean
	 */
	public void setOld_flag (UFBoolean newOld_flag ) {
	 	this.old_flag = newOld_flag;
	} 	  
	/**
	 * 属性zyx26的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx26 () {
		return zyx26;
	}   
	/**
	 * 属性zyx26的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx26 String
	 */
	public void setZyx26 (String newZyx26 ) {
	 	this.zyx26 = newZyx26;
	} 	  
	/**
	 * 属性fkyhdz的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getFkyhdz () {
		return fkyhdz;
	}   
	/**
	 * 属性fkyhdz的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFkyhdz String
	 */
	public void setFkyhdz (String newFkyhdz ) {
	 	this.fkyhdz = newFkyhdz;
	} 	  
	/**
	 * 属性zyx21的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx21 () {
		return zyx21;
	}   
	/**
	 * 属性zyx21的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx21 String
	 */
	public void setZyx21 (String newZyx21 ) {
	 	this.zyx21 = newZyx21;
	} 	  
	/**
	 * 属性zyx3的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx3 () {
		return zyx3;
	}   
	/**
	 * 属性zyx3的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx3 String
	 */
	public void setZyx3 (String newZyx3 ) {
	 	this.zyx3 = newZyx3;
	} 	  
	/**
	 * 属性innerorderno的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getInnerorderno () {
		return innerorderno;
	}   
	/**
	 * 属性innerorderno的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newInnerorderno String
	 */
	public void setInnerorderno (String newInnerorderno ) {
	 	this.innerorderno = newInnerorderno;
	} 	  
	/**
	 * 属性bbhl的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getBbhl () {
		return bbhl;
	}   
	/**
	 * 属性bbhl的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newBbhl UFDouble
	 */
	public void setBbhl (UFDouble newBbhl ) {
	 	this.bbhl = newBbhl;
	} 	  
	/**
	 * 属性checkflag的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public Integer getCheckflag () {
		return checkflag;
	}   
	/**
	 * 属性checkflag的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newCheckflag UFDouble
	 */
	public void setCheckflag (Integer newCheckflag ) {
	 	this.checkflag = newCheckflag;
	} 	  
	/**
	 * 属性ycskrq的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getYcskrq () {
		return ycskrq;
	}   
	/**
	 * 属性ycskrq的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newYcskrq UFDate
	 */
	public void setYcskrq (UFDate newYcskrq ) {
	 	this.ycskrq = newYcskrq;
	} 	  
	/**
	 * 属性zyx27的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx27 () {
		return zyx27;
	}   
	/**
	 * 属性zyx27的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx27 String
	 */
	public void setZyx27 (String newZyx27 ) {
	 	this.zyx27 = newZyx27;
	} 	  
	/**
	 * 属性zyx20的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx20 () {
		return zyx20;
	}   
	/**
	 * 属性zyx20的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx20 String
	 */
	public void setZyx20 (String newZyx20 ) {
	 	this.zyx20 = newZyx20;
	} 	  
	/**
	 * 属性wldx的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public Integer getWldx () {
		return wldx;
	}   
	/**
	 * 属性wldx的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newWldx UFDouble
	 */
	public void setWldx (Integer newWldx ) {
	 	this.wldx = newWldx;
	} 	  
	/**
	 * 属性ctzhtlx_pk的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getCtzhtlx_pk () {
		return ctzhtlx_pk;
	}   
	/**
	 * 属性ctzhtlx_pk的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newCtzhtlx_pk String
	 */
	public void setCtzhtlx_pk (String newCtzhtlx_pk ) {
	 	this.ctzhtlx_pk = newCtzhtlx_pk;
	} 	  
	/**
	 * 属性skyhdz的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getSkyhdz () {
		return skyhdz;
	}   
	/**
	 * 属性skyhdz的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSkyhdz String
	 */
	public void setSkyhdz (String newSkyhdz ) {
	 	this.skyhdz = newSkyhdz;
	} 	  
	/**
	 * 属性zyx22的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx22 () {
		return zyx22;
	}   
	/**
	 * 属性zyx22的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx22 String
	 */
	public void setZyx22 (String newZyx22 ) {
	 	this.zyx22 = newZyx22;
	} 	  
	/**
	 * 属性zyx4的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx4 () {
		return zyx4;
	}   
	/**
	 * 属性zyx4的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx4 String
	 */
	public void setZyx4 (String newZyx4 ) {
	 	this.zyx4 = newZyx4;
	} 	  
	/**
	 * 属性ywxz的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getYwxz () {
		return ywxz;
	}   
	/**
	 * 属性ywxz的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newYwxz String
	 */
	public void setYwxz (String newYwxz ) {
	 	this.ywxz = newYwxz;
	} 	  
	/**
	 * 属性zyx25的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx25 () {
		return zyx25;
	}   
	/**
	 * 属性zyx25的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx25 String
	 */
	public void setZyx25 (String newZyx25 ) {
	 	this.zyx25 = newZyx25;
	} 	  
	/**
	 * 属性jshj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getJshj () {
		return jshj;
	}   
	/**
	 * 属性jshj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newJshj UFDouble
	 */
	public void setJshj (UFDouble newJshj ) {
	 	this.jshj = newJshj;
	} 	  
	/**
	 * 属性zyx23的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx23 () {
		return zyx23;
	}   
	/**
	 * 属性zyx23的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx23 String
	 */
	public void setZyx23 (String newZyx23 ) {
	 	this.zyx23 = newZyx23;
	} 	  
	/**
	 * 属性vouchid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getVouchid () {
		return vouchid;
	}   
	/**
	 * 属性vouchid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newVouchid String
	 */
	public void setVouchid (String newVouchid ) {
	 	this.vouchid = newVouchid;
	} 	  
	/**
	 * 属性ckdid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getCkdid () {
		return ckdid;
	}   
	/**
	 * 属性ckdid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newCkdid String
	 */
	public void setCkdid (String newCkdid ) {
	 	this.ckdid = newCkdid;
	} 	  
	/**
	 * 属性kxyt的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getKxyt () {
		return kxyt;
	}   
	/**
	 * 属性kxyt的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newKxyt String
	 */
	public void setKxyt (String newKxyt ) {
	 	this.kxyt = newKxyt;
	} 	  
	/**
	 * 属性isverifyfinished的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFBoolean
	 */
	public UFBoolean getIsverifyfinished () {
		return isverifyfinished;
	}   
	/**
	 * 属性isverifyfinished的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newIsverifyfinished UFBoolean
	 */
	public void setIsverifyfinished (UFBoolean newIsverifyfinished ) {
	 	this.isverifyfinished = newIsverifyfinished;
	} 	  
	/**
	 * 属性zyx24的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx24 () {
		return zyx24;
	}   
	/**
	 * 属性zyx24的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx24 String
	 */
	public void setZyx24 (String newZyx24 ) {
	 	this.zyx24 = newZyx24;
	} 	  
	/**
	 * 属性zyx5的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx5 () {
		return zyx5;
	}   
	/**
	 * 属性zyx5的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx5 String
	 */
	public void setZyx5 (String newZyx5 ) {
	 	this.zyx5 = newZyx5;
	} 	  
	/**
	 * 属性zyx29的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx29 () {
		return zyx29;
	}   
	/**
	 * 属性zyx29的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx29 String
	 */
	public void setZyx29 (String newZyx29 ) {
	 	this.zyx29 = newZyx29;
	} 	  
	/**
	 * 属性bbtxfy的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getBbtxfy () {
		return bbtxfy;
	}   
	/**
	 * 属性bbtxfy的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newBbtxfy UFDouble
	 */
	public void setBbtxfy (UFDouble newBbtxfy ) {
	 	this.bbtxfy = newBbtxfy;
	} 	  
	/**
	 * 属性djbh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDjbh () {
		return djbh;
	}   
	/**
	 * 属性djbh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDjbh String
	 */
	public void setDjbh (String newDjbh ) {
	 	this.djbh = newDjbh;
	} 	  
	/**
	 * 属性dfshl的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getDfshl () {
		return dfshl;
	}   
	/**
	 * 属性dfshl的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDfshl UFDouble
	 */
	public void setDfshl (UFDouble newDfshl ) {
	 	this.dfshl = newDfshl;
	} 	  
	/**
	 * 属性deptid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDeptid () {
		return deptid;
	}   
	/**
	 * 属性deptid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDeptid String
	 */
	public void setDeptid (String newDeptid ) {
	 	this.deptid = newDeptid;
	} 	  
	/**
	 * 属性shlye的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getShlye () {
		return shlye;
	}   
	/**
	 * 属性shlye的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newShlye UFDouble
	 */
	public void setShlye (UFDouble newShlye ) {
	 	this.shlye = newShlye;
	} 	  
	/**
	 * 属性tax_num的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getTax_num () {
		return tax_num;
	}   
	/**
	 * 属性tax_num的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newTax_num String
	 */
	public void setTax_num (String newTax_num ) {
	 	this.tax_num = newTax_num;
	} 	  
	/**
	 * 属性jfybje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getJfybje () {
		return jfybje;
	}   
	/**
	 * 属性jfybje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newJfybje UFDouble
	 */
	public void setJfybje (UFDouble newJfybje ) {
	 	this.jfybje = newJfybje;
	} 	  
	/**
	 * 属性bbye的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getBbye () {
		return bbye;
	}   
	/**
	 * 属性bbye的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newBbye UFDouble
	 */
	public void setBbye (UFDouble newBbye ) {
	 	this.bbye = newBbye;
	} 	  
	/**
	 * 属性jfbbsj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getJfbbsj () {
		return jfbbsj;
	}   
	/**
	 * 属性jfbbsj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newJfbbsj UFDouble
	 */
	public void setJfbbsj (UFDouble newJfbbsj ) {
	 	this.jfbbsj = newJfbbsj;
	} 	  
	/**
	 * 属性wbfbbje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getWbfbbje () {
		return wbfbbje;
	}   
	/**
	 * 属性wbfbbje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newWbfbbje UFDouble
	 */
	public void setWbfbbje (UFDouble newWbfbbje ) {
	 	this.wbfbbje = newWbfbbje;
	} 	  
	/**
	 * 属性zkl的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getZkl () {
		return zkl;
	}   
	/**
	 * 属性zkl的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZkl UFDouble
	 */
	public void setZkl (UFDouble newZkl ) {
	 	this.zkl = newZkl;
	} 	  
	/**
	 * 属性dfybsj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getDfybsj () {
		return dfybsj;
	}   
	/**
	 * 属性dfybsj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDfybsj UFDouble
	 */
	public void setDfybsj (UFDouble newDfybsj ) {
	 	this.dfybsj = newDfybsj;
	} 	  
	/**
	 * 属性pch的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getPch () {
		return pch;
	}   
	/**
	 * 属性pch的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPch String
	 */
	public void setPch (String newPch ) {
	 	this.pch = newPch;
	} 	  
	/**
	 * 属性jfzkfbje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getJfzkfbje () {
		return jfzkfbje;
	}   
	/**
	 * 属性jfzkfbje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newJfzkfbje UFDouble
	 */
	public void setJfzkfbje (UFDouble newJfzkfbje ) {
	 	this.jfzkfbje = newJfzkfbje;
	} 	  
	/**
	 * 属性chbm_cl的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getChbm_cl () {
		return chbm_cl;
	}   
	/**
	 * 属性chbm_cl的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newChbm_cl String
	 */
	public void setChbm_cl (String newChbm_cl ) {
	 	this.chbm_cl = newChbm_cl;
	} 	  
	/**
	 * 属性dfbbsj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getDfbbsj () {
		return dfbbsj;
	}   
	/**
	 * 属性dfbbsj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDfbbsj UFDouble
	 */
	public void setDfbbsj (UFDouble newDfbbsj ) {
	 	this.dfbbsj = newDfbbsj;
	} 	  
	/**
	 * 属性jfybsj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getJfybsj () {
		return jfybsj;
	}   
	/**
	 * 属性jfybsj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newJfybsj UFDouble
	 */
	public void setJfybsj (UFDouble newJfybsj ) {
	 	this.jfybsj = newJfybsj;
	} 	  
	/**
	 * 属性htbh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getHtbh () {
		return htbh;
	}   
	/**
	 * 属性htbh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newHtbh String
	 */
	public void setHtbh (String newHtbh ) {
	 	this.htbh = newHtbh;
	} 	  
	/**
	 * 属性tbbh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getTbbh () {
		return tbbh;
	}   
	/**
	 * 属性tbbh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newTbbh String
	 */
	public void setTbbh (String newTbbh ) {
	 	this.tbbh = newTbbh;
	} 	  
	/**
	 * 属性ddhh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDdhh () {
		return ddhh;
	}   
	/**
	 * 属性ddhh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDdhh String
	 */
	public void setDdhh (String newDdhh ) {
	 	this.ddhh = newDdhh;
	} 	  
	/**
	 * 属性ksbm_cl的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getKsbm_cl () {
		return ksbm_cl;
	}   
	/**
	 * 属性ksbm_cl的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newKsbm_cl String
	 */
	public void setKsbm_cl (String newKsbm_cl ) {
	 	this.ksbm_cl = newKsbm_cl;
	} 	  
	/**
	 * 属性sl的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getSl () {
		return sl;
	}   
	/**
	 * 属性sl的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSl UFDouble
	 */
	public void setSl (UFDouble newSl ) {
	 	this.sl = newSl;
	} 	  
	/**
	 * 属性dwbm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDwbm () {
		return dwbm;
	}   
	/**
	 * 属性dwbm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDwbm String
	 */
	public void setDwbm (String newDwbm ) {
	 	this.dwbm = newDwbm;
	} 	  
	/**
	 * 属性bz_date的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getBz_date () {
		return bz_date;
	}   
	/**
	 * 属性bz_date的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newBz_date UFDate
	 */
	public void setBz_date (UFDate newBz_date ) {
	 	this.bz_date = newBz_date;
	} 	  
	/**
	 * 属性dfbbje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getDfbbje () {
		return dfbbje;
	}   
	/**
	 * 属性dfbbje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDfbbje UFDouble
	 */
	public void setDfbbje (UFDouble newDfbbje ) {
	 	this.dfbbje = newDfbbje;
	} 	  
	/**
	 * 属性pj_jsfs的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getPj_jsfs () {
		return pj_jsfs;
	}   
	/**
	 * 属性pj_jsfs的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPj_jsfs String
	 */
	public void setPj_jsfs (String newPj_jsfs ) {
	 	this.pj_jsfs = newPj_jsfs;
	} 	  
	/**
	 * 属性xmbm4的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getXmbm4 () {
		return xmbm4;
	}   
	/**
	 * 属性xmbm4的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newXmbm4 String
	 */
	public void setXmbm4 (String newXmbm4 ) {
	 	this.xmbm4 = newXmbm4;
	} 	  
	/**
	 * 属性bfyhzh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getBfyhzh () {
		return bfyhzh;
	}   
	/**
	 * 属性bfyhzh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newBfyhzh String
	 */
	public void setBfyhzh (String newBfyhzh ) {
	 	this.bfyhzh = newBfyhzh;
	} 	  
	/**
	 * 属性ywbm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getYwbm () {
		return ywbm;
	}   
	/**
	 * 属性ywbm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newYwbm String
	 */
	public void setYwbm (String newYwbm ) {
	 	this.ywbm = newYwbm;
	} 	  
	/**
	 * 属性pjdirection的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getPjdirection () {
		return pjdirection;
	}   
	/**
	 * 属性pjdirection的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPjdirection String
	 */
	public void setPjdirection (String newPjdirection ) {
	 	this.pjdirection = newPjdirection;
	} 	  
	/**
	 * 属性jobid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getJobid () {
		return jobid;
	}   
	/**
	 * 属性jobid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newJobid String
	 */
	public void setJobid (String newJobid ) {
	 	this.jobid = newJobid;
	} 	  
	/**
	 * 属性bankrollprojet的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getBankrollprojet () {
		return bankrollprojet;
	}   
	/**
	 * 属性bankrollprojet的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newBankrollprojet String
	 */
	public void setBankrollprojet (String newBankrollprojet ) {
	 	this.bankrollprojet = newBankrollprojet;
	} 	  
	/**
	 * 属性dfyhzh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDfyhzh () {
		return dfyhzh;
	}   
	/**
	 * 属性dfyhzh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDfyhzh String
	 */
	public void setDfyhzh (String newDfyhzh ) {
	 	this.dfyhzh = newDfyhzh;
	} 	  
	/**
	 * 属性assetpactno的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getAssetpactno () {
		return assetpactno;
	}   
	/**
	 * 属性assetpactno的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newAssetpactno String
	 */
	public void setAssetpactno (String newAssetpactno ) {
	 	this.assetpactno = newAssetpactno;
	} 	  
	/**
	 * 属性item_bill_pk的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getItem_bill_pk () {
		return item_bill_pk;
	}   
	/**
	 * 属性item_bill_pk的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newItem_bill_pk String
	 */
	public void setItem_bill_pk (String newItem_bill_pk ) {
	 	this.item_bill_pk = newItem_bill_pk;
	} 	  
	/**
	 * 属性flbh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public Integer getFlbh () {
		return flbh;
	}   
	/**
	 * 属性flbh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFlbh UFDouble
	 */
	public void setFlbh (Integer newFlbh ) {
	 	this.flbh = newFlbh;
	} 	  
	/**
	 * 属性clbh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getClbh () {
		return clbh;
	}   
	/**
	 * 属性clbh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newClbh String
	 */
	public void setClbh (String newClbh ) {
	 	this.clbh = newClbh;
	} 	  
	/**
	 * 属性fbhl的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getFbhl () {
		return fbhl;
	}   
	/**
	 * 属性fbhl的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFbhl UFDouble
	 */
	public void setFbhl (UFDouble newFbhl ) {
	 	this.fbhl = newFbhl;
	} 	  
	/**
	 * 属性zyx2的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx2 () {
		return zyx2;
	}   
	/**
	 * 属性zyx2的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx2 String
	 */
	public void setZyx2 (String newZyx2 ) {
	 	this.zyx2 = newZyx2;
	} 	  
	/**
	 * 属性ysfbye的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getYsfbye () {
		return ysfbye;
	}   
	/**
	 * 属性ysfbye的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newYsfbye UFDouble
	 */
	public void setYsfbye (UFDouble newYsfbye ) {
	 	this.ysfbye = newYsfbye;
	} 	  
	/**
	 * 属性ordercusmandoc的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getOrdercusmandoc () {
		return ordercusmandoc;
	}   
	/**
	 * 属性ordercusmandoc的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newOrdercusmandoc String
	 */
	public void setOrdercusmandoc (String newOrdercusmandoc ) {
	 	this.ordercusmandoc = newOrdercusmandoc;
	} 	  
	/**
	 * 属性txlx_ybje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getTxlx_ybje () {
		return txlx_ybje;
	}   
	/**
	 * 属性txlx_ybje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newTxlx_ybje UFDouble
	 */
	public void setTxlx_ybje (UFDouble newTxlx_ybje ) {
	 	this.txlx_ybje = newTxlx_ybje;
	} 	  
	/**
	 * 属性zrdeptid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZrdeptid () {
		return zrdeptid;
	}   
	/**
	 * 属性zrdeptid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZrdeptid String
	 */
	public void setZrdeptid (String newZrdeptid ) {
	 	this.zrdeptid = newZrdeptid;
	} 	  
	/**
	 * 属性xgbh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public Integer getXgbh () {
		return xgbh;
	}   
	/**
	 * 属性xgbh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newXgbh UFDouble
	 */
	public void setXgbh (Integer newXgbh ) {
	 	this.xgbh = newXgbh;
	} 	  
	/**
	 * 属性jfjs的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getJfjs () {
		return jfjs;
	}   
	/**
	 * 属性jfjs的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newJfjs UFDouble
	 */
	public void setJfjs (UFDouble newJfjs ) {
	 	this.jfjs = newJfjs;
	} 	  
	/**
	 * 属性fph的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getFph () {
		return fph;
	}   
	/**
	 * 属性fph的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFph String
	 */
	public void setFph (String newFph ) {
	 	this.fph = newFph;
	} 	  
	/**
	 * 属性payman的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getPayman () {
		return payman;
	}   
	/**
	 * 属性payman的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPayman String
	 */
	public void setPayman (String newPayman ) {
	 	this.payman = newPayman;
	} 	  
	/**
	 * 属性chmc的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getChmc () {
		return chmc;
	}   
	/**
	 * 属性chmc的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newChmc String
	 */
	public void setChmc (String newChmc ) {
	 	this.chmc = newChmc;
	} 	  
	/**
	 * 属性facardbh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getFacardbh () {
		return facardbh;
	}   
	/**
	 * 属性facardbh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFacardbh String
	 */
	public void setFacardbh (String newFacardbh ) {
	 	this.facardbh = newFacardbh;
	} 	  
	/**
	 * 属性zjldw的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZjldw () {
		return zjldw;
	}   
	/**
	 * 属性zjldw的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZjldw String
	 */
	public void setZjldw (String newZjldw ) {
	 	this.zjldw = newZjldw;
	} 	  
	/**
	 * 属性pk_jobobjpha的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getPk_jobobjpha () {
		return pk_jobobjpha;
	}   
	/**
	 * 属性pk_jobobjpha的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPk_jobobjpha String
	 */
	public void setPk_jobobjpha (String newPk_jobobjpha ) {
	 	this.pk_jobobjpha = newPk_jobobjpha;
	} 	  
	/**
	 * 属性sanhu的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getSanhu () {
		return sanhu;
	}   
	/**
	 * 属性sanhu的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSanhu String
	 */
	public void setSanhu (String newSanhu ) {
	 	this.sanhu = newSanhu;
	} 	  
	/**
	 * 属性dfybwsje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getDfybwsje () {
		return dfybwsje;
	}   
	/**
	 * 属性dfybwsje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDfybwsje UFDouble
	 */
	public void setDfybwsje (UFDouble newDfybwsje ) {
	 	this.dfybwsje = newDfybwsje;
	} 	  
	/**
	 * 属性sfbz的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getSfbz () {
		return sfbz;
	}   
	/**
	 * 属性sfbz的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSfbz String
	 */
	public void setSfbz (String newSfbz ) {
	 	this.sfbz = newSfbz;
	} 	  
	/**
	 * 属性payflag的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getPayflag () {
		return payflag;
	}   
	/**
	 * 属性payflag的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPayflag UFDouble
	 */
	public void setPayflag (UFDouble newPayflag ) {
	 	this.payflag = newPayflag;
	} 	  
	/**
	 * 属性wbffbje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getWbffbje () {
		return wbffbje;
	}   
	/**
	 * 属性wbffbje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newWbffbje UFDouble
	 */
	public void setWbffbje (UFDouble newWbffbje ) {
	 	this.wbffbje = newWbffbje;
	} 	  
	/**
	 * 属性jffbje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getJffbje () {
		return jffbje;
	}   
	/**
	 * 属性jffbje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newJffbje UFDouble
	 */
	public void setJffbje (UFDouble newJffbje ) {
	 	this.jffbje = newJffbje;
	} 	  
	/**
	 * 属性commonflag的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getCommonflag () {
		return commonflag;
	}   
	/**
	 * 属性commonflag的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newCommonflag String
	 */
	public void setCommonflag (String newCommonflag ) {
	 	this.commonflag = newCommonflag;
	} 	  
	/**
	 * 属性zyx8的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx8 () {
		return zyx8;
	}   
	/**
	 * 属性zyx8的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx8 String
	 */
	public void setZyx8 (String newZyx8 ) {
	 	this.zyx8 = newZyx8;
	} 	  
	/**
	 * 属性produceorder的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getProduceorder () {
		return produceorder;
	}   
	/**
	 * 属性produceorder的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newProduceorder String
	 */
	public void setProduceorder (String newProduceorder ) {
	 	this.produceorder = newProduceorder;
	} 	  
	/**
	 * 属性pzflh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getPzflh () {
		return pzflh;
	}   
	/**
	 * 属性pzflh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPzflh UFDouble
	 */
	public void setPzflh (UFDouble newPzflh ) {
	 	this.pzflh = newPzflh;
	} 	  
	/**
	 * 属性dffbje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getDffbje () {
		return dffbje;
	}   
	/**
	 * 属性dffbje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDffbje UFDouble
	 */
	public void setDffbje (UFDouble newDffbje ) {
	 	this.dffbje = newDffbje;
	} 	  
	/**
	 * 属性zyx28的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx28 () {
		return zyx28;
	}   
	/**
	 * 属性zyx28的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx28 String
	 */
	public void setZyx28 (String newZyx28 ) {
	 	this.zyx28 = newZyx28;
	} 	  
	/**
	 * 属性zyx9的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx9 () {
		return zyx9;
	}   
	/**
	 * 属性zyx9的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx9 String
	 */
	public void setZyx9 (String newZyx9 ) {
	 	this.zyx9 = newZyx9;
	} 	  
	/**
	 * 属性skyhmc的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getSkyhmc () {
		return skyhmc;
	}   
	/**
	 * 属性skyhmc的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSkyhmc String
	 */
	public void setSkyhmc (String newSkyhmc ) {
	 	this.skyhmc = newSkyhmc;
	} 	  
	/**
	 * 属性ph的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getPh () {
		return ph;
	}   
	/**
	 * 属性ph的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPh String
	 */
	public void setPh (String newPh ) {
	 	this.ph = newPh;
	} 	  
	/**
	 * 属性seqnum的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getSeqnum () {
		return seqnum;
	}   
	/**
	 * 属性seqnum的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSeqnum String
	 */
	public void setSeqnum (String newSeqnum ) {
	 	this.seqnum = newSeqnum;
	} 	  
	/**
	 * 属性dffbsj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getDffbsj () {
		return dffbsj;
	}   
	/**
	 * 属性dffbsj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDffbsj UFDouble
	 */
	public void setDffbsj (UFDouble newDffbsj ) {
	 	this.dffbsj = newDffbsj;
	} 	  
	/**
	 * 属性bzbm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getBzbm () {
		return bzbm;
	}   
	/**
	 * 属性bzbm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newBzbm String
	 */
	public void setBzbm (String newBzbm ) {
	 	this.bzbm = newBzbm;
	} 	  
	/**
	 * 属性bjjldw的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getBjjldw () {
		return bjjldw;
	}   
	/**
	 * 属性bjjldw的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newBjjldw String
	 */
	public void setBjjldw (String newBjjldw ) {
	 	this.bjjldw = newBjjldw;
	} 	  
	/**
	 * 属性pausetransact的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFBoolean
	 */
	public UFBoolean getPausetransact () {
		return pausetransact;
	}   
	/**
	 * 属性pausetransact的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPausetransact UFBoolean
	 */
	public void setPausetransact (UFBoolean newPausetransact ) {
	 	this.pausetransact = newPausetransact;
	} 	  
	/**
	 * 属性spzt的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getSpzt () {
		return spzt;
	}   
	/**
	 * 属性spzt的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSpzt UFDouble
	 */
	public void setSpzt (UFDouble newSpzt ) {
	 	this.spzt = newSpzt;
	} 	  
	/**
	 * 属性zyx7的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx7 () {
		return zyx7;
	}   
	/**
	 * 属性zyx7的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx7 String
	 */
	public void setZyx7 (String newZyx7 ) {
	 	this.zyx7 = newZyx7;
	} 	  
	/**
	 * 属性dfybje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getDfybje () {
		return dfybje;
	}   
	/**
	 * 属性dfybje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDfybje UFDouble
	 */
	public void setDfybje (UFDouble newDfybje ) {
	 	this.dfybje = newDfybje;
	} 	  
	/**
	 * 属性jfbbje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getJfbbje () {
		return jfbbje;
	}   
	/**
	 * 属性jfbbje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newJfbbje UFDouble
	 */
	public void setJfbbje (UFDouble newJfbbje ) {
	 	this.jfbbje = newJfbbje;
	} 	  
	/**
	 * 属性zyx6的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx6 () {
		return zyx6;
	}   
	/**
	 * 属性zyx6的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx6 String
	 */
	public void setZyx6 (String newZyx6 ) {
	 	this.zyx6 = newZyx6;
	} 	  
	/**
	 * 属性hbbm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getHbbm () {
		return hbbm;
	}   
	/**
	 * 属性hbbm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newHbbm String
	 */
	public void setHbbm (String newHbbm ) {
	 	this.hbbm = newHbbm;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性bz_kjnd的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getBz_kjnd () {
		return bz_kjnd;
	}   
	/**
	 * 属性bz_kjnd的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newBz_kjnd String
	 */
	public void setBz_kjnd (String newBz_kjnd ) {
	 	this.bz_kjnd = newBz_kjnd;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性ybpjlx的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getYbpjlx () {
		return ybpjlx;
	}   
	/**
	 * 属性ybpjlx的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newYbpjlx UFDouble
	 */
	public void setYbpjlx (UFDouble newYbpjlx ) {
	 	this.ybpjlx = newYbpjlx;
	} 	  
	/**
	 * 属性qxrq的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getQxrq () {
		return qxrq;
	}   
	/**
	 * 属性qxrq的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newQxrq UFDate
	 */
	public void setQxrq (UFDate newQxrq ) {
	 	this.qxrq = newQxrq;
	} 	  
	/**
	 * 属性verifyfinisheddate的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getVerifyfinisheddate () {
		return verifyfinisheddate;
	}   
	/**
	 * 属性verifyfinisheddate的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newVerifyfinisheddate UFDate
	 */
	public void setVerifyfinisheddate (UFDate newVerifyfinisheddate ) {
	 	this.verifyfinisheddate = newVerifyfinisheddate;
	} 	  
	/**
	 * 属性zyx30的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx30 () {
		return zyx30;
	}   
	/**
	 * 属性zyx30的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx30 String
	 */
	public void setZyx30 (String newZyx30 ) {
	 	this.zyx30 = newZyx30;
	} 	  
	/**
	 * 属性zyx12的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx12 () {
		return zyx12;
	}   
	/**
	 * 属性zyx12的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx12 String
	 */
	public void setZyx12 (String newZyx12 ) {
	 	this.zyx12 = newZyx12;
	} 	  
	/**
	 * 属性ggxh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getGgxh () {
		return ggxh;
	}   
	/**
	 * 属性ggxh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newGgxh String
	 */
	public void setGgxh (String newGgxh ) {
	 	this.ggxh = newGgxh;
	} 	  
	/**
	 * 属性usedept的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getUsedept () {
		return usedept;
	}   
	/**
	 * 属性usedept的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newUsedept String
	 */
	public void setUsedept (String newUsedept ) {
	 	this.usedept = newUsedept;
	} 	  
	/**
	 * 属性occupationmny的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getOccupationmny () {
		return occupationmny;
	}   
	/**
	 * 属性occupationmny的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newOccupationmny UFDouble
	 */
	public void setOccupationmny (UFDouble newOccupationmny ) {
	 	this.occupationmny = newOccupationmny;
	} 	  
	/**
	 * 属性dstlsubcs的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDstlsubcs () {
		return dstlsubcs;
	}   
	/**
	 * 属性dstlsubcs的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDstlsubcs String
	 */
	public void setDstlsubcs (String newDstlsubcs ) {
	 	this.dstlsubcs = newDstlsubcs;
	} 	  
	/**
	 * 属性accountid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getAccountid () {
		return accountid;
	}   
	/**
	 * 属性accountid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newAccountid String
	 */
	public void setAccountid (String newAccountid ) {
	 	this.accountid = newAccountid;
	} 	  
	/**
	 * 属性itemstyle的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getItemstyle () {
		return itemstyle;
	}   
	/**
	 * 属性itemstyle的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newItemstyle String
	 */
	public void setItemstyle (String newItemstyle ) {
	 	this.itemstyle = newItemstyle;
	} 	  
	/**
	 * 属性ybtxfy的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getYbtxfy () {
		return ybtxfy;
	}   
	/**
	 * 属性ybtxfy的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newYbtxfy UFDouble
	 */
	public void setYbtxfy (UFDouble newYbtxfy ) {
	 	this.ybtxfy = newYbtxfy;
	} 	  
	/**
	 * 属性xm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getXm () {
		return xm;
	}   
	/**
	 * 属性xm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newXm String
	 */
	public void setXm (String newXm ) {
	 	this.xm = newXm;
	} 	  
	/**
	 * 属性htmc的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getHtmc () {
		return htmc;
	}   
	/**
	 * 属性htmc的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newHtmc String
	 */
	public void setHtmc (String newHtmc ) {
	 	this.htmc = newHtmc;
	} 	  
	/**
	 * 属性jfzkybje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getJfzkybje () {
		return jfzkybje;
	}   
	/**
	 * 属性jfzkybje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newJfzkybje UFDouble
	 */
	public void setJfzkybje (UFDouble newJfzkybje ) {
	 	this.jfzkybje = newJfzkybje;
	} 	  
	/**
	 * 属性issfkxychanged的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFBoolean
	 */
	public UFBoolean getIssfkxychanged () {
		return issfkxychanged;
	}   
	/**
	 * 属性issfkxychanged的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newIssfkxychanged UFBoolean
	 */
	public void setIssfkxychanged (UFBoolean newIssfkxychanged ) {
	 	this.issfkxychanged = newIssfkxychanged;
	} 	  
	/**
	 * 属性fjldw的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getFjldw () {
		return fjldw;
	}   
	/**
	 * 属性fjldw的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFjldw String
	 */
	public void setFjldw (String newFjldw ) {
	 	this.fjldw = newFjldw;
	} 	  
	/**
	 * 属性encode的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getEncode () {
		return encode;
	}   
	/**
	 * 属性encode的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newEncode String
	 */
	public void setEncode (String newEncode ) {
	 	this.encode = newEncode;
	} 	  
	/**
	 * 属性fbye的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getFbye () {
		return fbye;
	}   
	/**
	 * 属性fbye的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFbye UFDouble
	 */
	public void setFbye (UFDouble newFbye ) {
	 	this.fbye = newFbye;
	} 	  
	/**
	 * 属性ywybm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getYwybm () {
		return ywybm;
	}   
	/**
	 * 属性ywybm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newYwybm String
	 */
	public void setYwybm (String newYwybm ) {
	 	this.ywybm = newYwybm;
	} 	  
	/**
	 * 属性zyx11的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx11 () {
		return zyx11;
	}   
	/**
	 * 属性zyx11的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx11 String
	 */
	public void setZyx11 (String newZyx11 ) {
	 	this.zyx11 = newZyx11;
	} 	  
	/**
	 * 属性zyx16的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx16 () {
		return zyx16;
	}   
	/**
	 * 属性zyx16的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx16 String
	 */
	public void setZyx16 (String newZyx16 ) {
	 	this.zyx16 = newZyx16;
	} 	  
	/**
	 * 属性freeitemid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getFreeitemid () {
		return freeitemid;
	}   
	/**
	 * 属性freeitemid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFreeitemid String
	 */
	public void setFreeitemid (String newFreeitemid ) {
	 	this.freeitemid = newFreeitemid;
	} 	  
	/**
	 * 属性dfjs的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getDfjs () {
		return dfjs;
	}   
	/**
	 * 属性dfjs的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDfjs UFDouble
	 */
	public void setDfjs (UFDouble newDfjs ) {
	 	this.dfjs = newDfjs;
	} 	  
	/**
	 * 属性xyzh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getXyzh () {
		return xyzh;
	}   
	/**
	 * 属性xyzh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newXyzh String
	 */
	public void setXyzh (String newXyzh ) {
	 	this.xyzh = newXyzh;
	} 	  
	/**
	 * 属性xmys的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getXmys () {
		return xmys;
	}   
	/**
	 * 属性xmys的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newXmys String
	 */
	public void setXmys (String newXmys ) {
	 	this.xmys = newXmys;
	} 	  
	/**
	 * 属性jfybwsje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getJfybwsje () {
		return jfybwsje;
	}   
	/**
	 * 属性jfybwsje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newJfybwsje UFDouble
	 */
	public void setJfybwsje (UFDouble newJfybwsje ) {
	 	this.jfybwsje = newJfybwsje;
	} 	  
	/**
	 * 属性fkyhmc的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getFkyhmc () {
		return fkyhmc;
	}   
	/**
	 * 属性fkyhmc的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFkyhmc String
	 */
	public void setFkyhmc (String newFkyhmc ) {
	 	this.fkyhmc = newFkyhmc;
	} 	  
	/**
	 * 属性srbz的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFBoolean
	 */
	public UFBoolean getSrbz () {
		return srbz;
	}   
	/**
	 * 属性srbz的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSrbz UFBoolean
	 */
	public void setSrbz (UFBoolean newSrbz ) {
	 	this.srbz = newSrbz;
	} 	  
	/**
	 * 属性bjdwsl的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getBjdwsl () {
		return bjdwsl;
	}   
	/**
	 * 属性bjdwsl的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newBjdwsl UFDouble
	 */
	public void setBjdwsl (UFDouble newBjdwsl ) {
	 	this.bjdwsl = newBjdwsl;
	} 	  
	/**
	 * 属性task的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getTask () {
		return task;
	}   
	/**
	 * 属性task的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newTask String
	 */
	public void setTask (String newTask ) {
	 	this.task = newTask;
	} 	  
	/**
	 * 属性fphid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getFphid () {
		return fphid;
	}   
	/**
	 * 属性fphid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFphid String
	 */
	public void setFphid (String newFphid ) {
	 	this.fphid = newFphid;
	} 	  
	/**
	 * 属性cksqsh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getCksqsh () {
		return cksqsh;
	}   
	/**
	 * 属性cksqsh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newCksqsh String
	 */
	public void setCksqsh (String newCksqsh ) {
	 	this.cksqsh = newCksqsh;
	} 	  
	/**
	 * 属性jobphaseid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getJobphaseid () {
		return jobphaseid;
	}   
	/**
	 * 属性jobphaseid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newJobphaseid String
	 */
	public void setJobphaseid (String newJobphaseid ) {
	 	this.jobphaseid = newJobphaseid;
	} 	  
	/**
	 * 属性djlxbm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDjlxbm () {
		return djlxbm;
	}   
	/**
	 * 属性djlxbm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDjlxbm String
	 */
	public void setDjlxbm (String newDjlxbm ) {
	 	this.djlxbm = newDjlxbm;
	} 	  
	/**
	 * 属性othersysflag的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getOthersysflag () {
		return othersysflag;
	}   
	/**
	 * 属性othersysflag的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newOthersysflag String
	 */
	public void setOthersysflag (String newOthersysflag ) {
	 	this.othersysflag = newOthersysflag;
	} 	  
	/**
	 * 属性bjdwhsdj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getBjdwhsdj () {
		return bjdwhsdj;
	}   
	/**
	 * 属性bjdwhsdj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newBjdwhsdj UFDouble
	 */
	public void setBjdwhsdj (UFDouble newBjdwhsdj ) {
	 	this.bjdwhsdj = newBjdwhsdj;
	} 	  
	/**
	 * 属性ybye的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getYbye () {
		return ybye;
	}   
	/**
	 * 属性ybye的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newYbye UFDouble
	 */
	public void setYbye (UFDouble newYbye ) {
	 	this.ybye = newYbye;
	} 	  
	/**
	 * 属性fb_oid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getFb_oid () {
		return fb_oid;
	}   
	/**
	 * 属性fb_oid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFb_oid String
	 */
	public void setFb_oid (String newFb_oid ) {
	 	this.fb_oid = newFb_oid;
	} 	  
	/**
	 * 属性zyx10的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx10 () {
		return zyx10;
	}   
	/**
	 * 属性zyx10的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx10 String
	 */
	public void setZyx10 (String newZyx10 ) {
	 	this.zyx10 = newZyx10;
	} 	  
	/**
	 * 属性cashitem的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getCashitem () {
		return cashitem;
	}   
	/**
	 * 属性cashitem的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newCashitem String
	 */
	public void setCashitem (String newCashitem ) {
	 	this.cashitem = newCashitem;
	} 	  
	/**
	 * 属性kprq的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getKprq () {
		return kprq;
	}   
	/**
	 * 属性kprq的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newKprq UFDate
	 */
	public void setKprq (UFDate newKprq ) {
	 	this.kprq = newKprq;
	} 	  
	/**
	 * 属性szxmid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getSzxmid () {
		return szxmid;
	}   
	/**
	 * 属性szxmid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSzxmid String
	 */
	public void setSzxmid (String newSzxmid ) {
	 	this.szxmid = newSzxmid;
	} 	  
	/**
	 * 属性txlx_fbje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getTxlx_fbje () {
		return txlx_fbje;
	}   
	/**
	 * 属性txlx_fbje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newTxlx_fbje UFDouble
	 */
	public void setTxlx_fbje (UFDouble newTxlx_fbje ) {
	 	this.txlx_fbje = newTxlx_fbje;
	} 	  
	/**
	 * 属性equipmentcode的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getEquipmentcode () {
		return equipmentcode;
	}   
	/**
	 * 属性equipmentcode的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newEquipmentcode String
	 */
	public void setEquipmentcode (String newEquipmentcode ) {
	 	this.equipmentcode = newEquipmentcode;
	} 	  
	/**
	 * 属性notetype的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getNotetype () {
		return notetype;
	}   
	/**
	 * 属性notetype的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newNotetype String
	 */
	public void setNotetype (String newNotetype ) {
	 	this.notetype = newNotetype;
	} 	  
	/**
	 * 属性ddlx的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDdlx () {
		return ddlx;
	}   
	/**
	 * 属性ddlx的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDdlx String
	 */
	public void setDdlx (String newDdlx ) {
	 	this.ddlx = newDdlx;
	} 	  
	/**
	 * 属性ddh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDdh () {
		return ddh;
	}   
	/**
	 * 属性ddh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDdh String
	 */
	public void setDdh (String newDdh ) {
	 	this.ddh = newDdh;
	} 	  
	/**
	 * 属性zyx19的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx19 () {
		return zyx19;
	}   
	/**
	 * 属性zyx19的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx19 String
	 */
	public void setZyx19 (String newZyx19 ) {
	 	this.zyx19 = newZyx19;
	} 	  
	/**
	 * 属性zy的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZy () {
		return zy;
	}   
	/**
	 * 属性zy的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZy String
	 */
	public void setZy (String newZy ) {
	 	this.zy = newZy;
	} 	  
	/**
	 * 属性ddhid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDdhid () {
		return ddhid;
	}   
	/**
	 * 属性ddhid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDdhid String
	 */
	public void setDdhid (String newDdhid ) {
	 	this.ddhid = newDdhid;
	} 	  
	/**
	 * 属性sfkxyh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getSfkxyh () {
		return sfkxyh;
	}   
	/**
	 * 属性sfkxyh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSfkxyh String
	 */
	public void setSfkxyh (String newSfkxyh ) {
	 	this.sfkxyh = newSfkxyh;
	} 	  
	/**
	 * 属性cinventoryid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getCinventoryid () {
		return cinventoryid;
	}   
	/**
	 * 属性cinventoryid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newCinventoryid String
	 */
	public void setCinventoryid (String newCinventoryid ) {
	 	this.cinventoryid = newCinventoryid;
	} 	  
	/**
	 * 属性contractno的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getContractno () {
		return contractno;
	}   
	/**
	 * 属性contractno的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newContractno String
	 */
	public void setContractno (String newContractno ) {
	 	this.contractno = newContractno;
	} 	  
	/**
	 * 属性ysbbye的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getYsbbye () {
		return ysbbye;
	}   
	/**
	 * 属性ysbbye的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newYsbbye UFDouble
	 */
	public void setYsbbye (UFDouble newYsbbye ) {
	 	this.ysbbye = newYsbbye;
	} 	  
	/**
	 * 属性paydate的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getPaydate () {
		return paydate;
	}   
	/**
	 * 属性paydate的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPaydate UFDate
	 */
	public void setPaydate (UFDate newPaydate ) {
	 	this.paydate = newPaydate;
	} 	  
	/**
	 * 属性groupnum的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getGroupnum () {
		return groupnum;
	}   
	/**
	 * 属性groupnum的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newGroupnum String
	 */
	public void setGroupnum (String newGroupnum ) {
	 	this.groupnum = newGroupnum;
	} 	  
	/**
	 * 属性jffbsj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getJffbsj () {
		return jffbsj;
	}   
	/**
	 * 属性jffbsj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newJffbsj UFDouble
	 */
	public void setJffbsj (UFDouble newJffbsj ) {
	 	this.jffbsj = newJffbsj;
	} 	  
	/**
	 * 属性wbfybje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getWbfybje () {
		return wbfybje;
	}   
	/**
	 * 属性wbfybje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newWbfybje UFDouble
	 */
	public void setWbfybje (UFDouble newWbfybje ) {
	 	this.wbfybje = newWbfybje;
	} 	  
	/**
	 * 属性ckdh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getCkdh () {
		return ckdh;
	}   
	/**
	 * 属性ckdh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newCkdh String
	 */
	public void setCkdh (String newCkdh ) {
	 	this.ckdh = newCkdh;
	} 	  
	/**
	 * 属性dj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getDj () {
		return dj;
	}   
	/**
	 * 属性dj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDj UFDouble
	 */
	public void setDj (UFDouble newDj ) {
	 	this.dj = newDj;
	} 	  
	/**
	 * 属性bz_kjqj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getBz_kjqj () {
		return bz_kjqj;
	}   
	/**
	 * 属性bz_kjqj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newBz_kjqj String
	 */
	public void setBz_kjqj (String newBz_kjqj ) {
	 	this.bz_kjqj = newBz_kjqj;
	} 	  
	/**
	 * 属性billdate的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getBilldate () {
		return billdate;
	}   
	/**
	 * 属性billdate的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newBilldate UFDate
	 */
	public void setBilldate (UFDate newBilldate ) {
	 	this.billdate = newBilldate;
	} 	  
	/**
	 * 属性txlx_bbje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getTxlx_bbje () {
		return txlx_bbje;
	}   
	/**
	 * 属性txlx_bbje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newTxlx_bbje UFDouble
	 */
	public void setTxlx_bbje (UFDouble newTxlx_bbje ) {
	 	this.txlx_bbje = newTxlx_bbje;
	} 	  
	/**
	 * 属性zyx17的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx17 () {
		return zyx17;
	}   
	/**
	 * 属性zyx17的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx17 String
	 */
	public void setZyx17 (String newZyx17 ) {
	 	this.zyx17 = newZyx17;
	} 	  
	/**
	 * 属性bbpjlx的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getBbpjlx () {
		return bbpjlx;
	}   
	/**
	 * 属性bbpjlx的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newBbpjlx UFDouble
	 */
	public void setBbpjlx (UFDouble newBbpjlx ) {
	 	this.bbpjlx = newBbpjlx;
	} 	  
	/**
	 * 属性productline的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getProductline () {
		return productline;
	}   
	/**
	 * 属性productline的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newProductline String
	 */
	public void setProductline (String newProductline ) {
	 	this.productline = newProductline;
	} 	  
	/**
	 * 属性zyx18的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx18 () {
		return zyx18;
	}   
	/**
	 * 属性zyx18的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx18 String
	 */
	public void setZyx18 (String newZyx18 ) {
	 	this.zyx18 = newZyx18;
	} 	  
	/**
	 * 属性dfbbwsje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getDfbbwsje () {
		return dfbbwsje;
	}   
	/**
	 * 属性dfbbwsje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDfbbwsje UFDouble
	 */
	public void setDfbbwsje (UFDouble newDfbbwsje ) {
	 	this.dfbbwsje = newDfbbwsje;
	} 	  
	/**
	 * 属性ysybye的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getYsybye () {
		return ysybye;
	}   
	/**
	 * 属性ysybye的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newYsybye UFDouble
	 */
	public void setYsybye (UFDouble newYsybye ) {
	 	this.ysybye = newYsybye;
	} 	  
	/**
	 * 属性fx的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public Integer getFx () {
		return fx;
	}   
	/**
	 * 属性fx的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFx UFDouble
	 */
	public void setFx (Integer newFx ) {
	 	this.fx = newFx;
	} 	  
	/**
	 * 属性zyx15的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx15 () {
		return zyx15;
	}   
	/**
	 * 属性zyx15的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx15 String
	 */
	public void setZyx15 (String newZyx15 ) {
	 	this.zyx15 = newZyx15;
	} 	  
	/**
	 * 属性hsdj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getHsdj () {
		return hsdj;
	}   
	/**
	 * 属性hsdj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newHsdj UFDouble
	 */
	public void setHsdj (UFDouble newHsdj ) {
	 	this.hsdj = newHsdj;
	} 	  
	/**
	 * 属性zyx14的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx14 () {
		return zyx14;
	}   
	/**
	 * 属性zyx14的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx14 String
	 */
	public void setZyx14 (String newZyx14 ) {
	 	this.zyx14 = newZyx14;
	} 	  
	/**
	 * 属性fbtxfy的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getFbtxfy () {
		return fbtxfy;
	}   
	/**
	 * 属性fbtxfy的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFbtxfy UFDouble
	 */
	public void setFbtxfy (UFDouble newFbtxfy ) {
	 	this.fbtxfy = newFbtxfy;
	} 	  
	/**
	 * 属性jfshl的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getJfshl () {
		return jfshl;
	}   
	/**
	 * 属性jfshl的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newJfshl UFDouble
	 */
	public void setJfshl (UFDouble newJfshl ) {
	 	this.jfshl = newJfshl;
	} 	  
	/**
	 * 属性xbbm3的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getXbbm3 () {
		return xbbm3;
	}   
	/**
	 * 属性xbbm3的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newXbbm3 String
	 */
	public void setXbbm3 (String newXbbm3 ) {
	 	this.xbbm3 = newXbbm3;
	} 	  
	/**
	 * 属性djxtflag的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public Integer getDjxtflag () {
		return djxtflag;
	}   
	/**
	 * 属性djxtflag的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDjxtflag UFDouble
	 */
	public void setDjxtflag (Integer newDjxtflag ) {
	 	this.djxtflag = newDjxtflag;
	} 	  
	/**
	 * 属性old_sys_flag的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFBoolean
	 */
	public UFBoolean getOld_sys_flag () {
		return old_sys_flag;
	}   
	/**
	 * 属性old_sys_flag的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newOld_sys_flag UFBoolean
	 */
	public void setOld_sys_flag (UFBoolean newOld_sys_flag ) {
	 	this.old_sys_flag = newOld_sys_flag;
	} 	  
	/**
	 * 属性zyx13的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx13 () {
		return zyx13;
	}   
	/**
	 * 属性zyx13的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx13 String
	 */
	public void setZyx13 (String newZyx13 ) {
	 	this.zyx13 = newZyx13;
	} 	  
	/**
	 * 属性pjh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getPjh () {
		return pjh;
	}   
	/**
	 * 属性pjh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPjh String
	 */
	public void setPjh (String newPjh ) {
	 	this.pjh = newPjh;
	} 	  
	/**
	 * 属性xmbm2的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getXmbm2 () {
		return xmbm2;
	}   
	/**
	 * 属性xmbm2的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newXmbm2 String
	 */
	public void setXmbm2 (String newXmbm2 ) {
	 	this.xmbm2 = newXmbm2;
	} 	  
	/**
	 * 属性jsfsbm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getJsfsbm () {
		return jsfsbm;
	}   
	/**
	 * 属性jsfsbm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newJsfsbm String
	 */
	public void setJsfsbm (String newJsfsbm ) {
	 	this.jsfsbm = newJsfsbm;
	} 	  
	/**
	 * 属性kmbm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getKmbm () {
		return kmbm;
	}   
	/**
	 * 属性kmbm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newKmbm String
	 */
	public void setKmbm (String newKmbm ) {
	 	this.kmbm = newKmbm;
	} 	  
	/**
	 * 属性zyx1的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx1 () {
		return zyx1;
	}   
	/**
	 * 属性zyx1的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx1 String
	 */
	public void setZyx1 (String newZyx1 ) {
	 	this.zyx1 = newZyx1;
	} 	  
	/**
	 * 属性kslb的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public Integer getKslb () {
		return kslb;
	}   
	/**
	 * 属性kslb的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newKslb UFDouble
	 */
	public void setKslb (Integer newKslb ) {
	 	this.kslb = newKslb;
	} 	  
	/**
	 * 属性fbpjlx的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getFbpjlx () {
		return fbpjlx;
	}   
	/**
	 * 属性fbpjlx的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFbpjlx UFDouble
	 */
	public void setFbpjlx (UFDouble newFbpjlx ) {
	 	this.fbpjlx = newFbpjlx;
	} 	  
	/**
	 * 属性bjdwwsdj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getBjdwwsdj () {
		return bjdwwsdj;
	}   
	/**
	 * 属性bjdwwsdj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newBjdwwsdj UFDouble
	 */
	public void setBjdwwsdj (UFDouble newBjdwwsdj ) {
	 	this.bjdwwsdj = newBjdwwsdj;
	} 	  
	/**
	 * 属性djdl的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDjdl () {
		return djdl;
	}   
	/**
	 * 属性djdl的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDjdl String
	 */
	public void setDjdl (String newDjdl ) {
	 	this.djdl = newDjdl;
	} 	  
	/**
	 * 属性hsl的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getHsl () {
		return hsl;
	}   
	/**
	 * 属性hsl的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newHsl UFDouble
	 */
	public void setHsl (UFDouble newHsl ) {
	 	this.hsl = newHsl;
	} 	  
	/**
	 * 属性ckbm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getCkbm () {
		return ckbm;
	}   
	/**
	 * 属性ckbm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newCkbm String
	 */
	public void setCkbm (String newCkbm ) {
	 	this.ckbm = newCkbm;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2010-11-06 10:36:10
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "VOUCHID";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2010-11-06 10:36:10
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "fb_oid";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2010-11-06 10:36:10
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "arap_djfb";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2010-11-06 10:36:10
	  */
     public DJZBItemVO() {
		super();	
	}    
} 
