/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.gt.gs.gs24;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2011-11-14 10:12:22
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class ColumnShowVO extends SuperVO {
	private String pk_corp;
	private UFDateTime ts;
	private String vapprovednote;
	private String pk_productline;
	private String vunapproveid;
	private String vunapprovednote;
	private String vapproveid;
	private Integer vbillstatus;
	private String memo;
	private UFDate vapprovedate;
	private UFDate dmakedate;
	private String pk_columnshow;
	private Integer dr;
	private String pk_operator;
	private UFDate vunapprovedate;
	private String vbillcode;

	public static final String PK_CORP = "pk_corp";
	public static final String VAPPROVEDNOTE = "vapprovednote";
	public static final String PK_PRODUCTLINE = "pk_productline";
	public static final String VUNAPPROVEID = "vunapproveid";
	public static final String VUNAPPROVEDNOTE = "vunapprovednote";
	public static final String VAPPROVEID = "vapproveid";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String MEMO = "memo";
	public static final String VAPPROVEDATE = "vapprovedate";
	public static final String DMAKEDATE = "dmakedate";
	public static final String PK_COLUMNSHOW = "pk_columnshow";
	public static final String PK_OPERATOR = "pk_operator";
	public static final String VUNAPPROVEDATE = "vunapprovedate";
	public static final String VBILLCODE = "vbillcode";
			
	
	public String getVbillcode() {
		return vbillcode;
	}
	public void setVbillcode(String vbillcode) {
		this.vbillcode = vbillcode;
	}
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性vapprovednote的Getter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @return String
	 */
	public String getVapprovednote () {
		return vapprovednote;
	}   
	/**
	 * 属性vapprovednote的Setter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @param newVapprovednote String
	 */
	public void setVapprovednote (String newVapprovednote ) {
	 	this.vapprovednote = newVapprovednote;
	} 	  
	/**
	 * 属性pk_productline的Getter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @return String
	 */
	public String getPk_productline () {
		return pk_productline;
	}   
	/**
	 * 属性pk_productline的Setter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @param newPk_productline String
	 */
	public void setPk_productline (String newPk_productline ) {
	 	this.pk_productline = newPk_productline;
	} 	  
	/**
	 * 属性vunapproveid的Getter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @return String
	 */
	public String getVunapproveid () {
		return vunapproveid;
	}   
	/**
	 * 属性vunapproveid的Setter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @param newVunapproveid String
	 */
	public void setVunapproveid (String newVunapproveid ) {
	 	this.vunapproveid = newVunapproveid;
	} 	  
	/**
	 * 属性vunapprovednote的Getter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @return String
	 */
	public String getVunapprovednote () {
		return vunapprovednote;
	}   
	/**
	 * 属性vunapprovednote的Setter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @param newVunapprovednote String
	 */
	public void setVunapprovednote (String newVunapprovednote ) {
	 	this.vunapprovednote = newVunapprovednote;
	} 	  
	/**
	 * 属性vapproveid的Getter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @return String
	 */
	public String getVapproveid () {
		return vapproveid;
	}   
	/**
	 * 属性vapproveid的Setter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @param newVapproveid String
	 */
	public void setVapproveid (String newVapproveid ) {
	 	this.vapproveid = newVapproveid;
	} 	  
	/**
	 * 属性vbillstatus的Getter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @return UFDouble
	 */
	public Integer getVbillstatus () {
		return vbillstatus;
	}   
	/**
	 * 属性vbillstatus的Setter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @param newVbillstatus UFDouble
	 */
	public void setVbillstatus (Integer newVbillstatus ) {
	 	this.vbillstatus = newVbillstatus;
	} 	  
	/**
	 * 属性memo的Getter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @return String
	 */
	public String getMemo () {
		return memo;
	}   
	/**
	 * 属性memo的Setter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @param newMemo String
	 */
	public void setMemo (String newMemo ) {
	 	this.memo = newMemo;
	} 	  
	/**
	 * 属性vapprovedate的Getter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @return UFDateTime
	 */
	public UFDate getVapprovedate () {
		return vapprovedate;
	}   
	/**
	 * 属性vapprovedate的Setter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @param newVapprovedate UFDateTime
	 */
	public void setVapprovedate (UFDate newVapprovedate ) {
	 	this.vapprovedate = newVapprovedate;
	} 	  
	/**
	 * 属性dmakedate的Getter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @return UFDateTime
	 */
	public UFDate getDmakedate () {
		return dmakedate;
	}   
	/**
	 * 属性dmakedate的Setter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @param newDmakedate UFDateTime
	 */
	public void setDmakedate (UFDate newDmakedate ) {
	 	this.dmakedate = newDmakedate;
	} 	  
	/**
	 * 属性pk_columnshow的Getter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @return String
	 */
	public String getPk_columnshow () {
		return pk_columnshow;
	}   
	/**
	 * 属性pk_columnshow的Setter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @param newPk_columnshow String
	 */
	public void setPk_columnshow (String newPk_columnshow ) {
	 	this.pk_columnshow = newPk_columnshow;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性pk_operator的Getter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @return String
	 */
	public String getPk_operator () {
		return pk_operator;
	}   
	/**
	 * 属性pk_operator的Setter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @param newPk_operator String
	 */
	public void setPk_operator (String newPk_operator ) {
	 	this.pk_operator = newPk_operator;
	} 	  
	/**
	 * 属性vunapprovedate的Getter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @return UFDateTime
	 */
	public UFDate getVunapprovedate () {
		return vunapprovedate;
	}   
	/**
	 * 属性vunapprovedate的Setter方法.
	 * 创建日期:2011-11-14 10:12:22
	 * @param newVunapprovedate UFDateTime
	 */
	public void setVunapprovedate (UFDate newVunapprovedate ) {
	 	this.vunapprovedate = newVunapprovedate;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-11-14 10:12:22
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-11-14 10:12:22
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_columnshow";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2011-11-14 10:12:22
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "gt_columnshow";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-11-14 10:12:22
	  */
     public ColumnShowVO() {
		super();	
	}    
} 
