/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.jyglgt.arap;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2010-11-06 10:36:10
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class DJZBVO extends SuperVO {
	private UFDateTime ts;
	private String zyx30;
	private String zyx26;
	private String zyx12;
	private UFDate effectdate;
	private String zyx21;
	private String zyx3;
	private String zyx27;
	private String hzbz;
	private String zyx20;
	private UFDouble isselectedpay;
	private String lasttzr;
	private String sxkjqj;
	private String shr;
	private String ssbh;
	private String zyx4;
	private String zyx22;
	private String outbusitype;
	private String yhqrr;
	private String zyx25;
	private UFBoolean isreded;
	private UFDouble specflag;
	private String zyx23;
	private String vouchid;
	private UFDate inner_effect_date;
	private String zyx11;
	private String zyx16;
	private String enduser;
	private UFDate yhqrrq;
	private String zyx24;
	private String zyx5;
	private String zyx29;
	private UFDate shrq;
	private Integer lybz;
	private UFBoolean prepay;
	private String djbh;
	private String lastshr;
	private UFBoolean isnetready;
	private String xslxbm;
	private String djkjqj;
	private String djlxbm;
	private UFBoolean ispaid;
	private UFBoolean isonlinepay;
	private String shkjnd;
	private String sfkr;
	private String shkjqj;
	private String pj_num;
	private UFDouble fbje;
	private UFDate zdrq;
	private String zyx10;
	private String sxkjnd;
	private String officialprintuser;
	private UFDouble shzd;
	private String settlenum;
	private String dwbm;
	private String pj_jsfs;
	private UFDate sxrq;
	private String zyx19;
	private String scomment;
	private String ywbm;
	private String pj_oid;
	private String ddhbbm;
	private String zdr;
	private UFDate paydate;
	private String yhqrkjqj;
	private Integer djzt;
	private UFDouble bbje;
	private UFBoolean qcbz;
	private String zyx2;
	private UFBoolean isjszxzf;
	private UFDouble fj;
	private String payman;
	private String sxr;
	private UFDate dzrq;
	private Integer zgyf;
	private String yhqrkjnd;
	private String djkjnd;
	private String zyx17;
	private String zyx18;
	private String zyx8;
	private String zyx15;
	private String zyx14;
	private Integer pzglh;
	private UFDouble ybje;
	private String sscause;
	private UFDate officialprintdate;
	private Integer sxbz;
	private String zyx28;
	private String zyx9;
	private Integer zzzt;
	private String zyx13;
	private UFDate djrq;
	private String kmbm;
	private String qrr;
	private String fktjbm;
	private String spzt;
	private String zyx7;
	private String kskhyh;
	private String zyx1;
	private String lrr;
	private UFDouble jszxzf;
	private String zyx6;
	private  Integer dr;
	private String dyvouchid;
	private String djdl;

	public static final String ZYX30 = "zyx30";
	public static final String ZYX26 = "zyx26";
	public static final String ZYX12 = "zyx12";
	public static final String EFFECTDATE = "effectdate";
	public static final String ZYX21 = "zyx21";
	public static final String ZYX3 = "zyx3";
	public static final String ZYX27 = "zyx27";
	public static final String HZBZ = "hzbz";
	public static final String ZYX20 = "zyx20";
	public static final String ISSELECTEDPAY = "isselectedpay";
	public static final String LASTTZR = "lasttzr";
	public static final String SXKJQJ = "sxkjqj";
	public static final String SHR = "shr";
	public static final String SSBH = "ssbh";
	public static final String ZYX4 = "zyx4";
	public static final String ZYX22 = "zyx22";
	public static final String OUTBUSITYPE = "outbusitype";
	public static final String YHQRR = "yhqrr";
	public static final String ZYX25 = "zyx25";
	public static final String ISREDED = "isreded";
	public static final String SPECFLAG = "specflag";
	public static final String ZYX23 = "zyx23";
	public static final String VOUCHID = "vouchid";
	public static final String INNER_EFFECT_DATE = "inner_effect_date";
	public static final String ZYX11 = "zyx11";
	public static final String ZYX16 = "zyx16";
	public static final String ENDUSER = "enduser";
	public static final String YHQRRQ = "yhqrrq";
	public static final String ZYX24 = "zyx24";
	public static final String ZYX5 = "zyx5";
	public static final String ZYX29 = "zyx29";
	public static final String SHRQ = "shrq";
	public static final String LYBZ = "lybz";
	public static final String PREPAY = "prepay";
	public static final String DJBH = "djbh";
	public static final String LASTSHR = "lastshr";
	public static final String ISNETREADY = "isnetready";
	public static final String XSLXBM = "xslxbm";
	public static final String DJKJQJ = "djkjqj";
	public static final String DJLXBM = "djlxbm";
	public static final String ISPAID = "ispaid";
	public static final String ISONLINEPAY = "isonlinepay";
	public static final String SHKJND = "shkjnd";
	public static final String SFKR = "sfkr";
	public static final String SHKJQJ = "shkjqj";
	public static final String PJ_NUM = "pj_num";
	public static final String FBJE = "fbje";
	public static final String ZDRQ = "zdrq";
	public static final String ZYX10 = "zyx10";
	public static final String SXKJND = "sxkjnd";
	public static final String OFFICIALPRINTUSER = "officialprintuser";
	public static final String SHZD = "shzd";
	public static final String SETTLENUM = "settlenum";
	public static final String DWBM = "dwbm";
	public static final String PJ_JSFS = "pj_jsfs";
	public static final String SXRQ = "sxrq";
	public static final String ZYX19 = "zyx19";
	public static final String SCOMMENT = "scomment";
	public static final String YWBM = "ywbm";
	public static final String PJ_OID = "pj_oid";
	public static final String DDHBBM = "ddhbbm";
	public static final String ZDR = "zdr";
	public static final String PAYDATE = "paydate";
	public static final String YHQRKJQJ = "yhqrkjqj";
	public static final String DJZT = "djzt";
	public static final String BBJE = "bbje";
	public static final String QCBZ = "qcbz";
	public static final String ZYX2 = "zyx2";
	public static final String ISJSZXZF = "isjszxzf";
	public static final String FJ = "fj";
	public static final String PAYMAN = "payman";
	public static final String SXR = "sxr";
	public static final String DZRQ = "dzrq";
	public static final String ZGYF = "zgyf";
	public static final String YHQRKJND = "yhqrkjnd";
	public static final String DJKJND = "djkjnd";
	public static final String ZYX17 = "zyx17";
	public static final String ZYX18 = "zyx18";
	public static final String ZYX8 = "zyx8";
	public static final String ZYX15 = "zyx15";
	public static final String ZYX14 = "zyx14";
	public static final String PZGLH = "pzglh";
	public static final String YBJE = "ybje";
	public static final String SSCAUSE = "sscause";
	public static final String OFFICIALPRINTDATE = "officialprintdate";
	public static final String SXBZ = "sxbz";
	public static final String ZYX28 = "zyx28";
	public static final String ZYX9 = "zyx9";
	public static final String ZZZT = "zzzt";
	public static final String ZYX13 = "zyx13";
	public static final String DJRQ = "djrq";
	public static final String KMBM = "kmbm";
	public static final String QRR = "qrr";
	public static final String FKTJBM = "fktjbm";
	public static final String SPZT = "spzt";
	public static final String ZYX7 = "zyx7";
	public static final String KSKHYH = "kskhyh";
	public static final String ZYX1 = "zyx1";
	public static final String LRR = "lrr";
	public static final String JSZXZF = "jszxzf";
	public static final String ZYX6 = "zyx6";
	public static final String DYVOUCHID = "dyvouchid";
	public static final String DJDL = "djdl";
			
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性zyx30的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx30 () {
		return zyx30;
	}   
	/**
	 * 属性zyx30的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx30 String
	 */
	public void setZyx30 (String newZyx30 ) {
	 	this.zyx30 = newZyx30;
	} 	  
	/**
	 * 属性zyx26的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx26 () {
		return zyx26;
	}   
	/**
	 * 属性zyx26的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx26 String
	 */
	public void setZyx26 (String newZyx26 ) {
	 	this.zyx26 = newZyx26;
	} 	  
	/**
	 * 属性zyx12的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx12 () {
		return zyx12;
	}   
	/**
	 * 属性zyx12的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx12 String
	 */
	public void setZyx12 (String newZyx12 ) {
	 	this.zyx12 = newZyx12;
	} 	  
	/**
	 * 属性effectdate的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getEffectdate () {
		return effectdate;
	}   
	/**
	 * 属性effectdate的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newEffectdate UFDate
	 */
	public void setEffectdate (UFDate newEffectdate ) {
	 	this.effectdate = newEffectdate;
	} 	  
	/**
	 * 属性zyx21的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx21 () {
		return zyx21;
	}   
	/**
	 * 属性zyx21的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx21 String
	 */
	public void setZyx21 (String newZyx21 ) {
	 	this.zyx21 = newZyx21;
	} 	  
	/**
	 * 属性zyx3的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx3 () {
		return zyx3;
	}   
	/**
	 * 属性zyx3的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx3 String
	 */
	public void setZyx3 (String newZyx3 ) {
	 	this.zyx3 = newZyx3;
	} 	  
	/**
	 * 属性zyx27的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx27 () {
		return zyx27;
	}   
	/**
	 * 属性zyx27的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx27 String
	 */
	public void setZyx27 (String newZyx27 ) {
	 	this.zyx27 = newZyx27;
	} 	  
	/**
	 * 属性hzbz的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getHzbz () {
		return hzbz;
	}   
	/**
	 * 属性hzbz的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newHzbz String
	 */
	public void setHzbz (String newHzbz ) {
	 	this.hzbz = newHzbz;
	} 	  
	/**
	 * 属性zyx20的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx20 () {
		return zyx20;
	}   
	/**
	 * 属性zyx20的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx20 String
	 */
	public void setZyx20 (String newZyx20 ) {
	 	this.zyx20 = newZyx20;
	} 	  
	/**
	 * 属性isselectedpay的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getIsselectedpay () {
		return isselectedpay;
	}   
	/**
	 * 属性isselectedpay的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newIsselectedpay UFDouble
	 */
	public void setIsselectedpay (UFDouble newIsselectedpay ) {
	 	this.isselectedpay = newIsselectedpay;
	} 	  
	/**
	 * 属性lasttzr的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getLasttzr () {
		return lasttzr;
	}   
	/**
	 * 属性lasttzr的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newLasttzr String
	 */
	public void setLasttzr (String newLasttzr ) {
	 	this.lasttzr = newLasttzr;
	} 	  
	/**
	 * 属性sxkjqj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getSxkjqj () {
		return sxkjqj;
	}   
	/**
	 * 属性sxkjqj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSxkjqj String
	 */
	public void setSxkjqj (String newSxkjqj ) {
	 	this.sxkjqj = newSxkjqj;
	} 	  
	/**
	 * 属性shr的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getShr () {
		return shr;
	}   
	/**
	 * 属性shr的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newShr String
	 */
	public void setShr (String newShr ) {
	 	this.shr = newShr;
	} 	  
	/**
	 * 属性ssbh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getSsbh () {
		return ssbh;
	}   
	/**
	 * 属性ssbh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSsbh String
	 */
	public void setSsbh (String newSsbh ) {
	 	this.ssbh = newSsbh;
	} 	  
	/**
	 * 属性zyx4的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx4 () {
		return zyx4;
	}   
	/**
	 * 属性zyx4的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx4 String
	 */
	public void setZyx4 (String newZyx4 ) {
	 	this.zyx4 = newZyx4;
	} 	  
	/**
	 * 属性zyx22的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx22 () {
		return zyx22;
	}   
	/**
	 * 属性zyx22的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx22 String
	 */
	public void setZyx22 (String newZyx22 ) {
	 	this.zyx22 = newZyx22;
	} 	  
	/**
	 * 属性outbusitype的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getOutbusitype () {
		return outbusitype;
	}   
	/**
	 * 属性outbusitype的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newOutbusitype String
	 */
	public void setOutbusitype (String newOutbusitype ) {
	 	this.outbusitype = newOutbusitype;
	} 	  
	/**
	 * 属性yhqrr的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getYhqrr () {
		return yhqrr;
	}   
	/**
	 * 属性yhqrr的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newYhqrr String
	 */
	public void setYhqrr (String newYhqrr ) {
	 	this.yhqrr = newYhqrr;
	} 	  
	/**
	 * 属性zyx25的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx25 () {
		return zyx25;
	}   
	/**
	 * 属性zyx25的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx25 String
	 */
	public void setZyx25 (String newZyx25 ) {
	 	this.zyx25 = newZyx25;
	} 	  
	/**
	 * 属性isreded的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFBoolean
	 */
	public UFBoolean getIsreded () {
		return isreded;
	}   
	/**
	 * 属性isreded的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newIsreded UFBoolean
	 */
	public void setIsreded (UFBoolean newIsreded ) {
	 	this.isreded = newIsreded;
	} 	  
	/**
	 * 属性specflag的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getSpecflag () {
		return specflag;
	}   
	/**
	 * 属性specflag的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSpecflag UFDouble
	 */
	public void setSpecflag (UFDouble newSpecflag ) {
	 	this.specflag = newSpecflag;
	} 	  
	/**
	 * 属性zyx23的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx23 () {
		return zyx23;
	}   
	/**
	 * 属性zyx23的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx23 String
	 */
	public void setZyx23 (String newZyx23 ) {
	 	this.zyx23 = newZyx23;
	} 	  
	/**
	 * 属性vouchid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getVouchid () {
		return vouchid;
	}   
	/**
	 * 属性vouchid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newVouchid String
	 */
	public void setVouchid (String newVouchid ) {
	 	this.vouchid = newVouchid;
	} 	  
	/**
	 * 属性inner_effect_date的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getInner_effect_date () {
		return inner_effect_date;
	}   
	/**
	 * 属性inner_effect_date的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newInner_effect_date UFDate
	 */
	public void setInner_effect_date (UFDate newInner_effect_date ) {
	 	this.inner_effect_date = newInner_effect_date;
	} 	  
	/**
	 * 属性zyx11的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx11 () {
		return zyx11;
	}   
	/**
	 * 属性zyx11的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx11 String
	 */
	public void setZyx11 (String newZyx11 ) {
	 	this.zyx11 = newZyx11;
	} 	  
	/**
	 * 属性zyx16的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx16 () {
		return zyx16;
	}   
	/**
	 * 属性zyx16的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx16 String
	 */
	public void setZyx16 (String newZyx16 ) {
	 	this.zyx16 = newZyx16;
	} 	  
	/**
	 * 属性enduser的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getEnduser () {
		return enduser;
	}   
	/**
	 * 属性enduser的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newEnduser String
	 */
	public void setEnduser (String newEnduser ) {
	 	this.enduser = newEnduser;
	} 	  
	/**
	 * 属性yhqrrq的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getYhqrrq () {
		return yhqrrq;
	}   
	/**
	 * 属性yhqrrq的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newYhqrrq UFDate
	 */
	public void setYhqrrq (UFDate newYhqrrq ) {
	 	this.yhqrrq = newYhqrrq;
	} 	  
	/**
	 * 属性zyx24的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx24 () {
		return zyx24;
	}   
	/**
	 * 属性zyx24的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx24 String
	 */
	public void setZyx24 (String newZyx24 ) {
	 	this.zyx24 = newZyx24;
	} 	  
	/**
	 * 属性zyx5的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx5 () {
		return zyx5;
	}   
	/**
	 * 属性zyx5的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx5 String
	 */
	public void setZyx5 (String newZyx5 ) {
	 	this.zyx5 = newZyx5;
	} 	  
	/**
	 * 属性zyx29的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx29 () {
		return zyx29;
	}   
	/**
	 * 属性zyx29的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx29 String
	 */
	public void setZyx29 (String newZyx29 ) {
	 	this.zyx29 = newZyx29;
	} 	  
	/**
	 * 属性shrq的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getShrq () {
		return shrq;
	}   
	/**
	 * 属性shrq的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newShrq UFDate
	 */
	public void setShrq (UFDate newShrq ) {
	 	this.shrq = newShrq;
	} 	  
	/**
	 * 属性lybz的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public Integer getLybz () {
		return lybz;
	}   
	/**
	 * 属性lybz的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newLybz UFDouble
	 */
	public void setLybz (Integer newLybz ) {
	 	this.lybz = newLybz;
	} 	  
	/**
	 * 属性prepay的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFBoolean
	 */
	public UFBoolean getPrepay () {
		return prepay;
	}   
	/**
	 * 属性prepay的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPrepay UFBoolean
	 */
	public void setPrepay (UFBoolean newPrepay ) {
	 	this.prepay = newPrepay;
	} 	  
	/**
	 * 属性djbh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDjbh () {
		return djbh;
	}   
	/**
	 * 属性djbh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDjbh String
	 */
	public void setDjbh (String newDjbh ) {
	 	this.djbh = newDjbh;
	} 	  
	/**
	 * 属性lastshr的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getLastshr () {
		return lastshr;
	}   
	/**
	 * 属性lastshr的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newLastshr String
	 */
	public void setLastshr (String newLastshr ) {
	 	this.lastshr = newLastshr;
	} 	  
	/**
	 * 属性isnetready的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFBoolean
	 */
	public UFBoolean getIsnetready () {
		return isnetready;
	}   
	/**
	 * 属性isnetready的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newIsnetready UFBoolean
	 */
	public void setIsnetready (UFBoolean newIsnetready ) {
	 	this.isnetready = newIsnetready;
	} 	  
	/**
	 * 属性xslxbm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getXslxbm () {
		return xslxbm;
	}   
	/**
	 * 属性xslxbm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newXslxbm String
	 */
	public void setXslxbm (String newXslxbm ) {
	 	this.xslxbm = newXslxbm;
	} 	  
	/**
	 * 属性djkjqj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDjkjqj () {
		return djkjqj;
	}   
	/**
	 * 属性djkjqj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDjkjqj String
	 */
	public void setDjkjqj (String newDjkjqj ) {
	 	this.djkjqj = newDjkjqj;
	} 	  
	/**
	 * 属性djlxbm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDjlxbm () {
		return djlxbm;
	}   
	/**
	 * 属性djlxbm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDjlxbm String
	 */
	public void setDjlxbm (String newDjlxbm ) {
	 	this.djlxbm = newDjlxbm;
	} 	  
	/**
	 * 属性ispaid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFBoolean
	 */
	public UFBoolean getIspaid () {
		return ispaid;
	}   
	/**
	 * 属性ispaid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newIspaid UFBoolean
	 */
	public void setIspaid (UFBoolean newIspaid ) {
	 	this.ispaid = newIspaid;
	} 	  
	/**
	 * 属性isonlinepay的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFBoolean
	 */
	public UFBoolean getIsonlinepay () {
		return isonlinepay;
	}   
	/**
	 * 属性isonlinepay的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newIsonlinepay UFBoolean
	 */
	public void setIsonlinepay (UFBoolean newIsonlinepay ) {
	 	this.isonlinepay = newIsonlinepay;
	} 	  
	/**
	 * 属性shkjnd的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getShkjnd () {
		return shkjnd;
	}   
	/**
	 * 属性shkjnd的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newShkjnd String
	 */
	public void setShkjnd (String newShkjnd ) {
	 	this.shkjnd = newShkjnd;
	} 	  
	/**
	 * 属性sfkr的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getSfkr () {
		return sfkr;
	}   
	/**
	 * 属性sfkr的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSfkr String
	 */
	public void setSfkr (String newSfkr ) {
	 	this.sfkr = newSfkr;
	} 	  
	/**
	 * 属性shkjqj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getShkjqj () {
		return shkjqj;
	}   
	/**
	 * 属性shkjqj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newShkjqj String
	 */
	public void setShkjqj (String newShkjqj ) {
	 	this.shkjqj = newShkjqj;
	} 	  
	/**
	 * 属性pj_num的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getPj_num () {
		return pj_num;
	}   
	/**
	 * 属性pj_num的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPj_num String
	 */
	public void setPj_num (String newPj_num ) {
	 	this.pj_num = newPj_num;
	} 	  
	/**
	 * 属性fbje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getFbje () {
		return fbje;
	}   
	/**
	 * 属性fbje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFbje UFDouble
	 */
	public void setFbje (UFDouble newFbje ) {
	 	this.fbje = newFbje;
	} 	  
	/**
	 * 属性zdrq的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getZdrq () {
		return zdrq;
	}   
	/**
	 * 属性zdrq的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZdrq UFDate
	 */
	public void setZdrq (UFDate newZdrq ) {
	 	this.zdrq = newZdrq;
	} 	  
	/**
	 * 属性zyx10的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx10 () {
		return zyx10;
	}   
	/**
	 * 属性zyx10的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx10 String
	 */
	public void setZyx10 (String newZyx10 ) {
	 	this.zyx10 = newZyx10;
	} 	  
	/**
	 * 属性sxkjnd的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getSxkjnd () {
		return sxkjnd;
	}   
	/**
	 * 属性sxkjnd的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSxkjnd String
	 */
	public void setSxkjnd (String newSxkjnd ) {
	 	this.sxkjnd = newSxkjnd;
	} 	  
	/**
	 * 属性officialprintuser的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getOfficialprintuser () {
		return officialprintuser;
	}   
	/**
	 * 属性officialprintuser的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newOfficialprintuser String
	 */
	public void setOfficialprintuser (String newOfficialprintuser ) {
	 	this.officialprintuser = newOfficialprintuser;
	} 	  
	/**
	 * 属性shzd的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getShzd () {
		return shzd;
	}   
	/**
	 * 属性shzd的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newShzd UFDouble
	 */
	public void setShzd (UFDouble newShzd ) {
	 	this.shzd = newShzd;
	} 	  
	/**
	 * 属性settlenum的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getSettlenum () {
		return settlenum;
	}   
	/**
	 * 属性settlenum的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSettlenum String
	 */
	public void setSettlenum (String newSettlenum ) {
	 	this.settlenum = newSettlenum;
	} 	  
	/**
	 * 属性dwbm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDwbm () {
		return dwbm;
	}   
	/**
	 * 属性dwbm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDwbm String
	 */
	public void setDwbm (String newDwbm ) {
	 	this.dwbm = newDwbm;
	} 	  
	/**
	 * 属性pj_jsfs的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getPj_jsfs () {
		return pj_jsfs;
	}   
	/**
	 * 属性pj_jsfs的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPj_jsfs String
	 */
	public void setPj_jsfs (String newPj_jsfs ) {
	 	this.pj_jsfs = newPj_jsfs;
	} 	  
	/**
	 * 属性sxrq的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getSxrq () {
		return sxrq;
	}   
	/**
	 * 属性sxrq的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSxrq UFDate
	 */
	public void setSxrq (UFDate newSxrq ) {
	 	this.sxrq = newSxrq;
	} 	  
	/**
	 * 属性zyx19的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx19 () {
		return zyx19;
	}   
	/**
	 * 属性zyx19的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx19 String
	 */
	public void setZyx19 (String newZyx19 ) {
	 	this.zyx19 = newZyx19;
	} 	  
	/**
	 * 属性scomment的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getScomment () {
		return scomment;
	}   
	/**
	 * 属性scomment的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newScomment String
	 */
	public void setScomment (String newScomment ) {
	 	this.scomment = newScomment;
	} 	  
	/**
	 * 属性ywbm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getYwbm () {
		return ywbm;
	}   
	/**
	 * 属性ywbm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newYwbm String
	 */
	public void setYwbm (String newYwbm ) {
	 	this.ywbm = newYwbm;
	} 	  
	/**
	 * 属性pj_oid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getPj_oid () {
		return pj_oid;
	}   
	/**
	 * 属性pj_oid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPj_oid String
	 */
	public void setPj_oid (String newPj_oid ) {
	 	this.pj_oid = newPj_oid;
	} 	  
	/**
	 * 属性ddhbbm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDdhbbm () {
		return ddhbbm;
	}   
	/**
	 * 属性ddhbbm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDdhbbm String
	 */
	public void setDdhbbm (String newDdhbbm ) {
	 	this.ddhbbm = newDdhbbm;
	} 	  
	/**
	 * 属性zdr的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZdr () {
		return zdr;
	}   
	/**
	 * 属性zdr的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZdr String
	 */
	public void setZdr (String newZdr ) {
	 	this.zdr = newZdr;
	} 	  
	/**
	 * 属性paydate的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getPaydate () {
		return paydate;
	}   
	/**
	 * 属性paydate的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPaydate UFDate
	 */
	public void setPaydate (UFDate newPaydate ) {
	 	this.paydate = newPaydate;
	} 	  
	/**
	 * 属性yhqrkjqj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getYhqrkjqj () {
		return yhqrkjqj;
	}   
	/**
	 * 属性yhqrkjqj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newYhqrkjqj String
	 */
	public void setYhqrkjqj (String newYhqrkjqj ) {
	 	this.yhqrkjqj = newYhqrkjqj;
	} 	  
	/**
	 * 属性djzt的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	
	/**
	 * 属性bbje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getBbje () {
		return bbje;
	}   
	public Integer getDjzt() {
		return djzt;
	}
	public void setDjzt(Integer djzt) {
		this.djzt = djzt;
	}
	/**
	 * 属性bbje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newBbje UFDouble
	 */
	public void setBbje (UFDouble newBbje ) {
	 	this.bbje = newBbje;
	} 	  
	/**
	 * 属性qcbz的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFBoolean
	 */
	public UFBoolean getQcbz () {
		return qcbz;
	}   
	/**
	 * 属性qcbz的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newQcbz UFBoolean
	 */
	public void setQcbz (UFBoolean newQcbz ) {
	 	this.qcbz = newQcbz;
	} 	  
	/**
	 * 属性zyx2的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx2 () {
		return zyx2;
	}   
	/**
	 * 属性zyx2的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx2 String
	 */
	public void setZyx2 (String newZyx2 ) {
	 	this.zyx2 = newZyx2;
	} 	  
	/**
	 * 属性isjszxzf的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFBoolean
	 */
	public UFBoolean getIsjszxzf () {
		return isjszxzf;
	}   
	/**
	 * 属性isjszxzf的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newIsjszxzf UFBoolean
	 */
	public void setIsjszxzf (UFBoolean newIsjszxzf ) {
	 	this.isjszxzf = newIsjszxzf;
	} 	  
	/**
	 * 属性fj的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getFj () {
		return fj;
	}   
	/**
	 * 属性fj的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFj UFDouble
	 */
	public void setFj (UFDouble newFj ) {
	 	this.fj = newFj;
	} 	  
	/**
	 * 属性payman的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getPayman () {
		return payman;
	}   
	/**
	 * 属性payman的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPayman String
	 */
	public void setPayman (String newPayman ) {
	 	this.payman = newPayman;
	} 	  
	/**
	 * 属性sxr的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getSxr () {
		return sxr;
	}   
	/**
	 * 属性sxr的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSxr String
	 */
	public void setSxr (String newSxr ) {
	 	this.sxr = newSxr;
	} 	  
	/**
	 * 属性dzrq的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getDzrq () {
		return dzrq;
	}   
	/**
	 * 属性dzrq的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDzrq UFDate
	 */
	public void setDzrq (UFDate newDzrq ) {
	 	this.dzrq = newDzrq;
	} 	  
	/**
	 * 属性zgyf的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public Integer getZgyf () {
		return zgyf;
	}   
	/**
	 * 属性zgyf的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZgyf UFDouble
	 */
	public void setZgyf (Integer newZgyf ) {
	 	this.zgyf = newZgyf;
	} 	  
	/**
	 * 属性yhqrkjnd的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getYhqrkjnd () {
		return yhqrkjnd;
	}   
	/**
	 * 属性yhqrkjnd的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newYhqrkjnd String
	 */
	public void setYhqrkjnd (String newYhqrkjnd ) {
	 	this.yhqrkjnd = newYhqrkjnd;
	} 	  
	/**
	 * 属性djkjnd的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDjkjnd () {
		return djkjnd;
	}   
	/**
	 * 属性djkjnd的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDjkjnd String
	 */
	public void setDjkjnd (String newDjkjnd ) {
	 	this.djkjnd = newDjkjnd;
	} 	  
	/**
	 * 属性zyx17的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx17 () {
		return zyx17;
	}   
	/**
	 * 属性zyx17的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx17 String
	 */
	public void setZyx17 (String newZyx17 ) {
	 	this.zyx17 = newZyx17;
	} 	  
	/**
	 * 属性zyx18的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx18 () {
		return zyx18;
	}   
	/**
	 * 属性zyx18的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx18 String
	 */
	public void setZyx18 (String newZyx18 ) {
	 	this.zyx18 = newZyx18;
	} 	  
	/**
	 * 属性zyx8的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx8 () {
		return zyx8;
	}   
	/**
	 * 属性zyx8的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx8 String
	 */
	public void setZyx8 (String newZyx8 ) {
	 	this.zyx8 = newZyx8;
	} 	  
	/**
	 * 属性zyx15的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx15 () {
		return zyx15;
	}   
	/**
	 * 属性zyx15的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx15 String
	 */
	public void setZyx15 (String newZyx15 ) {
	 	this.zyx15 = newZyx15;
	} 	  
	/**
	 * 属性zyx14的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx14 () {
		return zyx14;
	}   
	/**
	 * 属性zyx14的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx14 String
	 */
	public void setZyx14 (String newZyx14 ) {
	 	this.zyx14 = newZyx14;
	} 	  
	/**
	 * 属性pzglh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public Integer getPzglh () {
		return pzglh;
	}   
	/**
	 * 属性pzglh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newPzglh UFDouble
	 */
	public void setPzglh (Integer newPzglh ) {
	 	this.pzglh = newPzglh;
	} 	  
	/**
	 * 属性ybje的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getYbje () {
		return ybje;
	}   
	/**
	 * 属性ybje的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newYbje UFDouble
	 */
	public void setYbje (UFDouble newYbje ) {
	 	this.ybje = newYbje;
	} 	  
	/**
	 * 属性sscause的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getSscause () {
		return sscause;
	}   
	/**
	 * 属性sscause的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSscause String
	 */
	public void setSscause (String newSscause ) {
	 	this.sscause = newSscause;
	} 	  
	/**
	 * 属性officialprintdate的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getOfficialprintdate () {
		return officialprintdate;
	}   
	/**
	 * 属性officialprintdate的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newOfficialprintdate UFDate
	 */
	public void setOfficialprintdate (UFDate newOfficialprintdate ) {
	 	this.officialprintdate = newOfficialprintdate;
	} 	  
	/**
	 * 属性sxbz的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public Integer getSxbz () {
		return sxbz;
	}   
	/**
	 * 属性sxbz的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSxbz UFDouble
	 */
	public void setSxbz (Integer newSxbz ) {
	 	this.sxbz = newSxbz;
	} 	  
	/**
	 * 属性zyx28的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx28 () {
		return zyx28;
	}   
	/**
	 * 属性zyx28的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx28 String
	 */
	public void setZyx28 (String newZyx28 ) {
	 	this.zyx28 = newZyx28;
	} 	  
	/**
	 * 属性zyx9的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx9 () {
		return zyx9;
	}   
	/**
	 * 属性zyx9的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx9 String
	 */
	public void setZyx9 (String newZyx9 ) {
	 	this.zyx9 = newZyx9;
	} 	  
	/**
	 * 属性zzzt的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public Integer getZzzt () {
		return zzzt;
	}   
	/**
	 * 属性zzzt的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZzzt UFDouble
	 */
	public void setZzzt (Integer newZzzt ) {
	 	this.zzzt = newZzzt;
	} 	  
	/**
	 * 属性zyx13的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx13 () {
		return zyx13;
	}   
	/**
	 * 属性zyx13的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx13 String
	 */
	public void setZyx13 (String newZyx13 ) {
	 	this.zyx13 = newZyx13;
	} 	  
	/**
	 * 属性djrq的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDate
	 */
	public UFDate getDjrq () {
		return djrq;
	}   
	/**
	 * 属性djrq的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDjrq UFDate
	 */
	public void setDjrq (UFDate newDjrq ) {
	 	this.djrq = newDjrq;
	} 	  
	/**
	 * 属性kmbm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getKmbm () {
		return kmbm;
	}   
	/**
	 * 属性kmbm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newKmbm String
	 */
	public void setKmbm (String newKmbm ) {
	 	this.kmbm = newKmbm;
	} 	  
	/**
	 * 属性qrr的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getQrr () {
		return qrr;
	}   
	/**
	 * 属性qrr的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newQrr String
	 */
	public void setQrr (String newQrr ) {
	 	this.qrr = newQrr;
	} 	  
	/**
	 * 属性fktjbm的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getFktjbm () {
		return fktjbm;
	}   
	/**
	 * 属性fktjbm的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newFktjbm String
	 */
	public void setFktjbm (String newFktjbm ) {
	 	this.fktjbm = newFktjbm;
	} 	  
	/**
	 * 属性spzt的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getSpzt () {
		return spzt;
	}   
	/**
	 * 属性spzt的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newSpzt String
	 */
	public void setSpzt (String newSpzt ) {
	 	this.spzt = newSpzt;
	} 	  
	/**
	 * 属性zyx7的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx7 () {
		return zyx7;
	}   
	/**
	 * 属性zyx7的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx7 String
	 */
	public void setZyx7 (String newZyx7 ) {
	 	this.zyx7 = newZyx7;
	} 	  
	/**
	 * 属性kskhyh的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getKskhyh () {
		return kskhyh;
	}   
	/**
	 * 属性kskhyh的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newKskhyh String
	 */
	public void setKskhyh (String newKskhyh ) {
	 	this.kskhyh = newKskhyh;
	} 	  
	/**
	 * 属性zyx1的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx1 () {
		return zyx1;
	}   
	/**
	 * 属性zyx1的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx1 String
	 */
	public void setZyx1 (String newZyx1 ) {
	 	this.zyx1 = newZyx1;
	} 	  
	/**
	 * 属性lrr的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getLrr () {
		return lrr;
	}   
	/**
	 * 属性lrr的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newLrr String
	 */
	public void setLrr (String newLrr ) {
	 	this.lrr = newLrr;
	} 	  
	/**
	 * 属性jszxzf的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public UFDouble getJszxzf () {
		return jszxzf;
	}   
	/**
	 * 属性jszxzf的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newJszxzf UFDouble
	 */
	public void setJszxzf (UFDouble newJszxzf ) {
	 	this.jszxzf = newJszxzf;
	} 	  
	/**
	 * 属性zyx6的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getZyx6 () {
		return zyx6;
	}   
	/**
	 * 属性zyx6的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newZyx6 String
	 */
	public void setZyx6 (String newZyx6 ) {
	 	this.zyx6 = newZyx6;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性dyvouchid的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDyvouchid () {
		return dyvouchid;
	}   
	/**
	 * 属性dyvouchid的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDyvouchid String
	 */
	public void setDyvouchid (String newDyvouchid ) {
	 	this.dyvouchid = newDyvouchid;
	} 	  
	/**
	 * 属性djdl的Getter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @return String
	 */
	public String getDjdl () {
		return djdl;
	}   
	/**
	 * 属性djdl的Setter方法.
	 * 创建日期:2010-11-06 10:36:10
	 * @param newDjdl String
	 */
	public void setDjdl (String newDjdl ) {
	 	this.djdl = newDjdl;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2010-11-06 10:36:10
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2010-11-06 10:36:10
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "vouchid";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2010-11-06 10:36:10
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "arap_djzb";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2010-11-06 10:36:10
	  */
     public DJZBVO() {
		super();	
	}    
} 
