/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.jyglgt.j400680;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2011-06-14 19:57:51
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class BalanceWayVO extends SuperVO {
	private String pk_corp;
	private UFDateTime ts;
	private String balancecode;
	private String pk_balanceway;
	private UFBoolean balancestatus;
	private Integer dr;
	private String balancename;

	public static final String PK_CORP = "pk_corp";
	public static final String BALANCECODE = "balancecode";
	public static final String PK_BALANCEWAY = "pk_balanceway";
	public static final String BALANCESTATUS = "balancestatus";
	public static final String BALANCENAME = "balancename";
			
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2011-06-14 19:57:51
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2011-06-14 19:57:51
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2011-06-14 19:57:51
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2011-06-14 19:57:51
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性balancecode的Getter方法.
	 * 创建日期:2011-06-14 19:57:51
	 * @return String
	 */
	public String getBalancecode () {
		return balancecode;
	}   
	/**
	 * 属性balancecode的Setter方法.
	 * 创建日期:2011-06-14 19:57:51
	 * @param newBalancecode String
	 */
	public void setBalancecode (String newBalancecode ) {
	 	this.balancecode = newBalancecode;
	} 	  
	/**
	 * 属性pk_balanceway的Getter方法.
	 * 创建日期:2011-06-14 19:57:51
	 * @return String
	 */
	public String getPk_balanceway () {
		return pk_balanceway;
	}   
	/**
	 * 属性pk_balanceway的Setter方法.
	 * 创建日期:2011-06-14 19:57:51
	 * @param newPk_balanceway String
	 */
	public void setPk_balanceway (String newPk_balanceway ) {
	 	this.pk_balanceway = newPk_balanceway;
	} 	  
	/**
	 * 属性balancestatus的Getter方法.
	 * 创建日期:2011-06-14 19:57:51
	 * @return UFBoolean
	 */
	public UFBoolean getBalancestatus () {
		return balancestatus;
	}   
	/**
	 * 属性balancestatus的Setter方法.
	 * 创建日期:2011-06-14 19:57:51
	 * @param newBalancestatus UFBoolean
	 */
	public void setBalancestatus (UFBoolean newBalancestatus ) {
	 	this.balancestatus = newBalancestatus;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2011-06-14 19:57:51
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2011-06-14 19:57:51
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性balancename的Getter方法.
	 * 创建日期:2011-06-14 19:57:51
	 * @return String
	 */
	public String getBalancename () {
		return balancename;
	}   
	/**
	 * 属性balancename的Setter方法.
	 * 创建日期:2011-06-14 19:57:51
	 * @param newBalancename String
	 */
	public void setBalancename (String newBalancename ) {
	 	this.balancename = newBalancename;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-06-14 19:57:51
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-06-14 19:57:51
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_balanceway";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2011-06-14 19:57:51
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "gt_balanceway";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-06-14 19:57:51
	  */
     public BalanceWayVO() {
		super();	
	}    
} 
