/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.jyglgt.j400680;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2011-06-14 09:08:52
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class CreditBVO extends SuperVO {
	private String pk_corp;
	private UFDateTime ts;
	private String pk_basinfo;
	private String paybankacc;
	private UFDouble vdef9;
	private String vdef17;
	private String vdef20;
	private UFDate invoicedate;
	private UFDouble vdef1;
	private UFDouble vdef8;
	private UFDouble vdef10;
	private String paybank;
	private String fbmbilltype;
	private String vdef15;
	private String receivebankacc;
	private String vdef14;
	private String pk_credit_b;
	private UFDouble vdef7;
	private String vdef13;
	private UFDate gatherdate;
	private String pk_credit;
	private String receivebank;
	private UFDouble vdef2;
	private String vdef16;
	private UFDate enddate;
	private UFDouble vdef5;
	private String payunit;
	private String vdef11;
	private String vdef19;
	private String memo;
	private UFDouble vdef3;
	private String vdef12;
	private UFDouble vdef6;
	private UFDouble moneyy;
	private Integer dr;
	private UFDouble vdef4;
	private String vdef18;
	private String receiveunit;
	private String paybillunit;

	public static final String PK_CORP = "pk_corp";
	public static final String PK_BASINFO = "pk_basinfo";
	public static final String PAYBANKACC = "paybankacc";
	public static final String VDEF9 = "vdef9";
	public static final String VDEF17 = "vdef17";
	public static final String VDEF20 = "vdef20";
	public static final String INVOICEDATE = "invoicedate";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF8 = "vdef8";
	public static final String VDEF10 = "vdef10";
	public static final String PAYBANK = "paybank";
	public static final String FBMBILLTYPE = "fbmbilltype";
	public static final String VDEF15 = "vdef15";
	public static final String RECEIVEBANKACC = "receivebankacc";
	public static final String VDEF14 = "vdef14";
	public static final String PK_CREDIT_B = "pk_credit_b";
	public static final String VDEF7 = "vdef7";
	public static final String VDEF13 = "vdef13";
	public static final String GATHERDATE = "gatherdate";
	public static final String PK_CREDIT = "pk_credit";
	public static final String RECEIVEBANK = "receivebank";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF16 = "vdef16";
	public static final String ENDDATE = "enddate";
	public static final String VDEF5 = "vdef5";
	public static final String PAYUNIT = "payunit";
	public static final String VDEF11 = "vdef11";
	public static final String VDEF19 = "vdef19";
	public static final String MEMO = "memo";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF12 = "vdef12";
	public static final String VDEF6 = "vdef6";
	public static final String MONEYY = "moneyy";
	public static final String VDEF4 = "vdef4";
	public static final String VDEF18 = "vdef18";
	public static final String RECEIVEUNIT = "receiveunit";
	public static final String PAYBILLUNTI = "paybillunit";
			
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性pk_basinfo的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getPk_basinfo () {
		return pk_basinfo;
	}   
	/**
	 * 属性pk_basinfo的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newPk_basinfo String
	 */
	public void setPk_basinfo (String newPk_basinfo ) {
	 	this.pk_basinfo = newPk_basinfo;
	} 	  
	/**
	 * 属性paybankacc的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getPaybankacc () {
		return paybankacc;
	}   
	/**
	 * 属性paybankacc的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newPaybankacc String
	 */
	public void setPaybankacc (String newPaybankacc ) {
	 	this.paybankacc = newPaybankacc;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return UFDouble
	 */
	public UFDouble getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef9 UFDouble
	 */
	public void setVdef9 (UFDouble newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性vdef17的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getVdef17 () {
		return vdef17;
	}   
	/**
	 * 属性vdef17的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef17 String
	 */
	public void setVdef17 (String newVdef17 ) {
	 	this.vdef17 = newVdef17;
	} 	  
	/**
	 * 属性vdef20的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getVdef20 () {
		return vdef20;
	}   
	/**
	 * 属性vdef20的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef20 String
	 */
	public void setVdef20 (String newVdef20 ) {
	 	this.vdef20 = newVdef20;
	} 	  
	/**
	 * 属性invoicedate的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return UFDouble
	 */
	public UFDate getInvoicedate () {
		return invoicedate;
	}   
	/**
	 * 属性invoicedate的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newInvoicedate UFDouble
	 */
	public void setInvoicedate (UFDate newInvoicedate ) {
	 	this.invoicedate = newInvoicedate;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return UFDouble
	 */
	public UFDouble getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef1 UFDouble
	 */
	public void setVdef1 (UFDouble newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return UFDouble
	 */
	public UFDouble getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef8 UFDouble
	 */
	public void setVdef8 (UFDouble newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return UFDouble
	 */
	public UFDouble getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef10 UFDouble
	 */
	public void setVdef10 (UFDouble newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
	/**
	 * 属性paybank的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getPaybank () {
		return paybank;
	}   
	/**
	 * 属性paybank的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newPaybank String
	 */
	public void setPaybank (String newPaybank ) {
	 	this.paybank = newPaybank;
	} 	  
	/**
	 * 属性fbmbilltype的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getFbmbilltype () {
		return fbmbilltype;
	}   
	/**
	 * 属性fbmbilltype的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newFbmbilltype String
	 */
	public void setFbmbilltype (String newFbmbilltype ) {
	 	this.fbmbilltype = newFbmbilltype;
	} 	  
	/**
	 * 属性vdef15的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getVdef15 () {
		return vdef15;
	}   
	/**
	 * 属性vdef15的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef15 String
	 */
	public void setVdef15 (String newVdef15 ) {
	 	this.vdef15 = newVdef15;
	} 	  
	/**
	 * 属性receivebankacc的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getReceivebankacc () {
		return receivebankacc;
	}   
	/**
	 * 属性receivebankacc的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newReceivebankacc String
	 */
	public void setReceivebankacc (String newReceivebankacc ) {
	 	this.receivebankacc = newReceivebankacc;
	} 	  
	/**
	 * 属性vdef14的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getVdef14 () {
		return vdef14;
	}   
	/**
	 * 属性vdef14的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef14 String
	 */
	public void setVdef14 (String newVdef14 ) {
	 	this.vdef14 = newVdef14;
	} 	  
	/**
	 * 属性pk_credit_b的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getPk_credit_b () {
		return pk_credit_b;
	}   
	/**
	 * 属性pk_credit_b的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newPk_credit_b String
	 */
	public void setPk_credit_b (String newPk_credit_b ) {
	 	this.pk_credit_b = newPk_credit_b;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return UFDouble
	 */
	public UFDouble getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef7 UFDouble
	 */
	public void setVdef7 (UFDouble newVdef7 ) {
	 	this.vdef7 = newVdef7;
	} 	  
	/**
	 * 属性vdef13的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getVdef13 () {
		return vdef13;
	}   
	/**
	 * 属性vdef13的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef13 String
	 */
	public void setVdef13 (String newVdef13 ) {
	 	this.vdef13 = newVdef13;
	} 	  
	/**
	 * 属性gatherdate的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public UFDate getGatherdate () {
		return gatherdate;
	}   
	/**
	 * 属性gatherdate的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newGatherdate String
	 */
	public void setGatherdate (UFDate newGatherdate ) {
	 	this.gatherdate = newGatherdate;
	} 	  
	/**
	 * 属性pk_credit的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getPk_credit () {
		return pk_credit;
	}   
	/**
	 * 属性pk_credit的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newPk_credit String
	 */
	public void setPk_credit (String newPk_credit ) {
	 	this.pk_credit = newPk_credit;
	} 	  
	/**
	 * 属性receivebank的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getReceivebank () {
		return receivebank;
	}   
	/**
	 * 属性receivebank的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newReceivebank String
	 */
	public void setReceivebank (String newReceivebank ) {
	 	this.receivebank = newReceivebank;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return UFDouble
	 */
	public UFDouble getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef2 UFDouble
	 */
	public void setVdef2 (UFDouble newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef16的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getVdef16 () {
		return vdef16;
	}   
	/**
	 * 属性vdef16的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef16 String
	 */
	public void setVdef16 (String newVdef16 ) {
	 	this.vdef16 = newVdef16;
	} 	  
	/**
	 * 属性enddate的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return UFDouble
	 */
	public UFDate getEnddate () {
		return enddate;
	}   
	/**
	 * 属性enddate的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newEnddate UFDouble
	 */
	public void setEnddate (UFDate newEnddate ) {
	 	this.enddate = newEnddate;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return UFDouble
	 */
	public UFDouble getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef5 UFDouble
	 */
	public void setVdef5 (UFDouble newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性payunit的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getPayunit () {
		return payunit;
	}   
	/**
	 * 属性payunit的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newPayunit String
	 */
	public void setPayunit (String newPayunit ) {
	 	this.payunit = newPayunit;
	} 	  
	/**
	 * 属性vdef11的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getVdef11 () {
		return vdef11;
	}   
	/**
	 * 属性vdef11的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef11 String
	 */
	public void setVdef11 (String newVdef11 ) {
	 	this.vdef11 = newVdef11;
	} 	  
	/**
	 * 属性vdef19的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getVdef19 () {
		return vdef19;
	}   
	/**
	 * 属性vdef19的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef19 String
	 */
	public void setVdef19 (String newVdef19 ) {
	 	this.vdef19 = newVdef19;
	} 	  
	/**
	 * 属性memo的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getMemo () {
		return memo;
	}   
	/**
	 * 属性memo的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newMemo String
	 */
	public void setMemo (String newMemo ) {
	 	this.memo = newMemo;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return UFDouble
	 */
	public UFDouble getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef3 UFDouble
	 */
	public void setVdef3 (UFDouble newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef12的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getVdef12 () {
		return vdef12;
	}   
	/**
	 * 属性vdef12的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef12 String
	 */
	public void setVdef12 (String newVdef12 ) {
	 	this.vdef12 = newVdef12;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return UFDouble
	 */
	public UFDouble getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef6 UFDouble
	 */
	public void setVdef6 (UFDouble newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性moneyy的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return UFDouble
	 */
	public UFDouble getMoneyy () {
		return moneyy;
	}   
	/**
	 * 属性moneyy的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newMoneyy UFDouble
	 */
	public void setMoneyy (UFDouble newMoneyy ) {
	 	this.moneyy = newMoneyy;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return UFDouble
	 */
	public UFDouble getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef4 UFDouble
	 */
	public void setVdef4 (UFDouble newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性vdef18的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getVdef18 () {
		return vdef18;
	}   
	/**
	 * 属性vdef18的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newVdef18 String
	 */
	public void setVdef18 (String newVdef18 ) {
	 	this.vdef18 = newVdef18;
	} 	  
	/**
	 * 属性receiveunit的Getter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @return String
	 */
	public String getReceiveunit () {
		return receiveunit;
	}   
	/**
	 * 属性receiveunit的Setter方法.
	 * 创建日期:2011-06-14 09:08:52
	 * @param newReceiveunit String
	 */
	public void setReceiveunit (String newReceiveunit ) {
	 	this.receiveunit = newReceiveunit;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-06-14 09:08:52
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_credit";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-06-14 09:08:52
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_credit_b";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2011-06-14 09:08:52
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "gt_credit_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-06-14 09:08:52
	  */
     public CreditBVO() {
		super();	
	}
	public void setPaybillunit(String paybillunit) {
		this.paybillunit = paybillunit;
	}
	public String getPaybillunit() {
		return paybillunit;
	}    
} 
