/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.jyglgt.j400670;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2011-11-12 09:51:36
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class PricePolicybVO extends SuperVO {
	private String pk_corp;
	private UFDateTime ts;
	private UFDouble vdef9;
	private String pk_level;
	private String free7;
	private UFDouble vdef10;
	private UFDouble hsprice;
	private String vdef15;
	private String vdef14;
	private String free5;
	private Integer free1_2;
	private String free10;
	private UFDouble vdef7;
	private String pk_pricepolicy_b;
	private String free6;
	private String free2_1;
	private String pk_free2_1;
	private String pk_productline;
	private String vdef16;
	private UFDouble vdef2;
	private UFDouble vdef5;
	private String vdef19;
	private String memo;
	private String free9;
	private String vdef18;
	private UFDouble vdef4;
	private String free3_1;
	private String pk_free3_1;
	private String vdef17;
	private UFDouble vdef1;
	private String vdef20;
	private UFDouble vdef8;
	private String free8;
	private String free2_0;
	private String pk_free2_0;
	private String pk_zkway;
	private String pk_pricepolicy;
	private Integer free4_2;
	private String free1_0;
	private String free1_1;
	private String free4_0;
	private String pk_free1_0;
	private String pk_free1_1;
	private String pk_free4_0;
	private String vdef13;
	private Integer free3_2;
	private String pk_deliveryplan_b;
	private String vdef11;
	private Integer free2_2;
	private String free3_0;
	private String pk_free3_0;
	private String vdef12;
	private UFDouble vdef3;
	private UFDouble vdef6;
	private Integer dr;
	private String pk_invmandoc;
	private String free4_1;
	private String pk_free4_1;
	private String list1_0;
	private String list1_1;
	private String list2_0;
	private String list2_1;
	private String list3_0;
	private String list3_1;
	private String list4_0;
	private String list4_1;

	public static final String LIST1_0 = "list1_0";
	public static final String LIST1_1 = "list1_1";
	public static final String LIST2_0 = "list2_0";
	public static final String LIST2_1 = "list2_1";
	public static final String LIST3_0 = "list3_0";
	public static final String LIST3_1 = "list3_1";
	public static final String LIST4_0 = "list4_0";
	public static final String LIST4_1 = "list4_1";
	public static final String PK_CORP = "pk_corp";
	public static final String VDEF9 = "vdef9";
	public static final String PK_LEVEL = "pk_level";
	public static final String FREE7 = "free7";
	public static final String VDEF10 = "vdef10";
	public static final String HSPRICE = "hsprice";
	public static final String VDEF15 = "vdef15";
	public static final String VDEF14 = "vdef14";
	public static final String FREE5 = "free5";
	public static final String FREE1_2 = "free1_2";
	public static final String FREE10 = "free10";
	public static final String VDEF7 = "vdef7";
	public static final String PK_PRICEPOLICY_B = "pk_pricepolicy_b";
	public static final String FREE6 = "free6";
	public static final String FREE2_1 = "free2_1";
	public static final String PK_FREE2_1 = "pk_free2_1";
	public static final String PK_PRODUCTLINE = "pk_productline";
	public static final String VDEF16 = "vdef16";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF5 = "vdef5";
	public static final String VDEF19 = "vdef19";
	public static final String MEMO = "memo";
	public static final String FREE9 = "free9";
	public static final String VDEF18 = "vdef18";
	public static final String VDEF4 = "vdef4";
	public static final String FREE3_1 = "free3_1";
	public static final String PK_FREE3_1 = "pk_free3_1";
	public static final String VDEF17 = "vdef17";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF20 = "vdef20";
	public static final String VDEF8 = "vdef8";
	public static final String FREE8 = "free8";
	public static final String FREE2_0 = "free2_0";
	public static final String PK_FREE2_0 = "pk_free2_0";
	public static final String PK_ZKWAY = "pk_zkway";
	public static final String PK_PRICEPOLICY = "pk_pricepolicy";
	public static final String FREE4_2 = "free4_2";
	public static final String FREE1_0 = "free1_0";
	public static final String FREE1_1 = "free1_1";
	public static final String FREE4_0 = "free4_0";
	public static final String PK_FREE1_0 = "pk_free1_0";
	public static final String PK_FREE1_1 = "pk_free1_1";
	public static final String PK_FREE4_0 = "pk_free4_0";
	public static final String VDEF13 = "vdef13";
	public static final String FREE3_2 = "free3_2";
	public static final String PK_DELIVERYPLAN_B = "pk_deliveryplan_b";
	public static final String VDEF11 = "vdef11";
	public static final String FREE2_2 = "free2_2";
	public static final String FREE3_0 = "free3_0";
	public static final String PK_FREE3_0 = "pk_free3_0";
	public static final String VDEF12 = "vdef12";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF6 = "vdef6";
	public static final String PK_INVMANDOC = "pk_invmandoc";
	public static final String FREE4_1 = "free4_1";
	public static final String PK_FREE4_1 = "pk_free4_1";
			
	
	public String getList1_0() {
		return list1_0;
	}
	public void setList1_0(String list1_0) {
		this.list1_0 = list1_0;
	}
	public String getList1_1() {
		return list1_1;
	}
	public void setList1_1(String list1_1) {
		this.list1_1 = list1_1;
	}
	public String getList2_0() {
		return list2_0;
	}
	public void setList2_0(String list2_0) {
		this.list2_0 = list2_0;
	}
	public String getList2_1() {
		return list2_1;
	}
	public void setList2_1(String list2_1) {
		this.list2_1 = list2_1;
	}
	public String getList3_0() {
		return list3_0;
	}
	public void setList3_0(String list3_0) {
		this.list3_0 = list3_0;
	}
	public String getList3_1() {
		return list3_1;
	}
	public void setList3_1(String list3_1) {
		this.list3_1 = list3_1;
	}
	public String getList4_0() {
		return list4_0;
	}
	public void setList4_0(String list4_0) {
		this.list4_0 = list4_0;
	}
	public String getList4_1() {
		return list4_1;
	}
	public void setList4_1(String list4_1) {
		this.list4_1 = list4_1;
	}
	public String getPk_free2_1() {
		return pk_free2_1;
	}
	public void setPk_free2_1(String pk_free2_1) {
		this.pk_free2_1 = pk_free2_1;
	}
	public String getPk_free3_1() {
		return pk_free3_1;
	}
	public void setPk_free3_1(String pk_free3_1) {
		this.pk_free3_1 = pk_free3_1;
	}
	public String getPk_free2_0() {
		return pk_free2_0;
	}
	public void setPk_free2_0(String pk_free2_0) {
		this.pk_free2_0 = pk_free2_0;
	}
	public String getPk_free1_0() {
		return pk_free1_0;
	}
	public void setPk_free1_0(String pk_free1_0) {
		this.pk_free1_0 = pk_free1_0;
	}
	public String getPk_free1_1() {
		return pk_free1_1;
	}
	public void setPk_free1_1(String pk_free1_1) {
		this.pk_free1_1 = pk_free1_1;
	}
	public String getPk_free4_0() {
		return pk_free4_0;
	}
	public void setPk_free4_0(String pk_free4_0) {
		this.pk_free4_0 = pk_free4_0;
	}
	public String getPk_free3_0() {
		return pk_free3_0;
	}
	public void setPk_free3_0(String pk_free3_0) {
		this.pk_free3_0 = pk_free3_0;
	}
	public String getPk_free4_1() {
		return pk_free4_1;
	}
	public void setPk_free4_1(String pk_free4_1) {
		this.pk_free4_1 = pk_free4_1;
	}
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef9 UFDouble
	 */
	public void setVdef9 (UFDouble newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性pk_level的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getPk_level () {
		return pk_level;
	}   
	/**
	 * 属性pk_level的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newPk_level String
	 */
	public void setPk_level (String newPk_level ) {
	 	this.pk_level = newPk_level;
	} 	  
	/**
	 * 属性free7的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getFree7 () {
		return free7;
	}   
	/**
	 * 属性free7的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree7 String
	 */
	public void setFree7 (String newFree7 ) {
	 	this.free7 = newFree7;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef10 UFDouble
	 */
	public void setVdef10 (UFDouble newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
	/**
	 * 属性hsprice的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getHsprice () {
		return hsprice;
	}   
	/**
	 * 属性hsprice的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newHsprice UFDouble
	 */
	public void setHsprice (UFDouble newHsprice ) {
	 	this.hsprice = newHsprice;
	} 	  
	/**
	 * 属性vdef15的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef15 () {
		return vdef15;
	}   
	/**
	 * 属性vdef15的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef15 String
	 */
	public void setVdef15 (String newVdef15 ) {
	 	this.vdef15 = newVdef15;
	} 	  
	/**
	 * 属性vdef14的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef14 () {
		return vdef14;
	}   
	/**
	 * 属性vdef14的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef14 String
	 */
	public void setVdef14 (String newVdef14 ) {
	 	this.vdef14 = newVdef14;
	} 	  
	/**
	 * 属性free5的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getFree5 () {
		return free5;
	}   
	/**
	 * 属性free5的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree5 String
	 */
	public void setFree5 (String newFree5 ) {
	 	this.free5 = newFree5;
	} 	  
	/**
	 * 属性free1_2的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public Integer getFree1_2 () {
		return free1_2;
	}   
	/**
	 * 属性free1_2的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree1_2 String
	 */
	public void setFree1_2 (Integer newFree1_2 ) {
	 	this.free1_2 = newFree1_2;
	} 	  
	/**
	 * 属性free10的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getFree10 () {
		return free10;
	}   
	/**
	 * 属性free10的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree10 String
	 */
	public void setFree10 (String newFree10 ) {
	 	this.free10 = newFree10;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef7 UFDouble
	 */
	public void setVdef7 (UFDouble newVdef7 ) {
	 	this.vdef7 = newVdef7;
	} 	  
	/**
	 * 属性pk_pricepolicy_b的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getPk_pricepolicy_b () {
		return pk_pricepolicy_b;
	}   
	/**
	 * 属性pk_pricepolicy_b的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newPk_pricepolicy_b String
	 */
	public void setPk_pricepolicy_b (String newPk_pricepolicy_b ) {
	 	this.pk_pricepolicy_b = newPk_pricepolicy_b;
	} 	  
	/**
	 * 属性free6的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getFree6 () {
		return free6;
	}   
	/**
	 * 属性free6的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree6 String
	 */
	public void setFree6 (String newFree6 ) {
	 	this.free6 = newFree6;
	} 	  
	/**
	 * 属性free2_1的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public String getFree2_1 () {
		return free2_1;
	}   
	/**
	 * 属性free2_1的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree2_1 UFDouble
	 */
	public void setFree2_1 (String newFree2_1 ) {
	 	this.free2_1 = newFree2_1;
	} 	  
	/**
	 * 属性pk_productline的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getPk_productline () {
		return pk_productline;
	}   
	/**
	 * 属性pk_productline的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newPk_productline String
	 */
	public void setPk_productline (String newPk_productline ) {
	 	this.pk_productline = newPk_productline;
	} 	  
	/**
	 * 属性vdef16的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef16 () {
		return vdef16;
	}   
	/**
	 * 属性vdef16的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef16 String
	 */
	public void setVdef16 (String newVdef16 ) {
	 	this.vdef16 = newVdef16;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef2 UFDouble
	 */
	public void setVdef2 (UFDouble newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef5 UFDouble
	 */
	public void setVdef5 (UFDouble newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性vdef19的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef19 () {
		return vdef19;
	}   
	/**
	 * 属性vdef19的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef19 String
	 */
	public void setVdef19 (String newVdef19 ) {
	 	this.vdef19 = newVdef19;
	} 	  
	/**
	 * 属性memo的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getMemo () {
		return memo;
	}   
	/**
	 * 属性memo的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newMemo String
	 */
	public void setMemo (String newMemo ) {
	 	this.memo = newMemo;
	} 	  
	/**
	 * 属性free9的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getFree9 () {
		return free9;
	}   
	/**
	 * 属性free9的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree9 String
	 */
	public void setFree9 (String newFree9 ) {
	 	this.free9 = newFree9;
	} 	  
	/**
	 * 属性vdef18的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef18 () {
		return vdef18;
	}   
	/**
	 * 属性vdef18的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef18 String
	 */
	public void setVdef18 (String newVdef18 ) {
	 	this.vdef18 = newVdef18;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef4 UFDouble
	 */
	public void setVdef4 (UFDouble newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性free3_1的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public String getFree3_1 () {
		return free3_1;
	}   
	/**
	 * 属性free3_1的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree3_1 UFDouble
	 */
	public void setFree3_1 (String newFree3_1 ) {
	 	this.free3_1 = newFree3_1;
	} 	  
	/**
	 * 属性vdef17的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef17 () {
		return vdef17;
	}   
	/**
	 * 属性vdef17的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef17 String
	 */
	public void setVdef17 (String newVdef17 ) {
	 	this.vdef17 = newVdef17;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef1 UFDouble
	 */
	public void setVdef1 (UFDouble newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef20的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef20 () {
		return vdef20;
	}   
	/**
	 * 属性vdef20的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef20 String
	 */
	public void setVdef20 (String newVdef20 ) {
	 	this.vdef20 = newVdef20;
	} 	  
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef8 UFDouble
	 */
	public void setVdef8 (UFDouble newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性free8的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getFree8 () {
		return free8;
	}   
	/**
	 * 属性free8的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree8 String
	 */
	public void setFree8 (String newFree8 ) {
	 	this.free8 = newFree8;
	} 	  
	/**
	 * 属性free2_0的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public String getFree2_0 () {
		return free2_0;
	}   
	/**
	 * 属性free2_0的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree2_0 UFDouble
	 */
	public void setFree2_0 (String newFree2_0 ) {
	 	this.free2_0 = newFree2_0;
	} 	  
	/**
	 * 属性pk_zkway的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getPk_zkway () {
		return pk_zkway;
	}   
	/**
	 * 属性pk_zkway的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newPk_zkway String
	 */
	public void setPk_zkway (String newPk_zkway ) {
	 	this.pk_zkway = newPk_zkway;
	} 	  
	/**
	 * 属性pk_pricepolicy的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getPk_pricepolicy () {
		return pk_pricepolicy;
	}   
	/**
	 * 属性pk_pricepolicy的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newPk_pricepolicy String
	 */
	public void setPk_pricepolicy (String newPk_pricepolicy ) {
	 	this.pk_pricepolicy = newPk_pricepolicy;
	} 	  
	/**
	 * 属性free4_2的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public Integer getFree4_2 () {
		return free4_2;
	}   
	/**
	 * 属性free4_2的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree4_2 String
	 */
	public void setFree4_2 (Integer newFree4_2 ) {
	 	this.free4_2 = newFree4_2;
	} 	  
	/**
	 * 属性free1_0的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public String getFree1_0 () {
		return free1_0;
	}   
	/**
	 * 属性free1_0的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree1_0 UFDouble
	 */
	public void setFree1_0 (String newFree1_0 ) {
	 	this.free1_0 = newFree1_0;
	} 	  
	/**
	 * 属性free1_1的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public String getFree1_1 () {
		return free1_1;
	}   
	/**
	 * 属性free1_1的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree1_1 UFDouble
	 */
	public void setFree1_1 (String newFree1_1 ) {
	 	this.free1_1 = newFree1_1;
	} 	  
	/**
	 * 属性free4_0的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public String getFree4_0 () {
		return free4_0;
	}   
	/**
	 * 属性free4_0的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree4_0 UFDouble
	 */
	public void setFree4_0 (String newFree4_0 ) {
	 	this.free4_0 = newFree4_0;
	} 	  
	/**
	 * 属性vdef13的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef13 () {
		return vdef13;
	}   
	/**
	 * 属性vdef13的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef13 String
	 */
	public void setVdef13 (String newVdef13 ) {
	 	this.vdef13 = newVdef13;
	} 	  
	/**
	 * 属性free3_2的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public Integer getFree3_2 () {
		return free3_2;
	}   
	/**
	 * 属性free3_2的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree3_2 String
	 */
	public void setFree3_2 (Integer newFree3_2 ) {
	 	this.free3_2 = newFree3_2;
	} 	  
	/**
	 * 属性pk_deliveryplan_b的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getPk_deliveryplan_b () {
		return pk_deliveryplan_b;
	}   
	/**
	 * 属性pk_deliveryplan_b的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newPk_deliveryplan_b String
	 */
	public void setPk_deliveryplan_b (String newPk_deliveryplan_b ) {
	 	this.pk_deliveryplan_b = newPk_deliveryplan_b;
	} 	  
	/**
	 * 属性vdef11的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef11 () {
		return vdef11;
	}   
	/**
	 * 属性vdef11的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef11 String
	 */
	public void setVdef11 (String newVdef11 ) {
	 	this.vdef11 = newVdef11;
	} 	  
	/**
	 * 属性free2_2的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public Integer getFree2_2 () {
		return free2_2;
	}   
	/**
	 * 属性free2_2的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree2_2 String
	 */
	public void setFree2_2 (Integer newFree2_2 ) {
	 	this.free2_2 = newFree2_2;
	} 	  
	/**
	 * 属性free3_0的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public String getFree3_0 () {
		return free3_0;
	}   
	/**
	 * 属性free3_0的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree3_0 UFDouble
	 */
	public void setFree3_0 (String newFree3_0 ) {
	 	this.free3_0 = newFree3_0;
	} 	  
	/**
	 * 属性vdef12的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef12 () {
		return vdef12;
	}   
	/**
	 * 属性vdef12的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef12 String
	 */
	public void setVdef12 (String newVdef12 ) {
	 	this.vdef12 = newVdef12;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef3 UFDouble
	 */
	public void setVdef3 (UFDouble newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef6 UFDouble
	 */
	public void setVdef6 (UFDouble newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性pk_invmandoc的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getPk_invmandoc () {
		return pk_invmandoc;
	}   
	/**
	 * 属性pk_invmandoc的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newPk_invmandoc String
	 */
	public void setPk_invmandoc (String newPk_invmandoc ) {
	 	this.pk_invmandoc = newPk_invmandoc;
	} 	  
	/**
	 * 属性free4_1的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public String getFree4_1 () {
		return free4_1;
	}   
	/**
	 * 属性free4_1的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newFree4_1 UFDouble
	 */
	public void setFree4_1 (String newFree4_1 ) {
	 	this.free4_1 = newFree4_1;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-11-12 09:51:36
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_pricepolicy";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-11-12 09:51:36
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_pricepolicy_b";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2011-11-12 09:51:36
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "gt_pricepolicy_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-11-12 09:51:36
	  */
     public PricePolicybVO() {
		super();	
	}    
} 
