/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.gt.gs.gs24;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2011-11-14 10:12:23
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class ColumnShowbVO extends SuperVO {
	private String pk_corp;
	private String pk_columnshow;
	private UFDateTime ts;
	private String pk_columnshow_b;
	private Integer dr;
	private UFBoolean showflag;
	private String name;
	private String listcode;
	private String listname;
	private String free;
	private String pk_doclist;

	public static final String PK_CORP = "pk_corp";
	public static final String PK_COLUMNSHOW = "pk_columnshow";
	public static final String PK_COLUMNSHOW_B = "pk_columnshow_b";
	public static final String SHOWFLAG = "showflag";
	public static final String NAME = "name";
	public static final String LISTCODE = "listcode";
	public static final String FREE = "free";
	public static final String PK_DOCLIST = "pk_doclist";
	public static final String LISTNAME = "listname";
		
	
	public String getListname() {
		return listname;
	}
	public void setListname(String listname) {
		this.listname = listname;
	}
	public String getPk_doclist() {
		return pk_doclist;
	}
	public void setPk_doclist(String pk_doclist) {
		this.pk_doclist = pk_doclist;
	}
	public String getListcode() {
		return listcode;
	}
	public void setListcode(String listcode) {
		this.listcode = listcode;
	}
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2011-11-14 10:12:23
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2011-11-14 10:12:23
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性pk_columnshow的Getter方法.
	 * 创建日期:2011-11-14 10:12:23
	 * @return String
	 */
	public String getPk_columnshow () {
		return pk_columnshow;
	}   
	/**
	 * 属性pk_columnshow的Setter方法.
	 * 创建日期:2011-11-14 10:12:23
	 * @param newPk_columnshow String
	 */
	public void setPk_columnshow (String newPk_columnshow ) {
	 	this.pk_columnshow = newPk_columnshow;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2011-11-14 10:12:23
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2011-11-14 10:12:23
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性pk_columnshow_b的Getter方法.
	 * 创建日期:2011-11-14 10:12:23
	 * @return String
	 */
	public String getPk_columnshow_b () {
		return pk_columnshow_b;
	}   
	/**
	 * 属性pk_columnshow_b的Setter方法.
	 * 创建日期:2011-11-14 10:12:23
	 * @param newPk_columnshow_b String
	 */
	public void setPk_columnshow_b (String newPk_columnshow_b ) {
	 	this.pk_columnshow_b = newPk_columnshow_b;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2011-11-14 10:12:23
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2011-11-14 10:12:23
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性showflag的Getter方法.
	 * 创建日期:2011-11-14 10:12:23
	 * @return UFBoolean
	 */
	public UFBoolean getShowflag () {
		return showflag;
	}   
	/**
	 * 属性showflag的Setter方法.
	 * 创建日期:2011-11-14 10:12:23
	 * @param newShowflag UFBoolean
	 */
	public void setShowflag (UFBoolean newShowflag ) {
	 	this.showflag = newShowflag;
	} 	  
	/**
	 * 属性name的Getter方法.
	 * 创建日期:2011-11-14 10:12:23
	 * @return String
	 */
	public String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.
	 * 创建日期:2011-11-14 10:12:23
	 * @param newName String
	 */
	public void setName (String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性free的Getter方法.
	 * 创建日期:2011-11-14 10:12:23
	 * @return String
	 */
	public String getFree () {
		return free;
	}   
	/**
	 * 属性free的Setter方法.
	 * 创建日期:2011-11-14 10:12:23
	 * @param newFree String
	 */
	public void setFree (String newFree ) {
	 	this.free = newFree;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-11-14 10:12:23
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_columnshow";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-11-14 10:12:23
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_columnshow_b";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2011-11-14 10:12:23
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "gt_columnshow_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-11-14 10:12:23
	  */
     public ColumnShowbVO() {
		super();	
	}    
} 
