/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.jyglgt.j400670;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2011-11-12 09:51:36
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class PricePolicyVO extends SuperVO {
	private String pk_corp;
	private UFDateTime ts;
	private String billtype;
	private UFDouble vdef9;
	private String vapprovednote;
	private String vdef17;
	private String vbillcode;
	private UFDate sdate;
	private String vdef20;
	private UFDouble vdef1;
	private UFDouble vdef8;
	private UFDouble vdef10;
	private String vunapproveid;
	private String pk_busitype;
	private String vunapprovednote;
	private String vapproveid;
	private String vapprovenote;
	private String pk_pricepolicy;
	private String vdef15;
	private String product;
	private String vdef14;
	private UFDouble vdef7;
	private UFTime etime;
	private String vdef13;
	private UFTime stime;
	private String vdef16;
	private UFDouble vdef2;
	private String vdef11;
	private UFDouble vdef5;
	private String vdef19;
	private UFDate edate;
	private Integer vbillstatus;
	private String memo;
	private UFDate vapprovedate;
	private UFDate dapprovedate;
	private String vdef12;
	private UFDate dmakedate;
	private UFDouble vdef3;
	private UFDouble vdef6;
	private Integer dr;
	private String vdef18;
	private UFDouble vdef4;
	private String pk_operator;
	private UFDate vunapprovedate;

	public static final String PK_CORP = "pk_corp";
	public static final String BILLTYPE = "billtype";
	public static final String VDEF9 = "vdef9";
	public static final String VAPPROVEDNOTE = "vapprovednote";
	public static final String VDEF17 = "vdef17";
	public static final String VBILLCODE = "vbillcode";
	public static final String SDATE = "sdate";
	public static final String VDEF20 = "vdef20";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF8 = "vdef8";
	public static final String VDEF10 = "vdef10";
	public static final String VUNAPPROVEID = "vunapproveid";
	public static final String PK_BUSITYPE = "pk_busitype";
	public static final String VUNAPPROVEDNOTE = "vunapprovednote";
	public static final String VAPPROVEID = "vapproveid";
	public static final String PK_PRICEPOLICY = "pk_pricepolicy";
	public static final String VDEF15 = "vdef15";
	public static final String PRODUCT = "product";
	public static final String VDEF14 = "vdef14";
	public static final String VDEF7 = "vdef7";
	public static final String ETIME = "etime";
	public static final String VDEF13 = "vdef13";
	public static final String STIME = "stime";
	public static final String VDEF16 = "vdef16";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF11 = "vdef11";
	public static final String VDEF5 = "vdef5";
	public static final String VDEF19 = "vdef19";
	public static final String EDATE = "edate";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String MEMO = "memo";
	public static final String VAPPROVEDATE = "vapprovedate";
	public static final String VDEF12 = "vdef12";
	public static final String DMAKEDATE = "dmakedate";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF6 = "vdef6";
	public static final String VDEF18 = "vdef18";
	public static final String VDEF4 = "vdef4";
	public static final String PK_OPERATOR = "pk_operator";
	public static final String VUNAPPROVEDATE = "vunapprovedate";
		
	
	
	public String getVapprovenote() {
		return vapprovenote;
	}
	public void setVapprovenote(String vapprovenote) {
		this.vapprovenote = vapprovenote;
	}
	public UFDate getDapprovedate() {
		return dapprovedate;
	}
	public void setDapprovedate(UFDate dapprovedate) {
		this.dapprovedate = dapprovedate;
	}
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性billtype的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getBilltype () {
		return billtype;
	}   
	/**
	 * 属性billtype的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newBilltype String
	 */
	public void setBilltype (String newBilltype ) {
	 	this.billtype = newBilltype;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef9 UFDouble
	 */
	public void setVdef9 (UFDouble newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性vapprovednote的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVapprovednote () {
		return vapprovednote;
	}   
	/**
	 * 属性vapprovednote的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVapprovednote String
	 */
	public void setVapprovednote (String newVapprovednote ) {
	 	this.vapprovednote = newVapprovednote;
	} 	  
	/**
	 * 属性vdef17的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef17 () {
		return vdef17;
	}   
	/**
	 * 属性vdef17的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef17 String
	 */
	public void setVdef17 (String newVdef17 ) {
	 	this.vdef17 = newVdef17;
	} 	  
	/**
	 * 属性vbillcode的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVbillcode () {
		return vbillcode;
	}   
	/**
	 * 属性vbillcode的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVbillcode String
	 */
	public void setVbillcode (String newVbillcode ) {
	 	this.vbillcode = newVbillcode;
	} 	  
	/**
	 * 属性sdate的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDate
	 */
	public UFDate getSdate () {
		return sdate;
	}   
	/**
	 * 属性sdate的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newSdate UFDate
	 */
	public void setSdate (UFDate newSdate ) {
	 	this.sdate = newSdate;
	} 	  
	/**
	 * 属性vdef20的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef20 () {
		return vdef20;
	}   
	/**
	 * 属性vdef20的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef20 String
	 */
	public void setVdef20 (String newVdef20 ) {
	 	this.vdef20 = newVdef20;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef1 UFDouble
	 */
	public void setVdef1 (UFDouble newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef8 UFDouble
	 */
	public void setVdef8 (UFDouble newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef10 UFDouble
	 */
	public void setVdef10 (UFDouble newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
	/**
	 * 属性vunapproveid的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVunapproveid () {
		return vunapproveid;
	}   
	/**
	 * 属性vunapproveid的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVunapproveid String
	 */
	public void setVunapproveid (String newVunapproveid ) {
	 	this.vunapproveid = newVunapproveid;
	} 	  
	/**
	 * 属性pk_busitype的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getPk_busitype () {
		return pk_busitype;
	}   
	/**
	 * 属性pk_busitype的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newPk_busitype String
	 */
	public void setPk_busitype (String newPk_busitype ) {
	 	this.pk_busitype = newPk_busitype;
	} 	  
	/**
	 * 属性vunapprovednote的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVunapprovednote () {
		return vunapprovednote;
	}   
	/**
	 * 属性vunapprovednote的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVunapprovednote String
	 */
	public void setVunapprovednote (String newVunapprovednote ) {
	 	this.vunapprovednote = newVunapprovednote;
	} 	  
	/**
	 * 属性vapproveid的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVapproveid () {
		return vapproveid;
	}   
	/**
	 * 属性vapproveid的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVapproveid String
	 */
	public void setVapproveid (String newVapproveid ) {
	 	this.vapproveid = newVapproveid;
	} 	  
	/**
	 * 属性pk_pricepolicy的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getPk_pricepolicy () {
		return pk_pricepolicy;
	}   
	/**
	 * 属性pk_pricepolicy的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newPk_pricepolicy String
	 */
	public void setPk_pricepolicy (String newPk_pricepolicy ) {
	 	this.pk_pricepolicy = newPk_pricepolicy;
	} 	  
	/**
	 * 属性vdef15的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef15 () {
		return vdef15;
	}   
	/**
	 * 属性vdef15的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef15 String
	 */
	public void setVdef15 (String newVdef15 ) {
	 	this.vdef15 = newVdef15;
	} 	  
	/**
	 * 属性product的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getProduct () {
		return product;
	}   
	/**
	 * 属性product的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newProduct String
	 */
	public void setProduct (String newProduct ) {
	 	this.product = newProduct;
	} 	  
	/**
	 * 属性vdef14的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef14 () {
		return vdef14;
	}   
	/**
	 * 属性vdef14的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef14 String
	 */
	public void setVdef14 (String newVdef14 ) {
	 	this.vdef14 = newVdef14;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef7 UFDouble
	 */
	public void setVdef7 (UFDouble newVdef7 ) {
	 	this.vdef7 = newVdef7;
	}
	
	public UFTime getEtime() {
		return etime;
	}
	public void setEtime(UFTime etime) {
		this.etime = etime;
	}
	/**
	 * 属性vdef13的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef13 () {
		return vdef13;
	}   
	/**
	 * 属性vdef13的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef13 String
	 */
	public void setVdef13 (String newVdef13 ) {
	 	this.vdef13 = newVdef13;
	} 	  
	/**
	 * 属性stime的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDateTime
	 */
	public UFTime getStime () {
		return stime;
	}   
	/**
	 * 属性stime的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newStime UFDateTime
	 */
	public void setStime (UFTime newStime ) {
	 	this.stime = newStime;
	} 	  
	/**
	 * 属性vdef16的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef16 () {
		return vdef16;
	}   
	/**
	 * 属性vdef16的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef16 String
	 */
	public void setVdef16 (String newVdef16 ) {
	 	this.vdef16 = newVdef16;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef2 UFDouble
	 */
	public void setVdef2 (UFDouble newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef11的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef11 () {
		return vdef11;
	}   
	/**
	 * 属性vdef11的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef11 String
	 */
	public void setVdef11 (String newVdef11 ) {
	 	this.vdef11 = newVdef11;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef5 UFDouble
	 */
	public void setVdef5 (UFDouble newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性vdef19的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef19 () {
		return vdef19;
	}   
	/**
	 * 属性vdef19的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef19 String
	 */
	public void setVdef19 (String newVdef19 ) {
	 	this.vdef19 = newVdef19;
	} 	  
	/**
	 * 属性edate的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDate
	 */
	public UFDate getEdate () {
		return edate;
	}   
	/**
	 * 属性edate的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newEdate UFDate
	 */
	public void setEdate (UFDate newEdate ) {
	 	this.edate = newEdate;
	} 	  
	/**
	 * 属性vbillstatus的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public Integer getVbillstatus () {
		return vbillstatus;
	}   
	/**
	 * 属性vbillstatus的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVbillstatus UFDouble
	 */
	public void setVbillstatus (Integer newVbillstatus ) {
	 	this.vbillstatus = newVbillstatus;
	} 	  
	/**
	 * 属性memo的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getMemo () {
		return memo;
	}   
	/**
	 * 属性memo的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newMemo String
	 */
	public void setMemo (String newMemo ) {
	 	this.memo = newMemo;
	} 	  
	/**
	 * 属性vapprovedate的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDate
	 */
	public UFDate getVapprovedate () {
		return vapprovedate;
	}   
	/**
	 * 属性vapprovedate的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVapprovedate UFDate
	 */
	public void setVapprovedate (UFDate newVapprovedate ) {
	 	this.vapprovedate = newVapprovedate;
	} 	  
	/**
	 * 属性vdef12的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef12 () {
		return vdef12;
	}   
	/**
	 * 属性vdef12的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef12 String
	 */
	public void setVdef12 (String newVdef12 ) {
	 	this.vdef12 = newVdef12;
	} 	  
	/**
	 * 属性dmakedate的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDate
	 */
	public UFDate getDmakedate () {
		return dmakedate;
	}   
	/**
	 * 属性dmakedate的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newDmakedate UFDate
	 */
	public void setDmakedate (UFDate newDmakedate ) {
	 	this.dmakedate = newDmakedate;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef3 UFDouble
	 */
	public void setVdef3 (UFDouble newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef6 UFDouble
	 */
	public void setVdef6 (UFDouble newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性vdef18的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getVdef18 () {
		return vdef18;
	}   
	/**
	 * 属性vdef18的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef18 String
	 */
	public void setVdef18 (String newVdef18 ) {
	 	this.vdef18 = newVdef18;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDouble
	 */
	public UFDouble getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVdef4 UFDouble
	 */
	public void setVdef4 (UFDouble newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性pk_operator的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return String
	 */
	public String getPk_operator () {
		return pk_operator;
	}   
	/**
	 * 属性pk_operator的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newPk_operator String
	 */
	public void setPk_operator (String newPk_operator ) {
	 	this.pk_operator = newPk_operator;
	} 	  
	/**
	 * 属性vunapprovedate的Getter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @return UFDate
	 */
	public UFDate getVunapprovedate () {
		return vunapprovedate;
	}   
	/**
	 * 属性vunapprovedate的Setter方法.
	 * 创建日期:2011-11-12 09:51:36
	 * @param newVunapprovedate UFDate
	 */
	public void setVunapprovedate (UFDate newVunapprovedate ) {
	 	this.vunapprovedate = newVunapprovedate;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-11-12 09:51:36
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-11-12 09:51:36
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_pricepolicy";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2011-11-12 09:51:36
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "gt_pricepolicy";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-11-12 09:51:36
	  */
     public PricePolicyVO() {
		super();	
	}    
} 
